// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Fiona_Project

#include "../ui.h"

lv_obj_t * ui_Screen_SplashScreen = NULL;
lv_obj_t * ui_SplashScreen_Image_Logo = NULL;
lv_obj_t * ui_SplashScreen_Label_Clock = NULL;
lv_obj_t * ui_SplashScreen_Label_FionaSpeachLabel = NULL;
// event funtions
void ui_event_SplashScreen_Label_Clock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnScreenSaverClk(e);
    }
}

// build funtions

void ui_Screen_SplashScreen_screen_init(void)
{
    ui_Screen_SplashScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_SplashScreen,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_Screen_SplashScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_SplashScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SplashScreen_Image_Logo = lv_image_create(ui_Screen_SplashScreen);
    lv_image_set_src(ui_SplashScreen_Image_Logo, &ui_img_fordlogo_png);
    lv_obj_set_width(ui_SplashScreen_Image_Logo, LV_SIZE_CONTENT);   /// 935
    lv_obj_set_height(ui_SplashScreen_Image_Logo, LV_SIZE_CONTENT);    /// 404
    lv_obj_set_align(ui_SplashScreen_Image_Logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SplashScreen_Image_Logo, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SplashScreen_Image_Logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SplashScreen_Label_Clock = lv_label_create(ui_Screen_SplashScreen);
    lv_obj_set_width(ui_SplashScreen_Label_Clock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SplashScreen_Label_Clock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SplashScreen_Label_Clock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SplashScreen_Label_Clock, "20.04.2026 года\n00:00:00\nПонедельник");
    lv_obj_add_flag(ui_SplashScreen_Label_Clock, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_SplashScreen_Label_Clock, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SplashScreen_Label_Clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SplashScreen_Label_Clock, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SplashScreen_Label_Clock, &ui_font_SSaverFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SplashScreen_Label_FionaSpeachLabel = lv_label_create(ui_Screen_SplashScreen);
    lv_obj_set_width(ui_SplashScreen_Label_FionaSpeachLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SplashScreen_Label_FionaSpeachLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SplashScreen_Label_FionaSpeachLabel, 0);
    lv_obj_set_y(ui_SplashScreen_Label_FionaSpeachLabel, -80);
    lv_obj_set_align(ui_SplashScreen_Label_FionaSpeachLabel, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_SplashScreen_Label_FionaSpeachLabel, "Привет, Куда поедем?");
    lv_obj_set_style_text_color(ui_SplashScreen_Label_FionaSpeachLabel, lv_color_hex(0xFFFF00),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SplashScreen_Label_FionaSpeachLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SplashScreen_Label_FionaSpeachLabel, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SplashScreen_Label_FionaSpeachLabel, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SplashScreen_Label_Clock, ui_event_SplashScreen_Label_Clock, LV_EVENT_ALL, NULL);

}

void ui_Screen_SplashScreen_screen_destroy(void)
{
    if(ui_Screen_SplashScreen) lv_obj_del(ui_Screen_SplashScreen);

    // NULL screen variables
    ui_Screen_SplashScreen = NULL;
    ui_SplashScreen_Image_Logo = NULL;
    ui_SplashScreen_Label_Clock = NULL;
    ui_SplashScreen_Label_FionaSpeachLabel = NULL;

}
