// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Fiona_Project

#ifndef UI_SCREEN_CLIMATECONTROL_H
#define UI_SCREEN_CLIMATECONTROL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_ClimateControl
extern void ui_Screen_ClimateControl_screen_init(void);
extern void ui_Screen_ClimateControl_screen_destroy(void);
extern lv_obj_t * ui_Screen_ClimateControl;
extern void ui_event_ClimateControl_Label_LabelCC(lv_event_t * e);
extern lv_obj_t * ui_ClimateControl_Label_LabelCC;
extern lv_obj_t * ui_ClimateControl_Label_Label5;
extern void ui_event_ClimateControl_Slider_TempSlider(lv_event_t * e);
extern lv_obj_t * ui_ClimateControl_Slider_TempSlider;
extern lv_obj_t * ui_ClimateControl_Label_Label2;
extern void ui_event_ClimateControl_Slider_AlignSlider(lv_event_t * e);
extern lv_obj_t * ui_ClimateControl_Slider_AlignSlider;
extern lv_obj_t * ui_ClimateControl_Label_Label3;
extern void ui_event_ClimateControl_Slider_FlowSlider(lv_event_t * e);
extern lv_obj_t * ui_ClimateControl_Slider_FlowSlider;
extern void ui_event_ClimateControl_Switch_TempSwitch(lv_event_t * e);
extern lv_obj_t * ui_ClimateControl_Switch_TempSwitch;
extern void ui_event_ClimateControl_Switch_AlignSwitch(lv_event_t * e);
extern lv_obj_t * ui_ClimateControl_Switch_AlignSwitch;
extern void ui_event_ClimateControl_Switch_FlpwSwitch(lv_event_t * e);
extern lv_obj_t * ui_ClimateControl_Switch_FlpwSwitch;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

