// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Fiona_Project

#include "../ui.h"

lv_obj_t * ui_Screen_System = NULL;
lv_obj_t * ui_System_Tabview_SystemTabView = NULL;
lv_obj_t * ui_System_Tabpage_Refuel = NULL;
lv_obj_t * ui_System_Bar_FuelTank = NULL;
lv_obj_t * ui_System_Label_Zapravleno = NULL;
lv_obj_t * ui_System_Textarea_TAPrise = NULL;
lv_obj_t * ui_System_Label_LitrPrise = NULL;
lv_obj_t * ui_System_Label_Label4 = NULL;
lv_obj_t * ui_System_Textarea_TAODO = NULL;
lv_obj_t * ui_System_Label_Calibrate = NULL;
lv_obj_t * ui_System_Switch_SwitchFullTank = NULL;
lv_obj_t * ui_System_Textarea_TACurrentFuel = NULL;
lv_obj_t * ui_System_Label_SaveLBtn = NULL;
lv_obj_t * ui_System_Textarea_TAFuelToAdd = NULL;
lv_obj_t * ui_System_Tabpage_Setting = NULL;
lv_obj_t * ui_System_Textarea_TimeTextArea = NULL;
lv_obj_t * ui_System_Label_SaveLBtn2 = NULL;
lv_obj_t * ui_System_Label_TimeLbl = NULL;
lv_obj_t * ui_System_Label_TimeLBtn = NULL;
lv_obj_t * ui_System_Label_TimeLBtnR = NULL;
lv_obj_t * ui_System_Label_LightLbl = NULL;
lv_obj_t * ui_System_Label_LightMarkLbl = NULL;
lv_obj_t * ui_System_Label_DarkMarkLbl = NULL;
lv_obj_t * ui_System_Slider_SliderLight = NULL;
lv_obj_t * ui_System_Slider_SliderDark = NULL;
lv_obj_t * ui_System_Label_CurrentLight = NULL;
lv_obj_t * ui_System_Slider_SliderBridges = NULL;
lv_obj_t * ui_System_Label_CalibrateMCU = NULL;
lv_obj_t * ui_System_Label_FanPlus = NULL;
lv_obj_t * ui_System_Label_FanMinus = NULL;
lv_obj_t * ui_System_Label_FanApply = NULL;
lv_obj_t * ui_System_Label_FanSaved = NULL;
lv_obj_t * ui_System_Label_FanCalibLbl = NULL;
lv_obj_t * ui_System_Dropdown_DropdownFanDot = NULL;
lv_obj_t * ui_System_Tabpage_DebugArduino = NULL;
lv_obj_t * ui_System_Textarea_TextAreaArduino = NULL;
lv_obj_t * ui_System_Tabpage_DebugESP32 = NULL;
lv_obj_t * ui_System_Textarea_TextAreaESP = NULL;
lv_obj_t * ui_System_Tabpage_DebugScreen = NULL;
lv_obj_t * ui_System_Textarea_TextAreaScreen = NULL;
lv_obj_t * ui_System_Image_SDBack = NULL;
lv_obj_t * ui_System_Image_SDGrey = NULL;
lv_obj_t * ui_System_Image_SDRed = NULL;
lv_obj_t * ui_System_Image_ArduinoBack = NULL;
lv_obj_t * ui_System_Image_ArduinoGrey = NULL;
lv_obj_t * ui_System_Image_ArduinoRed = NULL;
lv_obj_t * ui_System_Image_ESP32Back = NULL;
lv_obj_t * ui_System_Image_ESP32Grey = NULL;
lv_obj_t * ui_System_Image_ESP32Red = NULL;
lv_obj_t * ui_System_Image_SpeachBack = NULL;
lv_obj_t * ui_System_Image_SpeachGrey = NULL;
lv_obj_t * ui_System_Image_SpeachRed = NULL;
lv_obj_t * ui_System_Image_StatBack = NULL;
lv_obj_t * ui_System_Image_StatGrey = NULL;
lv_obj_t * ui_System_Image_StatRed = NULL;
lv_obj_t * ui_System_Image_PresetBack = NULL;
lv_obj_t * ui_System_Image_PresetGrey = NULL;
lv_obj_t * ui_System_Image_PresetRed = NULL;
lv_obj_t * ui_System_Label_Label6 = NULL;
lv_obj_t * ui_System_Label_Label7 = NULL;
lv_obj_t * ui_System_Label_Label8 = NULL;
lv_obj_t * ui_System_Label_Label9 = NULL;
lv_obj_t * ui_System_Label_Label10 = NULL;
lv_obj_t * ui_System_Label_Label11 = NULL;
lv_obj_t * ui_System_Label_Label1 = NULL;
lv_obj_t * ui_System_Keyboard_KeyboardForTab = NULL;
// event funtions
void ui_event_System_Tabpage_Refuel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        OnRefuelFocused(e);
        _ui_flag_modify(ui_System_Switch_SwitchFullTank, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_System_Label_Zapravleno, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_System_Textarea_TAFuelToAdd, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_System_Textarea_TAPrise, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_System_Label_LitrPrise, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_System_Label_Calibrate, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_System_Keyboard_KeyboardForTab, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_System_Label_SaveLBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        OnRefueDefFocused(e);
    }
}

void ui_event_System_Textarea_TAPrise(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_System_Keyboard_KeyboardForTab,  ui_System_Textarea_TAPrise);
        _ui_flag_modify(ui_System_Keyboard_KeyboardForTab, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_System_Keyboard_KeyboardForTab, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_flag_modify(ui_System_Label_SaveLBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_System_Textarea_TAODO(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_System_Keyboard_KeyboardForTab,  ui_System_Textarea_TAODO);
        _ui_flag_modify(ui_System_Keyboard_KeyboardForTab, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_System_Keyboard_KeyboardForTab, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_flag_modify(ui_System_Label_SaveLBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_System_Switch_SwitchFullTank(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnCalibrateClicked(e);
    }
}

void ui_event_System_Textarea_TACurrentFuel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_System_Keyboard_KeyboardForTab,  ui_System_Textarea_TACurrentFuel);
        _ui_flag_modify(ui_System_Keyboard_KeyboardForTab, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_System_Keyboard_KeyboardForTab, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_flag_modify(ui_System_Label_Zapravleno, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_System_Textarea_TAFuelToAdd, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_System_Label_LitrPrise, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_System_Textarea_TAPrise, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_System_Label_Calibrate, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_System_Switch_SwitchFullTank, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_System_Label_SaveLBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_System_Label_SaveLBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SaveChangeBtnClick(e);
        _ui_flag_modify(ui_System_Label_SaveLBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_System_Textarea_TAFuelToAdd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_System_Keyboard_KeyboardForTab,  ui_System_Textarea_TAFuelToAdd);
        _ui_flag_modify(ui_System_Keyboard_KeyboardForTab, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_System_Keyboard_KeyboardForTab, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_flag_modify(ui_System_Label_SaveLBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_System_Tabpage_Setting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        SettingFocused(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        SettingDeFocused(e);
    }
}

void ui_event_System_Textarea_TimeTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_System_Keyboard_KeyboardForTab, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_System_Keyboard_KeyboardForTab,  ui_System_Textarea_TimeTextArea);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_System_Keyboard_KeyboardForTab, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_flag_modify(ui_System_Keyboard_KeyboardForTab, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_System_Label_SaveLBtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SaveSettingChangeBtnClick(e);
        _ui_flag_modify(ui_System_Label_SaveLBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_System_Label_TimeLBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SetTimeClicked(e);
        _ui_flag_modify(ui_System_Label_TimeLBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_System_Label_TimeLBtnR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SetTimeRClicked(e);
        _ui_flag_modify(ui_System_Label_TimeLBtnR, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_System_Slider_SliderLight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnLightSliderThresholdChanged(e);
    }
}

void ui_event_System_Slider_SliderDark(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnSliderThresholdChanged(e);
    }
}

void ui_event_System_Slider_SliderBridges(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnLightSliderChanged(e);
    }
}

void ui_event_System_Label_CalibrateMCU(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CalibrateMCUBtnClick(e);
        _ui_screen_change(&ui_Screen_DashBoard, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen_DashBoard_screen_init);
    }
}

void ui_event_System_Label_FanPlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        FanPlusClk(e);
    }
}

void ui_event_System_Label_FanMinus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        FanMinusClk(e);
    }
}

void ui_event_System_Label_FanApply(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        FanSaveApply(e);
    }
}

void ui_event_System_Label_FanSaved(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        FanPlusClk(e);
    }
}

void ui_event_System_Dropdown_DropdownFanDot(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        FanChangeDot(e);
    }
}

void ui_event_System_Tabpage_DebugArduino(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        OnDebugArduino(e);
    }
}

void ui_event_System_Textarea_TextAreaArduino(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnDebugArduino(e);
    }
}

void ui_event_System_Tabpage_DebugESP32(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        OnDebugESP32(e);
    }
}

void ui_event_System_Textarea_TextAreaESP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnDebugESP32(e);
    }
}

void ui_event_System_Tabpage_DebugScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        OnDebugScreen(e);
    }
}

void ui_event_System_Textarea_TextAreaScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnDebugScreen(e);
    }
}

void ui_event_System_Label_Label1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ToHomeClick(e);
        _ui_screen_change(&ui_Screen_DashBoard, LV_SCR_LOAD_ANIM_FADE_OUT, 100, 100, &ui_Screen_DashBoard_screen_init);
    }
}

// build funtions

void ui_Screen_System_screen_init(void)
{
    ui_Screen_System = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_System, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_System, lv_color_hex(0x000032), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_System, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen_System, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen_System, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Tabview_SystemTabView = lv_tabview_create(ui_Screen_System);
    lv_tabview_set_tab_bar_position(ui_System_Tabview_SystemTabView, LV_DIR_BOTTOM);
    lv_tabview_set_tab_bar_size(ui_System_Tabview_SystemTabView, 30);
    lv_obj_set_width(ui_System_Tabview_SystemTabView, 1024);
    lv_obj_set_height(ui_System_Tabview_SystemTabView, 600);
    lv_obj_remove_flag(ui_System_Tabview_SystemTabView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_System_Tabview_SystemTabView, &ui_img_global_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_System_Tabview_SystemTabView), lv_color_hex(0x808080),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_System_Tabview_SystemTabView), 255,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_bar(ui_System_Tabview_SystemTabView), &ui_font_BaseFont20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(lv_tabview_get_tab_bar(ui_System_Tabview_SystemTabView), 30,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_bar(ui_System_Tabview_SystemTabView), lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_bar(ui_System_Tabview_SystemTabView), 200,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_tabview_get_tab_bar(ui_System_Tabview_SystemTabView), &ui_font_BaseFont16,
                               LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_System_Tabpage_Refuel = lv_tabview_add_tab(ui_System_Tabview_SystemTabView, "Заправка");

    ui_System_Bar_FuelTank = lv_bar_create(ui_System_Tabpage_Refuel);
    lv_bar_set_mode(ui_System_Bar_FuelTank, LV_BAR_MODE_RANGE);
    lv_bar_set_range(ui_System_Bar_FuelTank, 0, 55);
    lv_bar_set_value(ui_System_Bar_FuelTank, 55, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_System_Bar_FuelTank, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_System_Bar_FuelTank, 150);
    lv_obj_set_height(ui_System_Bar_FuelTank, 498);
    lv_obj_set_x(ui_System_Bar_FuelTank, -400);
    lv_obj_set_y(ui_System_Bar_FuelTank, 25);
    lv_obj_set_align(ui_System_Bar_FuelTank, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_System_Bar_FuelTank,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    lv_obj_set_style_radius(ui_System_Bar_FuelTank, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_System_Bar_FuelTank, lv_color_hex(0x0000FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Bar_FuelTank, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_System_Bar_FuelTank,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_System_Bar_FuelTank, lv_obj_get_style_pad_right(ui_System_Bar_FuelTank,
                                                                                  LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_System_Label_Zapravleno = lv_label_create(ui_System_Tabpage_Refuel);
    lv_obj_set_width(ui_System_Label_Zapravleno, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_System_Label_Zapravleno, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_System_Label_Zapravleno, -216);
    lv_obj_set_y(ui_System_Label_Zapravleno, -175);
    lv_obj_set_align(ui_System_Label_Zapravleno, LV_ALIGN_CENTER);
    lv_label_set_text(ui_System_Label_Zapravleno, "Заправлено:");
    lv_obj_set_style_text_color(ui_System_Label_Zapravleno, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_Zapravleno, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_Zapravleno, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Textarea_TAPrise = lv_textarea_create(ui_System_Tabpage_Refuel);
    lv_obj_set_width(ui_System_Textarea_TAPrise, 160);
    lv_obj_set_height(ui_System_Textarea_TAPrise, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_System_Textarea_TAPrise, 400);
    lv_obj_set_y(ui_System_Textarea_TAPrise, -171);
    lv_obj_set_align(ui_System_Textarea_TAPrise, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_System_Textarea_TAPrise, "1234567890,.");
    lv_textarea_set_max_length(ui_System_Textarea_TAPrise, 5);
    lv_textarea_set_placeholder_text(ui_System_Textarea_TAPrise, "63,87");
    lv_textarea_set_one_line(ui_System_Textarea_TAPrise, true);
    lv_obj_set_style_text_color(ui_System_Textarea_TAPrise, lv_color_hex(0x00FF1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Textarea_TAPrise, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_System_Textarea_TAPrise, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Textarea_TAPrise, &ui_font_LedSymbol, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_System_Textarea_TAPrise, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Textarea_TAPrise, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_LitrPrise = lv_label_create(ui_System_Tabpage_Refuel);
    lv_obj_set_width(ui_System_Label_LitrPrise, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_System_Label_LitrPrise, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_System_Label_LitrPrise, 220);
    lv_obj_set_y(ui_System_Label_LitrPrise, -175);
    lv_obj_set_align(ui_System_Label_LitrPrise, LV_ALIGN_CENTER);
    lv_label_set_text(ui_System_Label_LitrPrise, "Цена за литр:");
    lv_obj_set_style_text_color(ui_System_Label_LitrPrise, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_LitrPrise, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_LitrPrise, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_Label4 = lv_label_create(ui_System_Tabpage_Refuel);
    lv_obj_set_width(ui_System_Label_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_System_Label_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_System_Label_Label4, -160);
    lv_obj_set_y(ui_System_Label_Label4, -90);
    lv_obj_set_align(ui_System_Label_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_System_Label_Label4, "Показания одометра:");
    lv_obj_set_style_text_color(ui_System_Label_Label4, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_Label4, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Textarea_TAODO = lv_textarea_create(ui_System_Tabpage_Refuel);
    lv_obj_set_width(ui_System_Textarea_TAODO, 236);
    lv_obj_set_height(ui_System_Textarea_TAODO, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_System_Textarea_TAODO, 120);
    lv_obj_set_y(ui_System_Textarea_TAODO, -90);
    lv_obj_set_align(ui_System_Textarea_TAODO, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_System_Textarea_TAODO, "1234567890,.");
    lv_textarea_set_max_length(ui_System_Textarea_TAODO, 7);
    lv_textarea_set_placeholder_text(ui_System_Textarea_TAODO, "1000000");
    lv_textarea_set_one_line(ui_System_Textarea_TAODO, true);
    lv_obj_set_style_text_color(ui_System_Textarea_TAODO, lv_color_hex(0x00FF1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Textarea_TAODO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_System_Textarea_TAODO, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Textarea_TAODO, &ui_font_LedSymbol, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_System_Textarea_TAODO, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Textarea_TAODO, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_Calibrate = lv_label_create(ui_System_Tabpage_Refuel);
    lv_obj_set_width(ui_System_Label_Calibrate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_System_Label_Calibrate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_System_Label_Calibrate, 330);
    lv_obj_set_y(ui_System_Label_Calibrate, -90);
    lv_obj_set_align(ui_System_Label_Calibrate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_System_Label_Calibrate, "Калибровка");
    lv_obj_set_style_text_color(ui_System_Label_Calibrate, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_Calibrate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_Calibrate, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Switch_SwitchFullTank = lv_switch_create(ui_System_Tabpage_Refuel);
    lv_obj_set_width(ui_System_Switch_SwitchFullTank, 60);
    lv_obj_set_height(ui_System_Switch_SwitchFullTank, 30);
    lv_obj_set_x(ui_System_Switch_SwitchFullTank, 449);
    lv_obj_set_y(ui_System_Switch_SwitchFullTank, -90);
    lv_obj_set_align(ui_System_Switch_SwitchFullTank, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_System_Switch_SwitchFullTank, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Switch_SwitchFullTank, 64, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_System_Switch_SwitchFullTank, lv_color_hex(0x00FF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Switch_SwitchFullTank, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_System_Textarea_TACurrentFuel = lv_textarea_create(ui_System_Tabpage_Refuel);
    lv_obj_set_width(ui_System_Textarea_TACurrentFuel, 130);
    lv_obj_set_height(ui_System_Textarea_TACurrentFuel, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_System_Textarea_TACurrentFuel, -400);
    lv_obj_set_y(ui_System_Textarea_TACurrentFuel, 0);
    lv_obj_set_align(ui_System_Textarea_TACurrentFuel, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_System_Textarea_TACurrentFuel, "1234567890,.");
    lv_textarea_set_max_length(ui_System_Textarea_TACurrentFuel, 4);
    lv_textarea_set_placeholder_text(ui_System_Textarea_TACurrentFuel, "20,0");
    lv_textarea_set_one_line(ui_System_Textarea_TACurrentFuel, true);
    lv_obj_set_style_text_color(ui_System_Textarea_TACurrentFuel, lv_color_hex(0x00FF1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Textarea_TACurrentFuel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_System_Textarea_TACurrentFuel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Textarea_TACurrentFuel, &ui_font_LedSymbol, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_System_Textarea_TACurrentFuel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Textarea_TACurrentFuel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_SaveLBtn = lv_label_create(ui_System_Tabpage_Refuel);
    lv_obj_set_width(ui_System_Label_SaveLBtn, 200);
    lv_obj_set_height(ui_System_Label_SaveLBtn, 35);
    lv_obj_set_x(ui_System_Label_SaveLBtn, 70);
    lv_obj_set_y(ui_System_Label_SaveLBtn, 0);
    lv_obj_set_align(ui_System_Label_SaveLBtn, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_System_Label_SaveLBtn, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_System_Label_SaveLBtn, "Сохранить");
    lv_obj_add_flag(ui_System_Label_SaveLBtn, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_System_Label_SaveLBtn, lv_color_hex(0x18187B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_SaveLBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_System_Label_SaveLBtn, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_System_Label_SaveLBtn, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_SaveLBtn, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_System_Label_SaveLBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_System_Label_SaveLBtn, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Label_SaveLBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Textarea_TAFuelToAdd = lv_textarea_create(ui_System_Tabpage_Refuel);
    lv_obj_set_width(ui_System_Textarea_TAFuelToAdd, 130);
    lv_obj_set_height(ui_System_Textarea_TAFuelToAdd, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_System_Textarea_TAFuelToAdd, -52);
    lv_obj_set_y(ui_System_Textarea_TAFuelToAdd, -171);
    lv_obj_set_align(ui_System_Textarea_TAFuelToAdd, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_System_Textarea_TAFuelToAdd, "1234567890,.");
    lv_textarea_set_max_length(ui_System_Textarea_TAFuelToAdd, 4);
    lv_textarea_set_placeholder_text(ui_System_Textarea_TAFuelToAdd, "20,0");
    lv_textarea_set_one_line(ui_System_Textarea_TAFuelToAdd, true);
    lv_obj_set_style_text_color(ui_System_Textarea_TAFuelToAdd, lv_color_hex(0x00FF1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Textarea_TAFuelToAdd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_System_Textarea_TAFuelToAdd, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Textarea_TAFuelToAdd, &ui_font_LedSymbol, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_System_Textarea_TAFuelToAdd, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Textarea_TAFuelToAdd, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Tabpage_Setting = lv_tabview_add_tab(ui_System_Tabview_SystemTabView, "Настройки");

    ui_System_Textarea_TimeTextArea = lv_textarea_create(ui_System_Tabpage_Setting);
    lv_obj_set_width(ui_System_Textarea_TimeTextArea, 153);
    lv_obj_set_height(ui_System_Textarea_TimeTextArea, 52);
    lv_obj_set_x(ui_System_Textarea_TimeTextArea, 250);
    lv_obj_set_y(ui_System_Textarea_TimeTextArea, 40);
    lv_textarea_set_max_length(ui_System_Textarea_TimeTextArea, 8);
    lv_textarea_set_placeholder_text(ui_System_Textarea_TimeTextArea, "00.00.00");
    lv_obj_set_style_text_align(ui_System_Textarea_TimeTextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Textarea_TimeTextArea, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_SaveLBtn2 = lv_label_create(ui_System_Tabpage_Setting);
    lv_obj_set_width(ui_System_Label_SaveLBtn2, 900);
    lv_obj_set_height(ui_System_Label_SaveLBtn2, 35);
    lv_obj_set_x(ui_System_Label_SaveLBtn2, 3);
    lv_obj_set_y(ui_System_Label_SaveLBtn2, 0);
    lv_obj_set_align(ui_System_Label_SaveLBtn2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_long_mode(ui_System_Label_SaveLBtn2, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_System_Label_SaveLBtn2, "Сохранить");
    lv_obj_add_flag(ui_System_Label_SaveLBtn2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_System_Label_SaveLBtn2, lv_color_hex(0x18187B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_SaveLBtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_System_Label_SaveLBtn2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_System_Label_SaveLBtn2, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_SaveLBtn2, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_System_Label_SaveLBtn2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_System_Label_SaveLBtn2, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Label_SaveLBtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_TimeLbl = lv_label_create(ui_System_Tabpage_Setting);
    lv_obj_set_width(ui_System_Label_TimeLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_System_Label_TimeLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_System_Label_TimeLbl, 20);
    lv_obj_set_y(ui_System_Label_TimeLbl, 50);
    lv_label_set_text(ui_System_Label_TimeLbl, "Текущее время:");
    lv_obj_set_style_text_color(ui_System_Label_TimeLbl, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_TimeLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_TimeLbl, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_TimeLBtn = lv_label_create(ui_System_Tabpage_Setting);
    lv_obj_set_width(ui_System_Label_TimeLBtn, 235);
    lv_obj_set_height(ui_System_Label_TimeLBtn, 35);
    lv_obj_set_x(ui_System_Label_TimeLBtn, 450);
    lv_obj_set_y(ui_System_Label_TimeLBtn, 50);
    lv_label_set_long_mode(ui_System_Label_TimeLBtn, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_System_Label_TimeLBtn, "Применить");
    lv_obj_add_flag(ui_System_Label_TimeLBtn, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_System_Label_TimeLBtn, lv_color_hex(0x18187B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_TimeLBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_System_Label_TimeLBtn, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_System_Label_TimeLBtn, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_TimeLBtn, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_System_Label_TimeLBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_System_Label_TimeLBtn, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Label_TimeLBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_TimeLBtnR = lv_label_create(ui_System_Tabpage_Setting);
    lv_obj_set_width(ui_System_Label_TimeLBtnR, 235);
    lv_obj_set_height(ui_System_Label_TimeLBtnR, 35);
    lv_obj_set_x(ui_System_Label_TimeLBtnR, 700);
    lv_obj_set_y(ui_System_Label_TimeLBtnR, 50);
    lv_label_set_long_mode(ui_System_Label_TimeLBtnR, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_System_Label_TimeLBtnR, "Запросить");
    lv_obj_add_flag(ui_System_Label_TimeLBtnR, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_System_Label_TimeLBtnR, lv_color_hex(0x18187B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_TimeLBtnR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_System_Label_TimeLBtnR, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_System_Label_TimeLBtnR, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_TimeLBtnR, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_System_Label_TimeLBtnR, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_System_Label_TimeLBtnR, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Label_TimeLBtnR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_LightLbl = lv_label_create(ui_System_Tabpage_Setting);
    lv_obj_set_width(ui_System_Label_LightLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_System_Label_LightLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_System_Label_LightLbl, 20);
    lv_obj_set_y(ui_System_Label_LightLbl, 100);
    lv_label_set_text(ui_System_Label_LightLbl, "Яркость: 222");
    lv_obj_set_style_text_color(ui_System_Label_LightLbl, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_LightLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_LightLbl, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_LightMarkLbl = lv_label_create(ui_System_Tabpage_Setting);
    lv_obj_set_width(ui_System_Label_LightMarkLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_System_Label_LightMarkLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_System_Label_LightMarkLbl, 20);
    lv_obj_set_y(ui_System_Label_LightMarkLbl, 150);
    lv_label_set_text(ui_System_Label_LightMarkLbl, "Светло: 245");
    lv_obj_set_style_text_color(ui_System_Label_LightMarkLbl, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_LightMarkLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_LightMarkLbl, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_DarkMarkLbl = lv_label_create(ui_System_Tabpage_Setting);
    lv_obj_set_width(ui_System_Label_DarkMarkLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_System_Label_DarkMarkLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_System_Label_DarkMarkLbl, 500);
    lv_obj_set_y(ui_System_Label_DarkMarkLbl, 150);
    lv_label_set_text(ui_System_Label_DarkMarkLbl, "Темно: 025");
    lv_obj_set_style_text_color(ui_System_Label_DarkMarkLbl, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_DarkMarkLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_DarkMarkLbl, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Slider_SliderLight = lv_slider_create(ui_System_Tabpage_Setting);
    lv_slider_set_range(ui_System_Slider_SliderLight, 0, 4095);
    lv_slider_set_value(ui_System_Slider_SliderLight, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_System_Slider_SliderLight) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_System_Slider_SliderLight, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_System_Slider_SliderLight, 242);
    lv_obj_set_height(ui_System_Slider_SliderLight, 25);
    lv_obj_set_x(ui_System_Slider_SliderLight, -147);
    lv_obj_set_y(ui_System_Slider_SliderLight, -101);
    lv_obj_set_align(ui_System_Slider_SliderLight, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_System_Slider_SliderLight,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_System_Slider_SliderLight,
                                                                                  lv_obj_get_style_pad_right(ui_System_Slider_SliderLight, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_System_Slider_SliderDark = lv_slider_create(ui_System_Tabpage_Setting);
    lv_slider_set_range(ui_System_Slider_SliderDark, 0, 4095);
    lv_slider_set_value(ui_System_Slider_SliderDark, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_System_Slider_SliderDark) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_System_Slider_SliderDark, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_System_Slider_SliderDark, 260);
    lv_obj_set_height(ui_System_Slider_SliderDark, 25);
    lv_obj_set_x(ui_System_Slider_SliderDark, 318);
    lv_obj_set_y(ui_System_Slider_SliderDark, -99);
    lv_obj_set_align(ui_System_Slider_SliderDark, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_System_Slider_SliderDark,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_System_Slider_SliderDark,
                                                                                  lv_obj_get_style_pad_right(ui_System_Slider_SliderDark, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_System_Label_CurrentLight = lv_label_create(ui_System_Tabpage_Setting);
    lv_obj_set_width(ui_System_Label_CurrentLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_System_Label_CurrentLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_System_Label_CurrentLight, 613);
    lv_obj_set_y(ui_System_Label_CurrentLight, 102);
    lv_label_set_text(ui_System_Label_CurrentLight, "Текущее значение: 000");
    lv_obj_set_style_text_color(ui_System_Label_CurrentLight, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_CurrentLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_CurrentLight, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Slider_SliderBridges = lv_slider_create(ui_System_Tabpage_Setting);
    lv_slider_set_value(ui_System_Slider_SliderBridges, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_System_Slider_SliderBridges) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_System_Slider_SliderBridges, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_System_Slider_SliderBridges, 366);
    lv_obj_set_height(ui_System_Slider_SliderBridges, 25);
    lv_obj_set_x(ui_System_Slider_SliderBridges, -79);
    lv_obj_set_y(ui_System_Slider_SliderBridges, -145);
    lv_obj_set_align(ui_System_Slider_SliderBridges, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_System_Slider_SliderBridges,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_System_Slider_SliderBridges,
                                                                                  lv_obj_get_style_pad_right(ui_System_Slider_SliderBridges, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_System_Label_CalibrateMCU = lv_label_create(ui_System_Tabpage_Setting);
    lv_obj_set_width(ui_System_Label_CalibrateMCU, 900);
    lv_obj_set_height(ui_System_Label_CalibrateMCU, 35);
    lv_obj_set_x(ui_System_Label_CalibrateMCU, 3);
    lv_obj_set_y(ui_System_Label_CalibrateMCU, -60);
    lv_obj_set_align(ui_System_Label_CalibrateMCU, LV_ALIGN_BOTTOM_MID);
    lv_label_set_long_mode(ui_System_Label_CalibrateMCU, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_System_Label_CalibrateMCU, "Калибровать аксклерометр");
    lv_obj_add_flag(ui_System_Label_CalibrateMCU, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_System_Label_CalibrateMCU, lv_color_hex(0x18187B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_CalibrateMCU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_System_Label_CalibrateMCU, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_System_Label_CalibrateMCU, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_CalibrateMCU, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_System_Label_CalibrateMCU, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_System_Label_CalibrateMCU, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Label_CalibrateMCU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_FanPlus = lv_label_create(ui_System_Tabpage_Setting);
    lv_obj_set_width(ui_System_Label_FanPlus, LV_SIZE_CONTENT);   /// 235
    lv_obj_set_height(ui_System_Label_FanPlus, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_System_Label_FanPlus, 416);
    lv_obj_set_y(ui_System_Label_FanPlus, 208);
    lv_label_set_long_mode(ui_System_Label_FanPlus, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_System_Label_FanPlus, ">>>");
    lv_obj_add_flag(ui_System_Label_FanPlus, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_System_Label_FanPlus, lv_color_hex(0x18187B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_FanPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_System_Label_FanPlus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_System_Label_FanPlus, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_FanPlus, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_System_Label_FanPlus, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_System_Label_FanPlus, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Label_FanPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_FanMinus = lv_label_create(ui_System_Tabpage_Setting);
    lv_obj_set_width(ui_System_Label_FanMinus, LV_SIZE_CONTENT);   /// 235
    lv_obj_set_height(ui_System_Label_FanMinus, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_System_Label_FanMinus, 274);
    lv_obj_set_y(ui_System_Label_FanMinus, 208);
    lv_label_set_long_mode(ui_System_Label_FanMinus, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_System_Label_FanMinus, "<<<");
    lv_obj_add_flag(ui_System_Label_FanMinus, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_System_Label_FanMinus, lv_color_hex(0x18187B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_FanMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_System_Label_FanMinus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_System_Label_FanMinus, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_FanMinus, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_System_Label_FanMinus, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_System_Label_FanMinus, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Label_FanMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_FanApply = lv_label_create(ui_System_Tabpage_Setting);
    lv_obj_set_width(ui_System_Label_FanApply, LV_SIZE_CONTENT);   /// 235
    lv_obj_set_height(ui_System_Label_FanApply, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_System_Label_FanApply, 488);
    lv_obj_set_y(ui_System_Label_FanApply, 208);
    lv_label_set_long_mode(ui_System_Label_FanApply, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_System_Label_FanApply, "Применить/сохранить");
    lv_obj_add_flag(ui_System_Label_FanApply, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_System_Label_FanApply, lv_color_hex(0x18187B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_FanApply, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_System_Label_FanApply, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_System_Label_FanApply, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_FanApply, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_System_Label_FanApply, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_System_Label_FanApply, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Label_FanApply, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_FanSaved = lv_label_create(ui_System_Tabpage_Setting);
    lv_obj_set_width(ui_System_Label_FanSaved, LV_SIZE_CONTENT);   /// 235
    lv_obj_set_height(ui_System_Label_FanSaved, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_System_Label_FanSaved, 820);
    lv_obj_set_y(ui_System_Label_FanSaved, 208);
    lv_label_set_long_mode(ui_System_Label_FanSaved, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_System_Label_FanSaved, "Сохранено");
    lv_obj_add_flag(ui_System_Label_FanSaved, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_System_Label_FanSaved,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_System_Label_FanSaved, lv_color_hex(0x18187B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_FanSaved, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_System_Label_FanSaved, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_System_Label_FanSaved, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_FanSaved, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_System_Label_FanSaved, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_System_Label_FanSaved, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Label_FanSaved, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_FanCalibLbl = lv_label_create(ui_System_Tabpage_Setting);
    lv_obj_set_width(ui_System_Label_FanCalibLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_System_Label_FanCalibLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_System_Label_FanCalibLbl, 342);
    lv_obj_set_y(ui_System_Label_FanCalibLbl, 208);
    lv_label_set_text(ui_System_Label_FanCalibLbl, "128");
    lv_obj_set_style_text_color(ui_System_Label_FanCalibLbl, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_FanCalibLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_FanCalibLbl, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Dropdown_DropdownFanDot = lv_dropdown_create(ui_System_Tabpage_Setting);
    lv_dropdown_set_options(ui_System_Dropdown_DropdownFanDot,
                            "В1-Точка старта\nВ1-Точка остановки\nВ1-Точка ВЧ\nВ1-Точка аэродинамики\nВ2-Точка старта\nВ2-Точка остановки\nВ2-Точка ВЧ\nВ2-Точка аэродинамики\nВП-Точка старта\nВП-Точка остановки\nВП-Точка ВЧ\nВП-Точка аэродинамики");
    lv_obj_set_width(ui_System_Dropdown_DropdownFanDot, 238);
    lv_obj_set_height(ui_System_Dropdown_DropdownFanDot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_System_Dropdown_DropdownFanDot, 20);
    lv_obj_set_y(ui_System_Dropdown_DropdownFanDot, 200);
    lv_obj_add_flag(ui_System_Dropdown_DropdownFanDot, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_System_Dropdown_DropdownFanDot, &ui_font_BaseFont20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_System_Dropdown_DropdownFanDot, &lv_font_montserrat_14,
                               LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_System_Dropdown_DropdownFanDot), &ui_font_BaseFont20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_System_Dropdown_DropdownFanDot), &ui_font_BaseFont20,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_System_Tabpage_DebugArduino = lv_tabview_add_tab(ui_System_Tabview_SystemTabView, "Ардуино");

    ui_System_Textarea_TextAreaArduino = lv_textarea_create(ui_System_Tabpage_DebugArduino);
    lv_obj_set_width(ui_System_Textarea_TextAreaArduino, 955);
    lv_obj_set_height(ui_System_Textarea_TextAreaArduino, 495);
    lv_obj_set_x(ui_System_Textarea_TextAreaArduino, 13);
    lv_obj_set_y(ui_System_Textarea_TextAreaArduino, 45);
    lv_textarea_set_text(ui_System_Textarea_TextAreaArduino, "Данные с Ардуино");
    lv_textarea_set_placeholder_text(ui_System_Textarea_TextAreaArduino, "Placeholder...");
    lv_obj_add_flag(ui_System_Textarea_TextAreaArduino,
                    LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW);    /// Flags
    lv_obj_remove_flag(ui_System_Textarea_TextAreaArduino,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_System_Textarea_TextAreaArduino, lv_color_hex(0x01C840),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Textarea_TextAreaArduino, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Textarea_TextAreaArduino, &ui_font_BaseFont16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_System_Textarea_TextAreaArduino, lv_color_hex(0x000810), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Textarea_TextAreaArduino, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Tabpage_DebugESP32 = lv_tabview_add_tab(ui_System_Tabview_SystemTabView, "ESP32");

    ui_System_Textarea_TextAreaESP = lv_textarea_create(ui_System_Tabpage_DebugESP32);
    lv_obj_set_width(ui_System_Textarea_TextAreaESP, 955);
    lv_obj_set_height(ui_System_Textarea_TextAreaESP, 495);
    lv_obj_set_x(ui_System_Textarea_TextAreaESP, 13);
    lv_obj_set_y(ui_System_Textarea_TextAreaESP, 45);
    lv_textarea_set_text(ui_System_Textarea_TextAreaESP, "Данные с ESP32");
    lv_textarea_set_placeholder_text(ui_System_Textarea_TextAreaESP, "Placeholder...");
    lv_obj_add_flag(ui_System_Textarea_TextAreaESP,
                    LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW);    /// Flags
    lv_obj_remove_flag(ui_System_Textarea_TextAreaESP, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_style_text_color(ui_System_Textarea_TextAreaESP, lv_color_hex(0x01C840), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Textarea_TextAreaESP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Textarea_TextAreaESP, &ui_font_BaseFont16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_System_Textarea_TextAreaESP, lv_color_hex(0x000810), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Textarea_TextAreaESP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Tabpage_DebugScreen = lv_tabview_add_tab(ui_System_Tabview_SystemTabView, "Экран");

    ui_System_Textarea_TextAreaScreen = lv_textarea_create(ui_System_Tabpage_DebugScreen);
    lv_obj_set_width(ui_System_Textarea_TextAreaScreen, 671);
    lv_obj_set_height(ui_System_Textarea_TextAreaScreen, 495);
    lv_obj_set_x(ui_System_Textarea_TextAreaScreen, 13);
    lv_obj_set_y(ui_System_Textarea_TextAreaScreen, 45);
    lv_textarea_set_text(ui_System_Textarea_TextAreaScreen, "Данные системы.\n");
    lv_textarea_set_placeholder_text(ui_System_Textarea_TextAreaScreen, "Placeholder...");
    lv_obj_remove_flag(ui_System_Textarea_TextAreaScreen,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_System_Textarea_TextAreaScreen, lv_color_hex(0x01C840), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Textarea_TextAreaScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Textarea_TextAreaScreen, &ui_font_BaseFont16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_System_Textarea_TextAreaScreen, lv_color_hex(0x000810), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Textarea_TextAreaScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Image_SDBack = lv_image_create(ui_System_Tabpage_DebugScreen);
    lv_image_set_src(ui_System_Image_SDBack, &ui_img_black_png);
    lv_obj_set_width(ui_System_Image_SDBack, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_System_Image_SDBack, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_System_Image_SDBack, 880);
    lv_obj_set_y(ui_System_Image_SDBack, -180);
    lv_obj_set_align(ui_System_Image_SDBack, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_System_Image_SDBack, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_System_Image_SDBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_System_Image_SDGrey = lv_image_create(ui_System_Tabpage_DebugScreen);
    lv_image_set_src(ui_System_Image_SDGrey, &ui_img_grey_png);
    lv_obj_set_width(ui_System_Image_SDGrey, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_System_Image_SDGrey, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_System_Image_SDGrey, 880);
    lv_obj_set_y(ui_System_Image_SDGrey, -180);
    lv_obj_set_align(ui_System_Image_SDGrey, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_System_Image_SDGrey, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_System_Image_SDGrey, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_System_Image_SDRed = lv_image_create(ui_System_Tabpage_DebugScreen);
    lv_image_set_src(ui_System_Image_SDRed, &ui_img_red_png);
    lv_obj_set_width(ui_System_Image_SDRed, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_System_Image_SDRed, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_System_Image_SDRed, 880);
    lv_obj_set_y(ui_System_Image_SDRed, -180);
    lv_obj_set_align(ui_System_Image_SDRed, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_System_Image_SDRed, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_System_Image_SDRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_System_Image_ArduinoBack = lv_image_create(ui_System_Tabpage_DebugScreen);
    lv_image_set_src(ui_System_Image_ArduinoBack, &ui_img_black_png);
    lv_obj_set_width(ui_System_Image_ArduinoBack, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_System_Image_ArduinoBack, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_System_Image_ArduinoBack, 880);
    lv_obj_set_y(ui_System_Image_ArduinoBack, -97);
    lv_obj_set_align(ui_System_Image_ArduinoBack, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_System_Image_ArduinoBack, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_System_Image_ArduinoBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_System_Image_ArduinoGrey = lv_image_create(ui_System_Tabpage_DebugScreen);
    lv_image_set_src(ui_System_Image_ArduinoGrey, &ui_img_grey_png);
    lv_obj_set_width(ui_System_Image_ArduinoGrey, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_System_Image_ArduinoGrey, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_System_Image_ArduinoGrey, 880);
    lv_obj_set_y(ui_System_Image_ArduinoGrey, -97);
    lv_obj_set_align(ui_System_Image_ArduinoGrey, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_System_Image_ArduinoGrey, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_System_Image_ArduinoGrey, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_System_Image_ArduinoRed = lv_image_create(ui_System_Tabpage_DebugScreen);
    lv_image_set_src(ui_System_Image_ArduinoRed, &ui_img_red_png);
    lv_obj_set_width(ui_System_Image_ArduinoRed, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_System_Image_ArduinoRed, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_System_Image_ArduinoRed, 880);
    lv_obj_set_y(ui_System_Image_ArduinoRed, -97);
    lv_obj_set_align(ui_System_Image_ArduinoRed, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_System_Image_ArduinoRed, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_System_Image_ArduinoRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_System_Image_ESP32Back = lv_image_create(ui_System_Tabpage_DebugScreen);
    lv_image_set_src(ui_System_Image_ESP32Back, &ui_img_black_png);
    lv_obj_set_width(ui_System_Image_ESP32Back, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_System_Image_ESP32Back, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_System_Image_ESP32Back, 880);
    lv_obj_set_y(ui_System_Image_ESP32Back, -15);
    lv_obj_set_align(ui_System_Image_ESP32Back, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_System_Image_ESP32Back, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_System_Image_ESP32Back, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_System_Image_ESP32Grey = lv_image_create(ui_System_Tabpage_DebugScreen);
    lv_image_set_src(ui_System_Image_ESP32Grey, &ui_img_grey_png);
    lv_obj_set_width(ui_System_Image_ESP32Grey, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_System_Image_ESP32Grey, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_System_Image_ESP32Grey, 880);
    lv_obj_set_y(ui_System_Image_ESP32Grey, -15);
    lv_obj_set_align(ui_System_Image_ESP32Grey, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_System_Image_ESP32Grey, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_System_Image_ESP32Grey, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_System_Image_ESP32Red = lv_image_create(ui_System_Tabpage_DebugScreen);
    lv_image_set_src(ui_System_Image_ESP32Red, &ui_img_red_png);
    lv_obj_set_width(ui_System_Image_ESP32Red, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_System_Image_ESP32Red, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_System_Image_ESP32Red, 880);
    lv_obj_set_y(ui_System_Image_ESP32Red, -15);
    lv_obj_set_align(ui_System_Image_ESP32Red, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_System_Image_ESP32Red, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_System_Image_ESP32Red, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_System_Image_SpeachBack = lv_image_create(ui_System_Tabpage_DebugScreen);
    lv_image_set_src(ui_System_Image_SpeachBack, &ui_img_black_png);
    lv_obj_set_width(ui_System_Image_SpeachBack, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_System_Image_SpeachBack, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_System_Image_SpeachBack, 880);
    lv_obj_set_y(ui_System_Image_SpeachBack, 66);
    lv_obj_set_align(ui_System_Image_SpeachBack, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_System_Image_SpeachBack, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_System_Image_SpeachBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_System_Image_SpeachGrey = lv_image_create(ui_System_Tabpage_DebugScreen);
    lv_image_set_src(ui_System_Image_SpeachGrey, &ui_img_grey_png);
    lv_obj_set_width(ui_System_Image_SpeachGrey, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_System_Image_SpeachGrey, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_System_Image_SpeachGrey, 880);
    lv_obj_set_y(ui_System_Image_SpeachGrey, 66);
    lv_obj_set_align(ui_System_Image_SpeachGrey, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_System_Image_SpeachGrey, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_System_Image_SpeachGrey, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_System_Image_SpeachRed = lv_image_create(ui_System_Tabpage_DebugScreen);
    lv_image_set_src(ui_System_Image_SpeachRed, &ui_img_red_png);
    lv_obj_set_width(ui_System_Image_SpeachRed, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_System_Image_SpeachRed, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_System_Image_SpeachRed, 880);
    lv_obj_set_y(ui_System_Image_SpeachRed, 66);
    lv_obj_set_align(ui_System_Image_SpeachRed, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_System_Image_SpeachRed, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_System_Image_SpeachRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_System_Image_StatBack = lv_image_create(ui_System_Tabpage_DebugScreen);
    lv_image_set_src(ui_System_Image_StatBack, &ui_img_black_png);
    lv_obj_set_width(ui_System_Image_StatBack, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_System_Image_StatBack, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_System_Image_StatBack, 880);
    lv_obj_set_y(ui_System_Image_StatBack, 148);
    lv_obj_set_align(ui_System_Image_StatBack, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_System_Image_StatBack, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_System_Image_StatBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_System_Image_StatGrey = lv_image_create(ui_System_Tabpage_DebugScreen);
    lv_image_set_src(ui_System_Image_StatGrey, &ui_img_grey_png);
    lv_obj_set_width(ui_System_Image_StatGrey, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_System_Image_StatGrey, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_System_Image_StatGrey, 880);
    lv_obj_set_y(ui_System_Image_StatGrey, 148);
    lv_obj_set_align(ui_System_Image_StatGrey, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_System_Image_StatGrey, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_System_Image_StatGrey, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_System_Image_StatRed = lv_image_create(ui_System_Tabpage_DebugScreen);
    lv_image_set_src(ui_System_Image_StatRed, &ui_img_red_png);
    lv_obj_set_width(ui_System_Image_StatRed, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_System_Image_StatRed, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_System_Image_StatRed, 880);
    lv_obj_set_y(ui_System_Image_StatRed, 148);
    lv_obj_set_align(ui_System_Image_StatRed, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_System_Image_StatRed, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_System_Image_StatRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_System_Image_PresetBack = lv_image_create(ui_System_Tabpage_DebugScreen);
    lv_image_set_src(ui_System_Image_PresetBack, &ui_img_black_png);
    lv_obj_set_width(ui_System_Image_PresetBack, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_System_Image_PresetBack, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_System_Image_PresetBack, 880);
    lv_obj_set_y(ui_System_Image_PresetBack, 230);
    lv_obj_set_align(ui_System_Image_PresetBack, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_System_Image_PresetBack, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_System_Image_PresetBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_System_Image_PresetGrey = lv_image_create(ui_System_Tabpage_DebugScreen);
    lv_image_set_src(ui_System_Image_PresetGrey, &ui_img_grey_png);
    lv_obj_set_width(ui_System_Image_PresetGrey, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_System_Image_PresetGrey, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_System_Image_PresetGrey, 880);
    lv_obj_set_y(ui_System_Image_PresetGrey, 230);
    lv_obj_set_align(ui_System_Image_PresetGrey, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_System_Image_PresetGrey, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_System_Image_PresetGrey, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_System_Image_PresetRed = lv_image_create(ui_System_Tabpage_DebugScreen);
    lv_image_set_src(ui_System_Image_PresetRed, &ui_img_red_png);
    lv_obj_set_width(ui_System_Image_PresetRed, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_System_Image_PresetRed, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_System_Image_PresetRed, 880);
    lv_obj_set_y(ui_System_Image_PresetRed, 230);
    lv_obj_set_align(ui_System_Image_PresetRed, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_System_Image_PresetRed, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_System_Image_PresetRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_System_Label_Label6 = lv_label_create(ui_System_Tabpage_DebugScreen);
    lv_obj_set_width(ui_System_Label_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_System_Label_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_System_Label_Label6, 690);
    lv_obj_set_y(ui_System_Label_Label6, -183);
    lv_obj_set_align(ui_System_Label_Label6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_System_Label_Label6, "Карта памяти");
    lv_obj_remove_flag(ui_System_Label_Label6,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_System_Label_Label6, lv_color_hex(0x00CA41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_Label6, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_Label7 = lv_label_create(ui_System_Tabpage_DebugScreen);
    lv_obj_set_width(ui_System_Label_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_System_Label_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_System_Label_Label7, 690);
    lv_obj_set_y(ui_System_Label_Label7, -97);
    lv_obj_set_align(ui_System_Label_Label7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_System_Label_Label7, "Ардуино");
    lv_obj_remove_flag(ui_System_Label_Label7,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_System_Label_Label7, lv_color_hex(0x00CA41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_Label7, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_Label8 = lv_label_create(ui_System_Tabpage_DebugScreen);
    lv_obj_set_width(ui_System_Label_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_System_Label_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_System_Label_Label8, 690);
    lv_obj_set_y(ui_System_Label_Label8, -15);
    lv_obj_set_align(ui_System_Label_Label8, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_System_Label_Label8, "ESP32");
    lv_obj_remove_flag(ui_System_Label_Label8,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_System_Label_Label8, lv_color_hex(0x00CA41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_Label8, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_Label9 = lv_label_create(ui_System_Tabpage_DebugScreen);
    lv_obj_set_width(ui_System_Label_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_System_Label_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_System_Label_Label9, 690);
    lv_obj_set_y(ui_System_Label_Label9, 67);
    lv_obj_set_align(ui_System_Label_Label9, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_System_Label_Label9, "Реплики");
    lv_obj_remove_flag(ui_System_Label_Label9,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_System_Label_Label9, lv_color_hex(0x00CA41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_Label9, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_Label10 = lv_label_create(ui_System_Tabpage_DebugScreen);
    lv_obj_set_width(ui_System_Label_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_System_Label_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_System_Label_Label10, 690);
    lv_obj_set_y(ui_System_Label_Label10, 149);
    lv_obj_set_align(ui_System_Label_Label10, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_System_Label_Label10, "Статистика");
    lv_obj_remove_flag(ui_System_Label_Label10,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_System_Label_Label10, lv_color_hex(0x00CA41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_Label10, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_Label11 = lv_label_create(ui_System_Tabpage_DebugScreen);
    lv_obj_set_width(ui_System_Label_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_System_Label_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_System_Label_Label11, 690);
    lv_obj_set_y(ui_System_Label_Label11, 233);
    lv_obj_set_align(ui_System_Label_Label11, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_System_Label_Label11, "Пресеты");
    lv_obj_remove_flag(ui_System_Label_Label11,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_System_Label_Label11, lv_color_hex(0x00CA41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_Label11, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Label_Label1 = lv_label_create(ui_Screen_System);
    lv_obj_set_width(ui_System_Label_Label1, 400);
    lv_obj_set_height(ui_System_Label_Label1, 30);
    lv_obj_set_x(ui_System_Label_Label1, 0);
    lv_obj_set_y(ui_System_Label_Label1, 10);
    lv_obj_set_align(ui_System_Label_Label1, LV_ALIGN_TOP_MID);
    lv_obj_set_ext_click_area(ui_System_Label_Label1, 20);
    lv_label_set_long_mode(ui_System_Label_Label1, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_System_Label_Label1, "Домой...");
    lv_obj_add_flag(ui_System_Label_Label1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_System_Label_Label1,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_System_Label_Label1, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Label_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_System_Label_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_System_Label_Label1, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Label_Label1, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_System_Keyboard_KeyboardForTab = lv_keyboard_create(ui_Screen_System);
    lv_keyboard_set_mode(ui_System_Keyboard_KeyboardForTab, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_System_Keyboard_KeyboardForTab, 780);
    lv_obj_set_height(ui_System_Keyboard_KeyboardForTab, 226);
    lv_obj_set_x(ui_System_Keyboard_KeyboardForTab, 80);
    lv_obj_set_y(ui_System_Keyboard_KeyboardForTab, 150);
    lv_obj_set_align(ui_System_Keyboard_KeyboardForTab, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_System_Keyboard_KeyboardForTab, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_System_Keyboard_KeyboardForTab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Keyboard_KeyboardForTab, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_System_Keyboard_KeyboardForTab, lv_color_hex(0x1C197A), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System_Keyboard_KeyboardForTab, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_System_Keyboard_KeyboardForTab, lv_color_hex(0x00D0FB),
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System_Keyboard_KeyboardForTab, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System_Keyboard_KeyboardForTab, &lv_font_montserrat_48, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_System_Textarea_TAPrise, ui_event_System_Textarea_TAPrise, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Textarea_TAODO, ui_event_System_Textarea_TAODO, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Switch_SwitchFullTank, ui_event_System_Switch_SwitchFullTank, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Textarea_TACurrentFuel, ui_event_System_Textarea_TACurrentFuel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Label_SaveLBtn, ui_event_System_Label_SaveLBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Textarea_TAFuelToAdd, ui_event_System_Textarea_TAFuelToAdd, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Tabpage_Refuel, ui_event_System_Tabpage_Refuel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Textarea_TimeTextArea, ui_event_System_Textarea_TimeTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Label_SaveLBtn2, ui_event_System_Label_SaveLBtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Label_TimeLBtn, ui_event_System_Label_TimeLBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Label_TimeLBtnR, ui_event_System_Label_TimeLBtnR, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Slider_SliderLight, ui_event_System_Slider_SliderLight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Slider_SliderDark, ui_event_System_Slider_SliderDark, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Slider_SliderBridges, ui_event_System_Slider_SliderBridges, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Label_CalibrateMCU, ui_event_System_Label_CalibrateMCU, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Label_FanPlus, ui_event_System_Label_FanPlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Label_FanMinus, ui_event_System_Label_FanMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Label_FanApply, ui_event_System_Label_FanApply, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Label_FanSaved, ui_event_System_Label_FanSaved, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Dropdown_DropdownFanDot, ui_event_System_Dropdown_DropdownFanDot, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Tabpage_Setting, ui_event_System_Tabpage_Setting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Textarea_TextAreaArduino, ui_event_System_Textarea_TextAreaArduino, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Tabpage_DebugArduino, ui_event_System_Tabpage_DebugArduino, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Textarea_TextAreaESP, ui_event_System_Textarea_TextAreaESP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Tabpage_DebugESP32, ui_event_System_Tabpage_DebugESP32, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Textarea_TextAreaScreen, ui_event_System_Textarea_TextAreaScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Tabpage_DebugScreen, ui_event_System_Tabpage_DebugScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_System_Label_Label1, ui_event_System_Label_Label1, LV_EVENT_ALL, NULL);

}

void ui_Screen_System_screen_destroy(void)
{
    if(ui_Screen_System) lv_obj_del(ui_Screen_System);

    // NULL screen variables
    ui_Screen_System = NULL;
    ui_System_Tabview_SystemTabView = NULL;
    ui_System_Tabpage_Refuel = NULL;
    ui_System_Bar_FuelTank = NULL;
    ui_System_Label_Zapravleno = NULL;
    ui_System_Textarea_TAPrise = NULL;
    ui_System_Label_LitrPrise = NULL;
    ui_System_Label_Label4 = NULL;
    ui_System_Textarea_TAODO = NULL;
    ui_System_Label_Calibrate = NULL;
    ui_System_Switch_SwitchFullTank = NULL;
    ui_System_Textarea_TACurrentFuel = NULL;
    ui_System_Label_SaveLBtn = NULL;
    ui_System_Textarea_TAFuelToAdd = NULL;
    ui_System_Tabpage_Setting = NULL;
    ui_System_Textarea_TimeTextArea = NULL;
    ui_System_Label_SaveLBtn2 = NULL;
    ui_System_Label_TimeLbl = NULL;
    ui_System_Label_TimeLBtn = NULL;
    ui_System_Label_TimeLBtnR = NULL;
    ui_System_Label_LightLbl = NULL;
    ui_System_Label_LightMarkLbl = NULL;
    ui_System_Label_DarkMarkLbl = NULL;
    ui_System_Slider_SliderLight = NULL;
    ui_System_Slider_SliderDark = NULL;
    ui_System_Label_CurrentLight = NULL;
    ui_System_Slider_SliderBridges = NULL;
    ui_System_Label_CalibrateMCU = NULL;
    ui_System_Label_FanPlus = NULL;
    ui_System_Label_FanMinus = NULL;
    ui_System_Label_FanApply = NULL;
    ui_System_Label_FanSaved = NULL;
    ui_System_Label_FanCalibLbl = NULL;
    ui_System_Dropdown_DropdownFanDot = NULL;
    ui_System_Tabpage_DebugArduino = NULL;
    ui_System_Textarea_TextAreaArduino = NULL;
    ui_System_Tabpage_DebugESP32 = NULL;
    ui_System_Textarea_TextAreaESP = NULL;
    ui_System_Tabpage_DebugScreen = NULL;
    ui_System_Textarea_TextAreaScreen = NULL;
    ui_System_Image_SDBack = NULL;
    ui_System_Image_SDGrey = NULL;
    ui_System_Image_SDRed = NULL;
    ui_System_Image_ArduinoBack = NULL;
    ui_System_Image_ArduinoGrey = NULL;
    ui_System_Image_ArduinoRed = NULL;
    ui_System_Image_ESP32Back = NULL;
    ui_System_Image_ESP32Grey = NULL;
    ui_System_Image_ESP32Red = NULL;
    ui_System_Image_SpeachBack = NULL;
    ui_System_Image_SpeachGrey = NULL;
    ui_System_Image_SpeachRed = NULL;
    ui_System_Image_StatBack = NULL;
    ui_System_Image_StatGrey = NULL;
    ui_System_Image_StatRed = NULL;
    ui_System_Image_PresetBack = NULL;
    ui_System_Image_PresetGrey = NULL;
    ui_System_Image_PresetRed = NULL;
    ui_System_Label_Label6 = NULL;
    ui_System_Label_Label7 = NULL;
    ui_System_Label_Label8 = NULL;
    ui_System_Label_Label9 = NULL;
    ui_System_Label_Label10 = NULL;
    ui_System_Label_Label11 = NULL;
    ui_System_Label_Label1 = NULL;
    ui_System_Keyboard_KeyboardForTab = NULL;

}
