// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Fiona_Project

#ifndef UI_SCREEN_SETTING_H
#define UI_SCREEN_SETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Setting
extern void ui_Screen_Setting_screen_init(void);
extern void ui_Screen_Setting_screen_destroy(void);
extern lv_obj_t * ui_Screen_Setting;
extern void ui_event_Setting_Label_Label4(lv_event_t * e);
extern lv_obj_t * ui_Setting_Label_Label4;
extern lv_obj_t * ui_Setting_Label_TimeLbl;
extern void ui_event_Setting_Textarea_TimeTextArea(lv_event_t * e);
extern lv_obj_t * ui_Setting_Textarea_TimeTextArea;
extern void ui_event_Setting_Label_SaveBtn(lv_event_t * e);
extern lv_obj_t * ui_Setting_Label_SaveBtn;
extern void ui_event_Setting_Label_TimeApply(lv_event_t * e);
extern lv_obj_t * ui_Setting_Label_TimeApply;
extern void ui_event_Setting_Label_TimeAsk(lv_event_t * e);
extern lv_obj_t * ui_Setting_Label_TimeAsk;
extern lv_obj_t * ui_Setting_Label_LightLbl2;
extern lv_obj_t * ui_Setting_Label_LightMarkLbl2;
extern lv_obj_t * ui_Setting_Label_DarkMarkLbl2;
extern void ui_event_Setting_Slider_SliderLight(lv_event_t * e);
extern lv_obj_t * ui_Setting_Slider_SliderLight;
extern void ui_event_Setting_Slider_SliderDark(lv_event_t * e);
extern lv_obj_t * ui_Setting_Slider_SliderDark;
extern void ui_event_Setting_Slider_SliderBridges(lv_event_t * e);
extern lv_obj_t * ui_Setting_Slider_SliderBridges;
extern void ui_event_Setting_Label_CalibrateMCU(lv_event_t * e);
extern lv_obj_t * ui_Setting_Label_CalibrateMCU;
extern void ui_event_Setting_Label_FanPlus(lv_event_t * e);
extern lv_obj_t * ui_Setting_Label_FanPlus;
extern void ui_event_Setting_Label_FanMinus(lv_event_t * e);
extern lv_obj_t * ui_Setting_Label_FanMinus;
extern void ui_event_Setting_Label_FanApply(lv_event_t * e);
extern lv_obj_t * ui_Setting_Label_FanApply;
extern void ui_event_Setting_Label_FanDefault(lv_event_t * e);
extern lv_obj_t * ui_Setting_Label_FanDefault;
extern lv_obj_t * ui_Setting_Label_FanCalibLbl;
extern void ui_event_Setting_Dropdown_DropdownFanDot(lv_event_t * e);
extern lv_obj_t * ui_Setting_Dropdown_DropdownFanDot;
extern lv_obj_t * ui_Setting_Label_KalibLabel;
extern void ui_event_Setting_Dropdown_UartDevice(lv_event_t * e);
extern lv_obj_t * ui_Setting_Dropdown_UartDevice;
extern void ui_event_Setting_Dropdown_SpeedUart(lv_event_t * e);
extern lv_obj_t * ui_Setting_Dropdown_SpeedUart;
extern void ui_event_Setting_Dropdown_RXList(lv_event_t * e);
extern lv_obj_t * ui_Setting_Dropdown_RXList;
extern void ui_event_Setting_Dropdown_TXList(lv_event_t * e);
extern lv_obj_t * ui_Setting_Dropdown_TXList;
extern lv_obj_t * ui_Setting_Label_RXLabel;
extern lv_obj_t * ui_Setting_Label_TXLabel;
extern void ui_event_Setting_Textarea_TextAreaUartLog(lv_event_t * e);
extern lv_obj_t * ui_Setting_Textarea_TextAreaUartLog;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

