// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Fiona_Project

#include "../ui.h"

lv_obj_t * uic_DashBoard_Label_q;
lv_obj_t * ui_Screen_DashBoard = NULL;
lv_obj_t * ui_DashBoard_Label_FionaSpeachLabelDash = NULL;
lv_obj_t * ui_DashBoard_Label_TahoLBL = NULL;
lv_obj_t * ui_DashBoard_Arc_Taho = NULL;
lv_obj_t * ui_DashBoard_Image_BlueRing = NULL;
lv_obj_t * ui_DashBoard_Image_ImageSpeed = NULL;
lv_obj_t * ui_DashBoard_Bar_BatBar = NULL;
lv_obj_t * ui_DashBoard_Image_BatShape = NULL;
lv_obj_t * ui_DashBoard_Image_Batallert = NULL;
lv_obj_t * ui_DashBoard_Image_BatHL = NULL;
lv_obj_t * ui_DashBoard_Bar_FuelBar = NULL;
lv_obj_t * ui_DashBoard_Image_FuelShape = NULL;
lv_obj_t * ui_DashBoard_Image_FuelNorm = NULL;
lv_obj_t * ui_DashBoard_Image_FuelAllert = NULL;
lv_obj_t * ui_DashBoard_Bar_TempBar = NULL;
lv_obj_t * ui_DashBoard_Image_CoolShape = NULL;
lv_obj_t * ui_DashBoard_Image_CoolNorm = NULL;
lv_obj_t * ui_DashBoard_Image_CoolHigh = NULL;
lv_obj_t * ui_DashBoard_Arc_Drossel = NULL;
lv_obj_t * ui_DashBoard_Arc_Uskorenie = NULL;
lv_obj_t * ui_DashBoard_Label_GazBL = NULL;
lv_obj_t * ui_DashBoard_Label_AxelBL = NULL;
lv_obj_t * ui_DashBoard_Label_AKB = NULL;
lv_obj_t * ui_DashBoard_Label_FUEL = NULL;
lv_obj_t * ui_DashBoard_Label_ODO = NULL;
lv_obj_t * ui_DashBoard_Label_TempNum = NULL;
lv_obj_t * ui_DashBoard_Image_TripImg = NULL;
lv_obj_t * ui_DashBoard_Label_TripNum = NULL;
lv_obj_t * ui_DashBoard_Label_TripTime = NULL;
lv_obj_t * ui_DashBoard_Label_TripTimePause = NULL;
lv_obj_t * ui_DashBoard_Label_TripLitr = NULL;
lv_obj_t * ui_DashBoard_Label_Time = NULL;
lv_obj_t * ui_DashBoard_Bar_lph = NULL;
lv_obj_t * ui_DashBoard_Label_LPHnum = NULL;
lv_obj_t * ui_DashBoard_Label_ODOonFuel = NULL;
lv_obj_t * ui_DashBoard_Label_SpeedDigit = NULL;
lv_obj_t * ui_DashBoard_Image_FreeWind = NULL;
lv_obj_t * ui_DashBoard_Image_ConditionHot = NULL;
lv_obj_t * ui_DashBoard_Image_ConditionCold = NULL;
lv_obj_t * ui_DashBoard_Image_RFirstVent = NULL;
lv_obj_t * ui_DashBoard_Image_RFirstVentAlert = NULL;
lv_obj_t * ui_DashBoard_Image_RSecondVent = NULL;
lv_obj_t * ui_DashBoard_Image_RSecondVentAlert = NULL;
lv_obj_t * ui_DashBoard_Image_RSecondVentAlert1 = NULL;
lv_obj_t * ui_DashBoard_Container_CenterContainer = NULL;
lv_obj_t * ui_DashBoard_Container_TripContainer = NULL;
lv_obj_t * ui_DashBoard_Container_FuelContainer = NULL;
lv_obj_t * ui_DashBoard_Label_CondShim = NULL;
lv_obj_t * ui_DashBoard_Label_VFirstShim = NULL;
lv_obj_t * ui_DashBoard_Label_VSecondShim = NULL;
lv_obj_t * ui_DashBoard_Label_EditionString = NULL;
lv_obj_t * ui_DashBoard_Image_ImageCyan = NULL;
lv_obj_t * ui_DashBoard_Image_ImageGreen = NULL;
lv_obj_t * ui_DashBoard_Image_ImageYellow = NULL;
lv_obj_t * ui_DashBoard_Image_ImageRed = NULL;
lv_obj_t * ui_DashBoard_Container_ContainerRez = NULL;
lv_obj_t * ui_DashBoard_Image_WiFi = NULL;
lv_obj_t * ui_DashBoard_Image_GPS = NULL;
lv_obj_t * ui_DashBoard_Image_ServerOn = NULL;
lv_obj_t * ui_DashBoard_Container_ContainerClimate = NULL;
lv_obj_t * ui_DashBoard_Label_LabelCC = NULL;
lv_obj_t * ui_DashBoard_Label_Label13 = NULL;
lv_obj_t * ui_DashBoard_Label_Label14 = NULL;
lv_obj_t * ui_DashBoard_Label_Label15 = NULL;
lv_obj_t * ui_DashBoard_Switch_TempSwitch = NULL;
lv_obj_t * ui_DashBoard_Switch_AlignSwitch = NULL;
lv_obj_t * ui_DashBoard_Switch_FlpwSwitch = NULL;
lv_obj_t * ui_DashBoard_Slider_TempSlider = NULL;
lv_obj_t * ui_DashBoard_Label_Temperatura = NULL;
lv_obj_t * ui_DashBoard_Slider_AlignSlider = NULL;
lv_obj_t * ui_DashBoard_Slider_FlowSlider = NULL;
lv_obj_t * ui_DashBoard_Label_FlowShim = NULL;
lv_obj_t * ui_DashBoard_Container_AKBContainer = NULL;
lv_obj_t * ui_DashBoard_Container_DebugContainer = NULL;
// event funtions
void ui_event_Screen_DashBoard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        DashOnFocused(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        OnDefocused(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        DashboardOnLoad(e);
    }
}

void ui_event_DashBoard_Label_Time(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GetInternetTime(e);
    }
}

void ui_event_DashBoard_Container_CenterContainer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DashBoard_Container_ContainerClimate, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_DashBoard_Container_TripContainer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnTripClick(e);
    }
}

void ui_event_DashBoard_Container_FuelContainer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ToRefuelClk(e);
    }
}

void ui_event_DashBoard_Container_ContainerRez(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        RezChange(e);
    }
}

void ui_event_DashBoard_Label_LabelCC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ToHomeClick(e);
        _ui_flag_modify(ui_DashBoard_Container_ContainerClimate, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_DashBoard_Switch_TempSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        TempAutoChange(e);
    }
}

void ui_event_DashBoard_Switch_AlignSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        AlignAutoChange(e);
    }
}

void ui_event_DashBoard_Switch_FlpwSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        FlowAutoChange(e);
    }
}

void ui_event_DashBoard_Slider_TempSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        TempChanged(e);
    }
}

void ui_event_DashBoard_Slider_AlignSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        AlignChanged(e);
    }
}

void ui_event_DashBoard_Slider_FlowSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        FlowChanged(e);
    }
}

void ui_event_DashBoard_Container_AKBContainer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ToSettingClk(e);
    }
}

void ui_event_DashBoard_Container_DebugContainer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ToDebugClk(e);
    }
}

// build funtions

void ui_Screen_DashBoard_screen_init(void)
{
    ui_Screen_DashBoard = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_DashBoard,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Screen_DashBoard, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_image_src(ui_Screen_DashBoard, &ui_img_bg_red_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Label_FionaSpeachLabelDash = lv_label_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Label_FionaSpeachLabelDash, 1024);
    lv_obj_set_height(ui_DashBoard_Label_FionaSpeachLabelDash, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DashBoard_Label_FionaSpeachLabelDash, LV_ALIGN_BOTTOM_MID);
    lv_label_set_long_mode(ui_DashBoard_Label_FionaSpeachLabelDash, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_DashBoard_Label_FionaSpeachLabelDash, "Привет, Куда поедем?");
    lv_obj_set_style_text_color(ui_DashBoard_Label_FionaSpeachLabelDash, lv_color_hex(0xFFFF00),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_FionaSpeachLabelDash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DashBoard_Label_FionaSpeachLabelDash, LV_TEXT_ALIGN_AUTO,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_FionaSpeachLabelDash, &ui_font_BaseFont20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DashBoard_Label_FionaSpeachLabelDash, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Label_FionaSpeachLabelDash, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Label_TahoLBL = lv_label_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Label_TahoLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DashBoard_Label_TahoLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DashBoard_Label_TahoLBL, -30);
    lv_obj_set_y(ui_DashBoard_Label_TahoLBL, -181);
    lv_obj_set_align(ui_DashBoard_Label_TahoLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DashBoard_Label_TahoLBL, "1234");
    lv_obj_remove_flag(ui_DashBoard_Label_TahoLBL,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DashBoard_Label_TahoLBL, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_TahoLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_TahoLBL, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Arc_Taho = lv_arc_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Arc_Taho, 530);
    lv_obj_set_height(ui_DashBoard_Arc_Taho, 530);
    lv_obj_set_x(ui_DashBoard_Arc_Taho, 0);
    lv_obj_set_y(ui_DashBoard_Arc_Taho, -7);
    lv_obj_set_align(ui_DashBoard_Arc_Taho, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DashBoard_Arc_Taho,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_DashBoard_Arc_Taho, 0, 7000);
    lv_arc_set_value(ui_DashBoard_Arc_Taho, 4000);
    lv_arc_set_bg_angles(ui_DashBoard_Arc_Taho, 145, 35);
    lv_obj_set_style_arc_width(ui_DashBoard_Arc_Taho, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_DashBoard_Arc_Taho, 25, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_DashBoard_Arc_Taho, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Arc_Taho, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_DashBoard_Arc_Taho, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_DashBoard_Image_BlueRing = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_BlueRing, &ui_img_small_blue_png);
    lv_obj_set_width(ui_DashBoard_Image_BlueRing, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DashBoard_Image_BlueRing, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DashBoard_Image_BlueRing, -2);
    lv_obj_set_y(ui_DashBoard_Image_BlueRing, -1);
    lv_obj_set_align(ui_DashBoard_Image_BlueRing, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DashBoard_Image_BlueRing,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_DashBoard_Image_ImageSpeed = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_ImageSpeed, &ui_img_speed_png);
    lv_obj_set_width(ui_DashBoard_Image_ImageSpeed, LV_SIZE_CONTENT);   /// 283
    lv_obj_set_height(ui_DashBoard_Image_ImageSpeed, LV_SIZE_CONTENT);    /// 160
    lv_obj_set_x(ui_DashBoard_Image_ImageSpeed, 1);
    lv_obj_set_y(ui_DashBoard_Image_ImageSpeed, -106);
    lv_obj_set_align(ui_DashBoard_Image_ImageSpeed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DashBoard_Image_ImageSpeed, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Image_ImageSpeed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DashBoard_Bar_BatBar = lv_bar_create(ui_Screen_DashBoard);
    lv_bar_set_range(ui_DashBoard_Bar_BatBar, 0, 16);
    lv_bar_set_value(ui_DashBoard_Bar_BatBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_DashBoard_Bar_BatBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_DashBoard_Bar_BatBar, 145);
    lv_obj_set_height(ui_DashBoard_Bar_BatBar, 125);
    lv_obj_set_x(ui_DashBoard_Bar_BatBar, -358);
    lv_obj_set_y(ui_DashBoard_Bar_BatBar, 113);
    lv_obj_set_align(ui_DashBoard_Bar_BatBar, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DashBoard_Bar_BatBar,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_DashBoard_Bar_BatBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_DashBoard_Bar_BatBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DashBoard_Bar_BatBar, lv_color_hex(0x00C800), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Bar_BatBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_DashBoard_Bar_BatBar, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_DashBoard_Bar_BatBar,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_DashBoard_Bar_BatBar,
                                                                                  lv_obj_get_style_pad_right(ui_DashBoard_Bar_BatBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_DashBoard_Image_BatShape = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_BatShape, &ui_img_akb_png);
    lv_obj_set_width(ui_DashBoard_Image_BatShape, LV_SIZE_CONTENT);   /// 145
    lv_obj_set_height(ui_DashBoard_Image_BatShape, LV_SIZE_CONTENT);    /// 125
    lv_obj_set_x(ui_DashBoard_Image_BatShape, -358);
    lv_obj_set_y(ui_DashBoard_Image_BatShape, 113);
    lv_obj_set_align(ui_DashBoard_Image_BatShape, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DashBoard_Image_BatShape,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DashBoard_Image_Batallert = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_Batallert, &ui_img_battery_png);
    lv_obj_set_width(ui_DashBoard_Image_Batallert, LV_SIZE_CONTENT);   /// 47
    lv_obj_set_height(ui_DashBoard_Image_Batallert, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_DashBoard_Image_Batallert, -480);
    lv_obj_set_y(ui_DashBoard_Image_Batallert, 160);
    lv_obj_set_align(ui_DashBoard_Image_Batallert, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DashBoard_Image_Batallert,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DashBoard_Image_BatHL = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_BatHL, &ui_img_h_l_png);
    lv_obj_set_width(ui_DashBoard_Image_BatHL, LV_SIZE_CONTENT);   /// 37
    lv_obj_set_height(ui_DashBoard_Image_BatHL, LV_SIZE_CONTENT);    /// 126
    lv_obj_set_x(ui_DashBoard_Image_BatHL, -431);
    lv_obj_set_y(ui_DashBoard_Image_BatHL, 115);
    lv_obj_set_align(ui_DashBoard_Image_BatHL, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DashBoard_Image_BatHL,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DashBoard_Bar_FuelBar = lv_bar_create(ui_Screen_DashBoard);
    lv_bar_set_range(ui_DashBoard_Bar_FuelBar, 0, 55);
    lv_bar_set_value(ui_DashBoard_Bar_FuelBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_DashBoard_Bar_FuelBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_DashBoard_Bar_FuelBar, 145);
    lv_obj_set_height(ui_DashBoard_Bar_FuelBar, 125);
    lv_obj_set_x(ui_DashBoard_Bar_FuelBar, 357);
    lv_obj_set_y(ui_DashBoard_Bar_FuelBar, 113);
    lv_obj_set_align(ui_DashBoard_Bar_FuelBar, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DashBoard_Bar_FuelBar,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_DashBoard_Bar_FuelBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_DashBoard_Bar_FuelBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DashBoard_Bar_FuelBar, lv_color_hex(0x00C800), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Bar_FuelBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_DashBoard_Bar_FuelBar,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_DashBoard_Bar_FuelBar,
                                                                                  lv_obj_get_style_pad_right(ui_DashBoard_Bar_FuelBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_DashBoard_Image_FuelShape = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_FuelShape, &ui_img_fuel_png);
    lv_obj_set_width(ui_DashBoard_Image_FuelShape, LV_SIZE_CONTENT);   /// 145
    lv_obj_set_height(ui_DashBoard_Image_FuelShape, LV_SIZE_CONTENT);    /// 125
    lv_obj_set_x(ui_DashBoard_Image_FuelShape, 357);
    lv_obj_set_y(ui_DashBoard_Image_FuelShape, 113);
    lv_obj_set_align(ui_DashBoard_Image_FuelShape, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DashBoard_Image_FuelShape, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Image_FuelShape,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DashBoard_Image_FuelNorm = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_FuelNorm, &ui_img_ofe_png);
    lv_obj_set_width(ui_DashBoard_Image_FuelNorm, LV_SIZE_CONTENT);   /// 37
    lv_obj_set_height(ui_DashBoard_Image_FuelNorm, LV_SIZE_CONTENT);    /// 126
    lv_obj_set_x(ui_DashBoard_Image_FuelNorm, 431);
    lv_obj_set_y(ui_DashBoard_Image_FuelNorm, 114);
    lv_obj_set_align(ui_DashBoard_Image_FuelNorm, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DashBoard_Image_FuelNorm,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DashBoard_Image_FuelAllert = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_FuelAllert, &ui_img_oil_level_png);
    lv_obj_set_width(ui_DashBoard_Image_FuelAllert, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_DashBoard_Image_FuelAllert, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_DashBoard_Image_FuelAllert, 480);
    lv_obj_set_y(ui_DashBoard_Image_FuelAllert, 160);
    lv_obj_set_align(ui_DashBoard_Image_FuelAllert, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DashBoard_Image_FuelAllert, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Image_FuelAllert,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DashBoard_Bar_TempBar = lv_bar_create(ui_Screen_DashBoard);
    lv_bar_set_range(ui_DashBoard_Bar_TempBar, -40, 130);
    lv_bar_set_value(ui_DashBoard_Bar_TempBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_DashBoard_Bar_TempBar, -40, LV_ANIM_OFF);
    lv_obj_set_width(ui_DashBoard_Bar_TempBar, 45);
    lv_obj_set_height(ui_DashBoard_Bar_TempBar, 115);
    lv_obj_set_x(ui_DashBoard_Bar_TempBar, -334);
    lv_obj_set_y(ui_DashBoard_Bar_TempBar, -92);
    lv_obj_set_align(ui_DashBoard_Bar_TempBar, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DashBoard_Bar_TempBar,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_DashBoard_Bar_TempBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_DashBoard_Bar_TempBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_DashBoard_Bar_TempBar,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_DashBoard_Bar_TempBar,
                                                                                  lv_obj_get_style_pad_right(ui_DashBoard_Bar_TempBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_DashBoard_Image_CoolShape = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_CoolShape, &ui_img_twater_png);
    lv_obj_set_width(ui_DashBoard_Image_CoolShape, LV_SIZE_CONTENT);   /// 42
    lv_obj_set_height(ui_DashBoard_Image_CoolShape, LV_SIZE_CONTENT);    /// 115
    lv_obj_set_x(ui_DashBoard_Image_CoolShape, -334);
    lv_obj_set_y(ui_DashBoard_Image_CoolShape, -92);
    lv_obj_set_align(ui_DashBoard_Image_CoolShape, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DashBoard_Image_CoolShape,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DashBoard_Image_CoolNorm = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_CoolNorm, &ui_img_water_temp2_png);
    lv_obj_set_width(ui_DashBoard_Image_CoolNorm, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_DashBoard_Image_CoolNorm, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_DashBoard_Image_CoolNorm, -380);
    lv_obj_set_y(ui_DashBoard_Image_CoolNorm, -51);
    lv_obj_set_align(ui_DashBoard_Image_CoolNorm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DashBoard_Image_CoolNorm, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Image_CoolNorm,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DashBoard_Image_CoolHigh = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_CoolHigh, &ui_img_water_temp_png);
    lv_obj_set_width(ui_DashBoard_Image_CoolHigh, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_DashBoard_Image_CoolHigh, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_DashBoard_Image_CoolHigh, -380);
    lv_obj_set_y(ui_DashBoard_Image_CoolHigh, -51);
    lv_obj_set_align(ui_DashBoard_Image_CoolHigh, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DashBoard_Image_CoolHigh,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DashBoard_Arc_Drossel = lv_arc_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Arc_Drossel, 655);
    lv_obj_set_height(ui_DashBoard_Arc_Drossel, 655);
    lv_obj_set_x(ui_DashBoard_Arc_Drossel, 0);
    lv_obj_set_y(ui_DashBoard_Arc_Drossel, -7);
    lv_obj_set_align(ui_DashBoard_Arc_Drossel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DashBoard_Arc_Drossel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_DashBoard_Arc_Drossel, 0);
    lv_arc_set_bg_angles(ui_DashBoard_Arc_Drossel, 147, 183);
    lv_obj_set_style_arc_width(ui_DashBoard_Arc_Drossel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_DashBoard_Arc_Drossel, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_DashBoard_Arc_Drossel, 96, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_DashBoard_Arc_Drossel, 52, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_DashBoard_Arc_Drossel, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Arc_Drossel, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_DashBoard_Arc_Drossel, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_DashBoard_Arc_Uskorenie = lv_arc_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Arc_Uskorenie, 655);
    lv_obj_set_height(ui_DashBoard_Arc_Uskorenie, 655);
    lv_obj_set_x(ui_DashBoard_Arc_Uskorenie, 0);
    lv_obj_set_y(ui_DashBoard_Arc_Uskorenie, -7);
    lv_obj_set_align(ui_DashBoard_Arc_Uskorenie, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DashBoard_Arc_Uskorenie,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_DashBoard_Arc_Uskorenie, -300, 300);
    lv_arc_set_value(ui_DashBoard_Arc_Uskorenie, 300);
    lv_arc_set_bg_angles(ui_DashBoard_Arc_Uskorenie, 357, 37);
    lv_arc_set_mode(ui_DashBoard_Arc_Uskorenie, LV_ARC_MODE_SYMMETRICAL);
    lv_obj_set_style_arc_width(ui_DashBoard_Arc_Uskorenie, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_DashBoard_Arc_Uskorenie, lv_color_hex(0x40FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_DashBoard_Arc_Uskorenie, 96, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_DashBoard_Arc_Uskorenie, 52, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_DashBoard_Arc_Uskorenie, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Arc_Uskorenie, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_DashBoard_Arc_Uskorenie, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_DashBoard_Label_GazBL = lv_label_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Label_GazBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DashBoard_Label_GazBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DashBoard_Label_GazBL, -295);
    lv_obj_set_y(ui_DashBoard_Label_GazBL, -71);
    lv_obj_set_align(ui_DashBoard_Label_GazBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DashBoard_Label_GazBL, "100");
    lv_obj_remove_flag(ui_DashBoard_Label_GazBL,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DashBoard_Label_GazBL, lv_color_hex(0x2196F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_GazBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_GazBL, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Label_AxelBL = lv_label_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Label_AxelBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DashBoard_Label_AxelBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DashBoard_Label_AxelBL, 295);
    lv_obj_set_y(ui_DashBoard_Label_AxelBL, -71);
    lv_obj_set_align(ui_DashBoard_Label_AxelBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DashBoard_Label_AxelBL, "-9.0");
    lv_obj_remove_flag(ui_DashBoard_Label_AxelBL,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DashBoard_Label_AxelBL, lv_color_hex(0x2196F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_AxelBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_AxelBL, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Label_AKB = lv_label_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Label_AKB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DashBoard_Label_AKB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DashBoard_Label_AKB, -385);
    lv_obj_set_y(ui_DashBoard_Label_AKB, 35);
    lv_obj_set_align(ui_DashBoard_Label_AKB, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DashBoard_Label_AKB, "09.9v");
    lv_obj_remove_flag(ui_DashBoard_Label_AKB,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DashBoard_Label_AKB, lv_color_hex(0x2196F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_AKB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_DashBoard_Label_AKB, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_DashBoard_Label_AKB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_AKB, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Label_FUEL = lv_label_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Label_FUEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DashBoard_Label_FUEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DashBoard_Label_FUEL, 380);
    lv_obj_set_y(ui_DashBoard_Label_FUEL, 35);
    lv_obj_set_align(ui_DashBoard_Label_FUEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DashBoard_Label_FUEL, "50.0л");
    lv_obj_remove_flag(ui_DashBoard_Label_FUEL,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DashBoard_Label_FUEL, lv_color_hex(0x2196F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_FUEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_DashBoard_Label_FUEL, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_DashBoard_Label_FUEL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_FUEL, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Label_ODO = lv_label_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Label_ODO, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DashBoard_Label_ODO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DashBoard_Label_ODO, -380);
    lv_obj_set_y(ui_DashBoard_Label_ODO, 220);
    lv_obj_set_align(ui_DashBoard_Label_ODO, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DashBoard_Label_ODO, "123456789км");
    lv_obj_remove_flag(ui_DashBoard_Label_ODO,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DashBoard_Label_ODO, lv_color_hex(0x9EEFFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_ODO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_ODO, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Label_TempNum = lv_label_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Label_TempNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DashBoard_Label_TempNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DashBoard_Label_TempNum, -415);
    lv_obj_set_y(ui_DashBoard_Label_TempNum, -145);
    lv_obj_set_align(ui_DashBoard_Label_TempNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DashBoard_Label_TempNum, "t-000°С");
    lv_obj_remove_flag(ui_DashBoard_Label_TempNum,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DashBoard_Label_TempNum, lv_color_hex(0x2196F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_TempNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_TempNum, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Image_TripImg = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_TripImg, &ui_img_esp_png);
    lv_obj_set_width(ui_DashBoard_Image_TripImg, LV_SIZE_CONTENT);   /// 65
    lv_obj_set_height(ui_DashBoard_Image_TripImg, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_DashBoard_Image_TripImg, 340);
    lv_obj_set_y(ui_DashBoard_Image_TripImg, -130);
    lv_obj_set_align(ui_DashBoard_Image_TripImg, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DashBoard_Image_TripImg,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DashBoard_Label_TripNum = lv_label_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Label_TripNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DashBoard_Label_TripNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DashBoard_Label_TripNum, 440);
    lv_obj_set_y(ui_DashBoard_Label_TripNum, -145);
    lv_obj_set_align(ui_DashBoard_Label_TripNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DashBoard_Label_TripNum, "0000км");
    lv_obj_remove_flag(ui_DashBoard_Label_TripNum,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DashBoard_Label_TripNum, lv_color_hex(0x2196F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_TripNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_TripNum, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Label_TripTime = lv_label_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Label_TripTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DashBoard_Label_TripTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DashBoard_Label_TripTime, 438);
    lv_obj_set_y(ui_DashBoard_Label_TripTime, -110);
    lv_obj_set_align(ui_DashBoard_Label_TripTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DashBoard_Label_TripTime, "00:00:00");
    lv_obj_remove_flag(ui_DashBoard_Label_TripTime,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DashBoard_Label_TripTime, lv_color_hex(0x2196F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_TripTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_TripTime, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Label_TripTimePause = lv_label_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Label_TripTimePause, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DashBoard_Label_TripTimePause, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DashBoard_Label_TripTimePause, 438);
    lv_obj_set_y(ui_DashBoard_Label_TripTimePause, -75);
    lv_obj_set_align(ui_DashBoard_Label_TripTimePause, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DashBoard_Label_TripTimePause, "00:00:00");
    lv_obj_remove_flag(ui_DashBoard_Label_TripTimePause,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DashBoard_Label_TripTimePause, lv_color_hex(0x2196F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_TripTimePause, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_TripTimePause, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Label_TripLitr = lv_label_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Label_TripLitr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DashBoard_Label_TripLitr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DashBoard_Label_TripLitr, 440);
    lv_obj_set_y(ui_DashBoard_Label_TripLitr, -45);
    lv_obj_set_align(ui_DashBoard_Label_TripLitr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DashBoard_Label_TripLitr, "00л");
    lv_obj_remove_flag(ui_DashBoard_Label_TripLitr,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DashBoard_Label_TripLitr, lv_color_hex(0x2196F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_TripLitr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_TripLitr, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Label_Time = lv_label_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Label_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DashBoard_Label_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DashBoard_Label_Time, 400);
    lv_obj_set_y(ui_DashBoard_Label_Time, -250);
    lv_obj_set_align(ui_DashBoard_Label_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DashBoard_Label_Time, "00:00:00");
    lv_obj_add_flag(ui_DashBoard_Label_Time, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Label_Time, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_style_text_color(ui_DashBoard_Label_Time, lv_color_hex(0x9EEFFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_Time, &ui_font_LedSymbol, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Bar_lph = lv_bar_create(ui_Screen_DashBoard);
    lv_bar_set_range(ui_DashBoard_Bar_lph, 0, 25);
    lv_bar_set_value(ui_DashBoard_Bar_lph, 1, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_DashBoard_Bar_lph, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_DashBoard_Bar_lph, 250);
    lv_obj_set_height(ui_DashBoard_Bar_lph, 30);
    lv_obj_set_x(ui_DashBoard_Bar_lph, 1);
    lv_obj_set_y(ui_DashBoard_Bar_lph, 209);
    lv_obj_set_align(ui_DashBoard_Bar_lph, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DashBoard_Bar_lph,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_width(ui_DashBoard_Bar_lph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_DashBoard_Bar_lph, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Bar_lph, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DashBoard_Bar_lph, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_DashBoard_Bar_lph, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_DashBoard_Bar_lph,
                                                                                                        lv_obj_get_style_pad_right(ui_DashBoard_Bar_lph, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_DashBoard_Label_LPHnum = lv_label_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Label_LPHnum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DashBoard_Label_LPHnum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DashBoard_Label_LPHnum, 1);
    lv_obj_set_y(ui_DashBoard_Label_LPHnum, 250);
    lv_obj_set_align(ui_DashBoard_Label_LPHnum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DashBoard_Label_LPHnum, "28.8л/ч");
    lv_obj_remove_flag(ui_DashBoard_Label_LPHnum,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_DashBoard_Label_LPHnum, lv_color_hex(0x0A2CC9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_LPHnum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_LPHnum, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Label_ODOonFuel = lv_label_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Label_ODOonFuel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DashBoard_Label_ODOonFuel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DashBoard_Label_ODOonFuel, 330);
    lv_obj_set_y(ui_DashBoard_Label_ODOonFuel, 220);
    lv_obj_set_align(ui_DashBoard_Label_ODOonFuel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DashBoard_Label_ODOonFuel, "789км");
    lv_obj_remove_flag(ui_DashBoard_Label_ODOonFuel,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DashBoard_Label_ODOonFuel, lv_color_hex(0x3CE600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_ODOonFuel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_ODOonFuel, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Label_SpeedDigit = lv_label_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Label_SpeedDigit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DashBoard_Label_SpeedDigit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DashBoard_Label_SpeedDigit, 3);
    lv_obj_set_y(ui_DashBoard_Label_SpeedDigit, 2);
    lv_obj_set_align(ui_DashBoard_Label_SpeedDigit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DashBoard_Label_SpeedDigit, "000");
    lv_obj_remove_flag(ui_DashBoard_Label_SpeedDigit,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_DashBoard_Label_SpeedDigit, lv_color_hex(0x9EEFFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_SpeedDigit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_SpeedDigit, &ui_font_Digital, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Image_FreeWind = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_FreeWind, &ui_img_1173513873);
    lv_obj_set_width(ui_DashBoard_Image_FreeWind, LV_SIZE_CONTENT);   /// 152
    lv_obj_set_height(ui_DashBoard_Image_FreeWind, LV_SIZE_CONTENT);    /// 152
    lv_obj_set_x(ui_DashBoard_Image_FreeWind, -30);
    lv_obj_set_y(ui_DashBoard_Image_FreeWind, -30);
    lv_obj_add_flag(ui_DashBoard_Image_FreeWind, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Image_FreeWind,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_image_set_scale(ui_DashBoard_Image_FreeWind, 138);

    ui_DashBoard_Image_ConditionHot = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_ConditionHot, &ui_img_1279366634);
    lv_obj_set_width(ui_DashBoard_Image_ConditionHot, LV_SIZE_CONTENT);   /// 152
    lv_obj_set_height(ui_DashBoard_Image_ConditionHot, LV_SIZE_CONTENT);    /// 152
    lv_obj_set_x(ui_DashBoard_Image_ConditionHot, 40);
    lv_obj_set_y(ui_DashBoard_Image_ConditionHot, -30);
    lv_obj_add_flag(ui_DashBoard_Image_ConditionHot, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Image_ConditionHot,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_image_set_scale(ui_DashBoard_Image_ConditionHot, 138);

    ui_DashBoard_Image_ConditionCold = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_ConditionCold, &ui_img_1173515923);
    lv_obj_set_width(ui_DashBoard_Image_ConditionCold, LV_SIZE_CONTENT);   /// 152
    lv_obj_set_height(ui_DashBoard_Image_ConditionCold, LV_SIZE_CONTENT);    /// 152
    lv_obj_set_x(ui_DashBoard_Image_ConditionCold, 40);
    lv_obj_set_y(ui_DashBoard_Image_ConditionCold, -30);
    lv_obj_add_flag(ui_DashBoard_Image_ConditionCold, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Image_ConditionCold,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_image_set_scale(ui_DashBoard_Image_ConditionCold, 138);

    ui_DashBoard_Image_RFirstVent = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_RFirstVent, &ui_img_cooller2_png);
    lv_obj_set_width(ui_DashBoard_Image_RFirstVent, LV_SIZE_CONTENT);   /// 152
    lv_obj_set_height(ui_DashBoard_Image_RFirstVent, LV_SIZE_CONTENT);    /// 152
    lv_obj_set_x(ui_DashBoard_Image_RFirstVent, 120);
    lv_obj_set_y(ui_DashBoard_Image_RFirstVent, -30);
    lv_obj_add_flag(ui_DashBoard_Image_RFirstVent, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Image_RFirstVent,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_image_set_scale(ui_DashBoard_Image_RFirstVent, 138);

    ui_DashBoard_Image_RFirstVentAlert = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_RFirstVentAlert, &ui_img_cooller1a_png);
    lv_obj_set_width(ui_DashBoard_Image_RFirstVentAlert, LV_SIZE_CONTENT);   /// 152
    lv_obj_set_height(ui_DashBoard_Image_RFirstVentAlert, LV_SIZE_CONTENT);    /// 152
    lv_obj_set_x(ui_DashBoard_Image_RFirstVentAlert, 120);
    lv_obj_set_y(ui_DashBoard_Image_RFirstVentAlert, -30);
    lv_obj_add_flag(ui_DashBoard_Image_RFirstVentAlert, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Image_RFirstVentAlert,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_image_set_scale(ui_DashBoard_Image_RFirstVentAlert, 138);

    ui_DashBoard_Image_RSecondVent = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_RSecondVent, &ui_img_cooller1_png);
    lv_obj_set_width(ui_DashBoard_Image_RSecondVent, LV_SIZE_CONTENT);   /// 152
    lv_obj_set_height(ui_DashBoard_Image_RSecondVent, LV_SIZE_CONTENT);    /// 152
    lv_obj_set_x(ui_DashBoard_Image_RSecondVent, 200);
    lv_obj_set_y(ui_DashBoard_Image_RSecondVent, -30);
    lv_obj_add_flag(ui_DashBoard_Image_RSecondVent, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Image_RSecondVent,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_image_set_scale(ui_DashBoard_Image_RSecondVent, 138);

    ui_DashBoard_Image_RSecondVentAlert = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_RSecondVentAlert, &ui_img_cooller2a_png);
    lv_obj_set_width(ui_DashBoard_Image_RSecondVentAlert, LV_SIZE_CONTENT);   /// 152
    lv_obj_set_height(ui_DashBoard_Image_RSecondVentAlert, LV_SIZE_CONTENT);    /// 152
    lv_obj_set_x(ui_DashBoard_Image_RSecondVentAlert, 200);
    lv_obj_set_y(ui_DashBoard_Image_RSecondVentAlert, -30);
    lv_obj_add_flag(ui_DashBoard_Image_RSecondVentAlert, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Image_RSecondVentAlert,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_image_set_scale(ui_DashBoard_Image_RSecondVentAlert, 138);

    ui_DashBoard_Image_RSecondVentAlert1 = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_RSecondVentAlert1, &ui_img_cooller3_png);
    lv_obj_set_width(ui_DashBoard_Image_RSecondVentAlert1, LV_SIZE_CONTENT);   /// 152
    lv_obj_set_height(ui_DashBoard_Image_RSecondVentAlert1, LV_SIZE_CONTENT);    /// 152
    lv_obj_set_x(ui_DashBoard_Image_RSecondVentAlert1, 200);
    lv_obj_set_y(ui_DashBoard_Image_RSecondVentAlert1, -30);
    lv_obj_add_flag(ui_DashBoard_Image_RSecondVentAlert1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Image_RSecondVentAlert1,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_image_set_scale(ui_DashBoard_Image_RSecondVentAlert1, 138);

    ui_DashBoard_Container_CenterContainer = lv_obj_create(ui_Screen_DashBoard);
    lv_obj_remove_style_all(ui_DashBoard_Container_CenterContainer);
    lv_obj_set_width(ui_DashBoard_Container_CenterContainer, 570);
    lv_obj_set_height(ui_DashBoard_Container_CenterContainer, 600);
    lv_obj_set_x(ui_DashBoard_Container_CenterContainer, 1);
    lv_obj_set_y(ui_DashBoard_Container_CenterContainer, 0);
    lv_obj_set_align(ui_DashBoard_Container_CenterContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DashBoard_Container_CenterContainer, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Container_CenterContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DashBoard_Container_TripContainer = lv_obj_create(ui_Screen_DashBoard);
    lv_obj_remove_style_all(ui_DashBoard_Container_TripContainer);
    lv_obj_set_width(ui_DashBoard_Container_TripContainer, 164);
    lv_obj_set_height(ui_DashBoard_Container_TripContainer, 178);
    lv_obj_set_x(ui_DashBoard_Container_TripContainer, 426);
    lv_obj_set_y(ui_DashBoard_Container_TripContainer, -114);
    lv_obj_set_align(ui_DashBoard_Container_TripContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DashBoard_Container_TripContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DashBoard_Container_FuelContainer = lv_obj_create(ui_Screen_DashBoard);
    lv_obj_remove_style_all(ui_DashBoard_Container_FuelContainer);
    lv_obj_set_width(ui_DashBoard_Container_FuelContainer, 209);
    lv_obj_set_height(ui_DashBoard_Container_FuelContainer, 192);
    lv_obj_set_x(ui_DashBoard_Container_FuelContainer, 812);
    lv_obj_set_y(ui_DashBoard_Container_FuelContainer, 308);
    lv_obj_add_flag(ui_DashBoard_Container_FuelContainer, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Container_FuelContainer,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DashBoard_Label_CondShim = lv_label_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Label_CondShim, LV_SIZE_CONTENT);   /// 1024
    lv_obj_set_height(ui_DashBoard_Label_CondShim, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_x(ui_DashBoard_Label_CondShim, 99);
    lv_obj_set_y(ui_DashBoard_Label_CondShim, -3);
    lv_label_set_text(ui_DashBoard_Label_CondShim, "000");
    lv_obj_set_style_text_color(ui_DashBoard_Label_CondShim, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_CondShim, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DashBoard_Label_CondShim, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_CondShim, &ui_font_BaseFont20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DashBoard_Label_CondShim, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Label_CondShim, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Label_VFirstShim = lv_label_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Label_VFirstShim, LV_SIZE_CONTENT);   /// 1024
    lv_obj_set_height(ui_DashBoard_Label_VFirstShim, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_x(ui_DashBoard_Label_VFirstShim, 178);
    lv_obj_set_y(ui_DashBoard_Label_VFirstShim, -3);
    lv_label_set_text(ui_DashBoard_Label_VFirstShim, "000");
    lv_obj_set_style_text_color(ui_DashBoard_Label_VFirstShim, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_VFirstShim, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DashBoard_Label_VFirstShim, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_VFirstShim, &ui_font_BaseFont20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DashBoard_Label_VFirstShim, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Label_VFirstShim, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Label_VSecondShim = lv_label_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Label_VSecondShim, LV_SIZE_CONTENT);   /// 1024
    lv_obj_set_height(ui_DashBoard_Label_VSecondShim, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_x(ui_DashBoard_Label_VSecondShim, 253);
    lv_obj_set_y(ui_DashBoard_Label_VSecondShim, -3);
    lv_label_set_text(ui_DashBoard_Label_VSecondShim, "000");
    lv_obj_set_style_text_color(ui_DashBoard_Label_VSecondShim, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_VSecondShim, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DashBoard_Label_VSecondShim, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_VSecondShim, &ui_font_BaseFont20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DashBoard_Label_VSecondShim, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Label_VSecondShim, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Label_EditionString = lv_label_create(ui_Screen_DashBoard);
    lv_obj_set_width(ui_DashBoard_Label_EditionString, 300);
    lv_obj_set_height(ui_DashBoard_Label_EditionString, 32);
    lv_obj_set_x(ui_DashBoard_Label_EditionString, 0);
    lv_obj_set_y(ui_DashBoard_Label_EditionString, -130);
    lv_obj_set_align(ui_DashBoard_Label_EditionString, LV_ALIGN_BOTTOM_MID);
    lv_label_set_long_mode(ui_DashBoard_Label_EditionString, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_DashBoard_Label_EditionString, "Привет, Куда поедем?");
    lv_obj_set_style_text_color(ui_DashBoard_Label_EditionString, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_EditionString, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DashBoard_Label_EditionString, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_EditionString, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DashBoard_Label_EditionString, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Label_EditionString, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Image_ImageCyan = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_ImageCyan, &ui_img_cyan_cat_png);
    lv_obj_set_width(ui_DashBoard_Image_ImageCyan, LV_SIZE_CONTENT);   /// 140
    lv_obj_set_height(ui_DashBoard_Image_ImageCyan, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_x(ui_DashBoard_Image_ImageCyan, 0);
    lv_obj_set_y(ui_DashBoard_Image_ImageCyan, -71);
    lv_obj_set_align(ui_DashBoard_Image_ImageCyan, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DashBoard_Image_ImageCyan, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Image_ImageCyan,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DashBoard_Image_ImageGreen = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_ImageGreen, &ui_img_green_cat_png);
    lv_obj_set_width(ui_DashBoard_Image_ImageGreen, LV_SIZE_CONTENT);   /// 140
    lv_obj_set_height(ui_DashBoard_Image_ImageGreen, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_x(ui_DashBoard_Image_ImageGreen, 0);
    lv_obj_set_y(ui_DashBoard_Image_ImageGreen, -71);
    lv_obj_set_align(ui_DashBoard_Image_ImageGreen, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DashBoard_Image_ImageGreen, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Image_ImageGreen,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DashBoard_Image_ImageYellow = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_ImageYellow, &ui_img_yellow_cat_png);
    lv_obj_set_width(ui_DashBoard_Image_ImageYellow, LV_SIZE_CONTENT);   /// 140
    lv_obj_set_height(ui_DashBoard_Image_ImageYellow, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_x(ui_DashBoard_Image_ImageYellow, 0);
    lv_obj_set_y(ui_DashBoard_Image_ImageYellow, -71);
    lv_obj_set_align(ui_DashBoard_Image_ImageYellow, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DashBoard_Image_ImageYellow, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Image_ImageYellow,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DashBoard_Image_ImageRed = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_ImageRed, &ui_img_red_cat_png);
    lv_obj_set_width(ui_DashBoard_Image_ImageRed, LV_SIZE_CONTENT);   /// 140
    lv_obj_set_height(ui_DashBoard_Image_ImageRed, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_x(ui_DashBoard_Image_ImageRed, 0);
    lv_obj_set_y(ui_DashBoard_Image_ImageRed, -71);
    lv_obj_set_align(ui_DashBoard_Image_ImageRed, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DashBoard_Image_ImageRed, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Image_ImageRed,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DashBoard_Container_ContainerRez = lv_obj_create(ui_Screen_DashBoard);
    lv_obj_remove_style_all(ui_DashBoard_Container_ContainerRez);
    lv_obj_set_width(ui_DashBoard_Container_ContainerRez, 140);
    lv_obj_set_height(ui_DashBoard_Container_ContainerRez, 90);
    lv_obj_set_x(ui_DashBoard_Container_ContainerRez, 0);
    lv_obj_set_y(ui_DashBoard_Container_ContainerRez, -71);
    lv_obj_set_align(ui_DashBoard_Container_ContainerRez, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_DashBoard_Container_ContainerRez,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DashBoard_Image_WiFi = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_WiFi, &ui_img_iconwifi_png);
    lv_obj_set_width(ui_DashBoard_Image_WiFi, LV_SIZE_CONTENT);   /// 94
    lv_obj_set_height(ui_DashBoard_Image_WiFi, LV_SIZE_CONTENT);    /// 94
    lv_obj_set_x(ui_DashBoard_Image_WiFi, 259);
    lv_obj_set_y(ui_DashBoard_Image_WiFi, -250);
    lv_obj_set_align(ui_DashBoard_Image_WiFi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DashBoard_Image_WiFi, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Image_WiFi,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DashBoard_Image_GPS = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_GPS, &ui_img_gps_png);
    lv_obj_set_width(ui_DashBoard_Image_GPS, LV_SIZE_CONTENT);   /// 96
    lv_obj_set_height(ui_DashBoard_Image_GPS, LV_SIZE_CONTENT);    /// 96
    lv_obj_set_x(ui_DashBoard_Image_GPS, 222);
    lv_obj_set_y(ui_DashBoard_Image_GPS, -245);
    lv_obj_set_align(ui_DashBoard_Image_GPS, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DashBoard_Image_GPS, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Image_GPS,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DashBoard_Image_ServerOn = lv_image_create(ui_Screen_DashBoard);
    lv_image_set_src(ui_DashBoard_Image_ServerOn, &ui_img_serverwifi_png);
    lv_obj_set_width(ui_DashBoard_Image_ServerOn, LV_SIZE_CONTENT);   /// 94
    lv_obj_set_height(ui_DashBoard_Image_ServerOn, LV_SIZE_CONTENT);    /// 94
    lv_obj_set_x(ui_DashBoard_Image_ServerOn, 469);
    lv_obj_set_y(ui_DashBoard_Image_ServerOn, 231);
    lv_obj_set_align(ui_DashBoard_Image_ServerOn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DashBoard_Image_ServerOn, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Image_ServerOn,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DashBoard_Container_ContainerClimate = lv_obj_create(ui_Screen_DashBoard);
    lv_obj_remove_style_all(ui_DashBoard_Container_ContainerClimate);
    lv_obj_set_width(ui_DashBoard_Container_ContainerClimate, 1024);
    lv_obj_set_height(ui_DashBoard_Container_ContainerClimate, 600);
    lv_obj_add_flag(ui_DashBoard_Container_ContainerClimate, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Container_ContainerClimate,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DashBoard_Container_ContainerClimate, lv_color_hex(0x000429),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Container_ContainerClimate, 192, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Label_LabelCC = lv_label_create(ui_DashBoard_Container_ContainerClimate);
    lv_obj_set_width(ui_DashBoard_Label_LabelCC, 400);
    lv_obj_set_height(ui_DashBoard_Label_LabelCC, 30);
    lv_obj_set_x(ui_DashBoard_Label_LabelCC, 0);
    lv_obj_set_y(ui_DashBoard_Label_LabelCC, 10);
    lv_obj_set_align(ui_DashBoard_Label_LabelCC, LV_ALIGN_TOP_MID);
    lv_obj_set_ext_click_area(ui_DashBoard_Label_LabelCC, 20);
    lv_label_set_long_mode(ui_DashBoard_Label_LabelCC, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_DashBoard_Label_LabelCC, "");
    lv_obj_add_flag(ui_DashBoard_Label_LabelCC, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Label_LabelCC,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DashBoard_Label_LabelCC, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_LabelCC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DashBoard_Label_LabelCC, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_DashBoard_Label_LabelCC, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_LabelCC, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DashBoard_Label_LabelCC, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Label_LabelCC, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Label_Label13 = lv_label_create(ui_DashBoard_Container_ContainerClimate);
    lv_obj_set_width(ui_DashBoard_Label_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DashBoard_Label_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DashBoard_Label_Label13, 35);
    lv_obj_set_y(ui_DashBoard_Label_Label13, 70);
    lv_obj_set_align(ui_DashBoard_Label_Label13, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_DashBoard_Label_Label13, "Температура");
    lv_obj_remove_flag(ui_DashBoard_Label_Label13,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DashBoard_Label_Label13, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_Label13, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Label_Label14 = lv_label_create(ui_DashBoard_Container_ContainerClimate);
    lv_obj_set_width(ui_DashBoard_Label_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DashBoard_Label_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DashBoard_Label_Label14, 36);
    lv_obj_set_y(ui_DashBoard_Label_Label14, 268);
    lv_obj_set_align(ui_DashBoard_Label_Label14, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_DashBoard_Label_Label14,
                      "Салон---------------------------Ноги---------------------------Стекло");
    lv_obj_remove_flag(ui_DashBoard_Label_Label14,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DashBoard_Label_Label14, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_Label14, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Label_Label15 = lv_label_create(ui_DashBoard_Container_ContainerClimate);
    lv_obj_set_width(ui_DashBoard_Label_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DashBoard_Label_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DashBoard_Label_Label15, 35);
    lv_obj_set_y(ui_DashBoard_Label_Label15, 446);
    lv_obj_set_align(ui_DashBoard_Label_Label15, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_DashBoard_Label_Label15, "Сила");
    lv_obj_remove_flag(ui_DashBoard_Label_Label15,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DashBoard_Label_Label15, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_Label15, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Switch_TempSwitch = lv_switch_create(ui_DashBoard_Container_ContainerClimate);
    lv_obj_set_width(ui_DashBoard_Switch_TempSwitch, 66);
    lv_obj_set_height(ui_DashBoard_Switch_TempSwitch, 25);
    lv_obj_set_x(ui_DashBoard_Switch_TempSwitch, -451);
    lv_obj_set_y(ui_DashBoard_Switch_TempSwitch, -150);
    lv_obj_set_align(ui_DashBoard_Switch_TempSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_DashBoard_Switch_TempSwitch, lv_color_hex(0x000810), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Switch_TempSwitch, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_DashBoard_Switch_TempSwitch, lv_color_hex(0x00FF17), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Switch_TempSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_DashBoard_Switch_AlignSwitch = lv_switch_create(ui_DashBoard_Container_ContainerClimate);
    lv_obj_set_width(ui_DashBoard_Switch_AlignSwitch, 66);
    lv_obj_set_height(ui_DashBoard_Switch_AlignSwitch, 25);
    lv_obj_set_x(ui_DashBoard_Switch_AlignSwitch, -452);
    lv_obj_set_y(ui_DashBoard_Switch_AlignSwitch, 50);
    lv_obj_set_align(ui_DashBoard_Switch_AlignSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_DashBoard_Switch_AlignSwitch, lv_color_hex(0x000810), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Switch_AlignSwitch, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_DashBoard_Switch_AlignSwitch, lv_color_hex(0x00FF17), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Switch_AlignSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_DashBoard_Switch_FlpwSwitch = lv_switch_create(ui_DashBoard_Container_ContainerClimate);
    lv_obj_set_width(ui_DashBoard_Switch_FlpwSwitch, 66);
    lv_obj_set_height(ui_DashBoard_Switch_FlpwSwitch, 25);
    lv_obj_set_x(ui_DashBoard_Switch_FlpwSwitch, -448);
    lv_obj_set_y(ui_DashBoard_Switch_FlpwSwitch, 229);
    lv_obj_set_align(ui_DashBoard_Switch_FlpwSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_DashBoard_Switch_FlpwSwitch, lv_color_hex(0x000810), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Switch_FlpwSwitch, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_DashBoard_Switch_FlpwSwitch, lv_color_hex(0x00FF17), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Switch_FlpwSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_DashBoard_Slider_TempSlider = lv_slider_create(ui_DashBoard_Container_ContainerClimate);
    lv_slider_set_range(ui_DashBoard_Slider_TempSlider, -20, 20);
    lv_slider_set_mode(ui_DashBoard_Slider_TempSlider, LV_SLIDER_MODE_SYMMETRICAL);
    lv_slider_set_value(ui_DashBoard_Slider_TempSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_DashBoard_Slider_TempSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_DashBoard_Slider_TempSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_DashBoard_Slider_TempSlider, 800);
    lv_obj_set_height(ui_DashBoard_Slider_TempSlider, 60);
    lv_obj_set_x(ui_DashBoard_Slider_TempSlider, 35);
    lv_obj_set_y(ui_DashBoard_Slider_TempSlider, -150);
    lv_obj_set_align(ui_DashBoard_Slider_TempSlider, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_DashBoard_Slider_TempSlider, lv_color_hex(0x0000FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Slider_TempSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_DashBoard_Slider_TempSlider,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_DashBoard_Slider_TempSlider,
                                                                                  lv_obj_get_style_pad_right(ui_DashBoard_Slider_TempSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_DashBoard_Label_Temperatura = lv_label_create(ui_DashBoard_Container_ContainerClimate);
    lv_obj_set_width(ui_DashBoard_Label_Temperatura, LV_SIZE_CONTENT);   /// 1024
    lv_obj_set_height(ui_DashBoard_Label_Temperatura, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_x(ui_DashBoard_Label_Temperatura, 35);
    lv_obj_set_y(ui_DashBoard_Label_Temperatura, 134);
    lv_obj_set_align(ui_DashBoard_Label_Temperatura, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_DashBoard_Label_Temperatura, "000");
    lv_obj_set_style_text_color(ui_DashBoard_Label_Temperatura, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_Temperatura, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DashBoard_Label_Temperatura, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_Temperatura, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DashBoard_Label_Temperatura, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Label_Temperatura, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Slider_AlignSlider = lv_slider_create(ui_DashBoard_Container_ContainerClimate);
    lv_slider_set_range(ui_DashBoard_Slider_AlignSlider, 0, 255);
    lv_slider_set_value(ui_DashBoard_Slider_AlignSlider, 128, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_DashBoard_Slider_AlignSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_DashBoard_Slider_AlignSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_DashBoard_Slider_AlignSlider, 800);
    lv_obj_set_height(ui_DashBoard_Slider_AlignSlider, 60);
    lv_obj_set_x(ui_DashBoard_Slider_AlignSlider, 35);
    lv_obj_set_y(ui_DashBoard_Slider_AlignSlider, 50);
    lv_obj_set_align(ui_DashBoard_Slider_AlignSlider, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_DashBoard_Slider_AlignSlider, lv_color_hex(0x0000FF),
                              LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Slider_AlignSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_DashBoard_Slider_AlignSlider,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_DashBoard_Slider_AlignSlider,
                                                                                  lv_obj_get_style_pad_right(ui_DashBoard_Slider_AlignSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_DashBoard_Slider_FlowSlider = lv_slider_create(ui_DashBoard_Container_ContainerClimate);
    lv_slider_set_range(ui_DashBoard_Slider_FlowSlider, 0, 255);
    lv_slider_set_value(ui_DashBoard_Slider_FlowSlider, 128, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_DashBoard_Slider_FlowSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_DashBoard_Slider_FlowSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_DashBoard_Slider_FlowSlider, 800);
    lv_obj_set_height(ui_DashBoard_Slider_FlowSlider, 60);
    lv_obj_set_x(ui_DashBoard_Slider_FlowSlider, 35);
    lv_obj_set_y(ui_DashBoard_Slider_FlowSlider, 230);
    lv_obj_set_align(ui_DashBoard_Slider_FlowSlider, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_DashBoard_Slider_FlowSlider, lv_color_hex(0x0000FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Slider_FlowSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_DashBoard_Slider_FlowSlider,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_DashBoard_Slider_FlowSlider,
                                                                                  lv_obj_get_style_pad_right(ui_DashBoard_Slider_FlowSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_DashBoard_Label_FlowShim = lv_label_create(ui_DashBoard_Container_ContainerClimate);
    lv_obj_set_width(ui_DashBoard_Label_FlowShim, LV_SIZE_CONTENT);   /// 1024
    lv_obj_set_height(ui_DashBoard_Label_FlowShim, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_x(ui_DashBoard_Label_FlowShim, 35);
    lv_obj_set_y(ui_DashBoard_Label_FlowShim, 516);
    lv_obj_set_align(ui_DashBoard_Label_FlowShim, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_DashBoard_Label_FlowShim, "000");
    lv_obj_set_style_text_color(ui_DashBoard_Label_FlowShim, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashBoard_Label_FlowShim, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DashBoard_Label_FlowShim, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DashBoard_Label_FlowShim, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DashBoard_Label_FlowShim, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoard_Label_FlowShim, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashBoard_Container_AKBContainer = lv_obj_create(ui_Screen_DashBoard);
    lv_obj_remove_style_all(ui_DashBoard_Container_AKBContainer);
    lv_obj_set_width(ui_DashBoard_Container_AKBContainer, 209);
    lv_obj_set_height(ui_DashBoard_Container_AKBContainer, 192);
    lv_obj_set_x(ui_DashBoard_Container_AKBContainer, 7);
    lv_obj_set_y(ui_DashBoard_Container_AKBContainer, 304);
    lv_obj_add_flag(ui_DashBoard_Container_AKBContainer, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Container_AKBContainer,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DashBoard_Container_DebugContainer = lv_obj_create(ui_Screen_DashBoard);
    lv_obj_remove_style_all(ui_DashBoard_Container_DebugContainer);
    lv_obj_set_width(ui_DashBoard_Container_DebugContainer, 314);
    lv_obj_set_height(ui_DashBoard_Container_DebugContainer, 85);
    lv_obj_set_x(ui_DashBoard_Container_DebugContainer, 5);
    lv_obj_set_y(ui_DashBoard_Container_DebugContainer, 2);
    lv_obj_add_flag(ui_DashBoard_Container_DebugContainer, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_DashBoard_Container_DebugContainer,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    lv_obj_add_event_cb(ui_DashBoard_Label_Time, ui_event_DashBoard_Label_Time, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DashBoard_Container_CenterContainer, ui_event_DashBoard_Container_CenterContainer, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_DashBoard_Container_TripContainer, ui_event_DashBoard_Container_TripContainer, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_DashBoard_Container_FuelContainer, ui_event_DashBoard_Container_FuelContainer, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_DashBoard_Container_ContainerRez, ui_event_DashBoard_Container_ContainerRez, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DashBoard_Label_LabelCC, ui_event_DashBoard_Label_LabelCC, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DashBoard_Switch_TempSwitch, ui_event_DashBoard_Switch_TempSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DashBoard_Switch_AlignSwitch, ui_event_DashBoard_Switch_AlignSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DashBoard_Switch_FlpwSwitch, ui_event_DashBoard_Switch_FlpwSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DashBoard_Slider_TempSlider, ui_event_DashBoard_Slider_TempSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DashBoard_Slider_AlignSlider, ui_event_DashBoard_Slider_AlignSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DashBoard_Slider_FlowSlider, ui_event_DashBoard_Slider_FlowSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DashBoard_Container_AKBContainer, ui_event_DashBoard_Container_AKBContainer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DashBoard_Container_DebugContainer, ui_event_DashBoard_Container_DebugContainer, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_Screen_DashBoard, ui_event_Screen_DashBoard, LV_EVENT_ALL, NULL);
    uic_DashBoard_Label_q = ui_DashBoard_Label_TripTimePause;

}

void ui_Screen_DashBoard_screen_destroy(void)
{
    if(ui_Screen_DashBoard) lv_obj_del(ui_Screen_DashBoard);

    // NULL screen variables
    ui_Screen_DashBoard = NULL;
    ui_DashBoard_Label_FionaSpeachLabelDash = NULL;
    ui_DashBoard_Label_TahoLBL = NULL;
    ui_DashBoard_Arc_Taho = NULL;
    ui_DashBoard_Image_BlueRing = NULL;
    ui_DashBoard_Image_ImageSpeed = NULL;
    ui_DashBoard_Bar_BatBar = NULL;
    ui_DashBoard_Image_BatShape = NULL;
    ui_DashBoard_Image_Batallert = NULL;
    ui_DashBoard_Image_BatHL = NULL;
    ui_DashBoard_Bar_FuelBar = NULL;
    ui_DashBoard_Image_FuelShape = NULL;
    ui_DashBoard_Image_FuelNorm = NULL;
    ui_DashBoard_Image_FuelAllert = NULL;
    ui_DashBoard_Bar_TempBar = NULL;
    ui_DashBoard_Image_CoolShape = NULL;
    ui_DashBoard_Image_CoolNorm = NULL;
    ui_DashBoard_Image_CoolHigh = NULL;
    ui_DashBoard_Arc_Drossel = NULL;
    ui_DashBoard_Arc_Uskorenie = NULL;
    ui_DashBoard_Label_GazBL = NULL;
    ui_DashBoard_Label_AxelBL = NULL;
    ui_DashBoard_Label_AKB = NULL;
    ui_DashBoard_Label_FUEL = NULL;
    ui_DashBoard_Label_ODO = NULL;
    ui_DashBoard_Label_TempNum = NULL;
    ui_DashBoard_Image_TripImg = NULL;
    ui_DashBoard_Label_TripNum = NULL;
    ui_DashBoard_Label_TripTime = NULL;
    uic_DashBoard_Label_q = NULL;
    ui_DashBoard_Label_TripTimePause = NULL;
    ui_DashBoard_Label_TripLitr = NULL;
    ui_DashBoard_Label_Time = NULL;
    ui_DashBoard_Bar_lph = NULL;
    ui_DashBoard_Label_LPHnum = NULL;
    ui_DashBoard_Label_ODOonFuel = NULL;
    ui_DashBoard_Label_SpeedDigit = NULL;
    ui_DashBoard_Image_FreeWind = NULL;
    ui_DashBoard_Image_ConditionHot = NULL;
    ui_DashBoard_Image_ConditionCold = NULL;
    ui_DashBoard_Image_RFirstVent = NULL;
    ui_DashBoard_Image_RFirstVentAlert = NULL;
    ui_DashBoard_Image_RSecondVent = NULL;
    ui_DashBoard_Image_RSecondVentAlert = NULL;
    ui_DashBoard_Image_RSecondVentAlert1 = NULL;
    ui_DashBoard_Container_CenterContainer = NULL;
    ui_DashBoard_Container_TripContainer = NULL;
    ui_DashBoard_Container_FuelContainer = NULL;
    ui_DashBoard_Label_CondShim = NULL;
    ui_DashBoard_Label_VFirstShim = NULL;
    ui_DashBoard_Label_VSecondShim = NULL;
    ui_DashBoard_Label_EditionString = NULL;
    ui_DashBoard_Image_ImageCyan = NULL;
    ui_DashBoard_Image_ImageGreen = NULL;
    ui_DashBoard_Image_ImageYellow = NULL;
    ui_DashBoard_Image_ImageRed = NULL;
    ui_DashBoard_Container_ContainerRez = NULL;
    ui_DashBoard_Image_WiFi = NULL;
    ui_DashBoard_Image_GPS = NULL;
    ui_DashBoard_Image_ServerOn = NULL;
    ui_DashBoard_Container_ContainerClimate = NULL;
    ui_DashBoard_Label_LabelCC = NULL;
    ui_DashBoard_Label_Label13 = NULL;
    ui_DashBoard_Label_Label14 = NULL;
    ui_DashBoard_Label_Label15 = NULL;
    ui_DashBoard_Switch_TempSwitch = NULL;
    ui_DashBoard_Switch_AlignSwitch = NULL;
    ui_DashBoard_Switch_FlpwSwitch = NULL;
    ui_DashBoard_Slider_TempSlider = NULL;
    ui_DashBoard_Label_Temperatura = NULL;
    ui_DashBoard_Slider_AlignSlider = NULL;
    ui_DashBoard_Slider_FlowSlider = NULL;
    ui_DashBoard_Label_FlowShim = NULL;
    ui_DashBoard_Container_AKBContainer = NULL;
    ui_DashBoard_Container_DebugContainer = NULL;

}
