// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Fiona_Project

#ifndef UI_SCREEN_DASHBOARD_H
#define UI_SCREEN_DASHBOARD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_DashBoard
extern void ui_Screen_DashBoard_screen_init(void);
extern void ui_Screen_DashBoard_screen_destroy(void);
extern void ui_event_Screen_DashBoard(lv_event_t * e);
extern lv_obj_t * ui_Screen_DashBoard;
extern lv_obj_t * ui_DashBoard_Label_FionaSpeachLabelDash;
extern lv_obj_t * ui_DashBoard_Label_TahoLBL;
extern lv_obj_t * ui_DashBoard_Arc_Taho;
extern lv_obj_t * ui_DashBoard_Image_BlueRing;
extern lv_obj_t * ui_DashBoard_Image_ImageSpeed;
extern lv_obj_t * ui_DashBoard_Bar_BatBar;
extern lv_obj_t * ui_DashBoard_Image_BatShape;
extern lv_obj_t * ui_DashBoard_Image_Batallert;
extern lv_obj_t * ui_DashBoard_Image_BatHL;
extern lv_obj_t * ui_DashBoard_Bar_FuelBar;
extern lv_obj_t * ui_DashBoard_Image_FuelShape;
extern lv_obj_t * ui_DashBoard_Image_FuelNorm;
extern lv_obj_t * ui_DashBoard_Image_FuelAllert;
extern lv_obj_t * ui_DashBoard_Bar_TempBar;
extern lv_obj_t * ui_DashBoard_Image_CoolShape;
extern lv_obj_t * ui_DashBoard_Image_CoolNorm;
extern lv_obj_t * ui_DashBoard_Image_CoolHigh;
extern lv_obj_t * ui_DashBoard_Arc_Drossel;
extern lv_obj_t * ui_DashBoard_Arc_Uskorenie;
extern lv_obj_t * ui_DashBoard_Label_GazBL;
extern lv_obj_t * ui_DashBoard_Label_AxelBL;
extern lv_obj_t * ui_DashBoard_Label_AKB;
extern lv_obj_t * ui_DashBoard_Label_FUEL;
extern lv_obj_t * ui_DashBoard_Label_ODO;
extern lv_obj_t * ui_DashBoard_Label_TempNum;
extern lv_obj_t * ui_DashBoard_Image_TripImg;
extern lv_obj_t * ui_DashBoard_Label_TripNum;
extern lv_obj_t * ui_DashBoard_Label_TripTime;
extern lv_obj_t * ui_DashBoard_Label_TripTimePause;
extern lv_obj_t * ui_DashBoard_Label_TripLitr;
extern void ui_event_DashBoard_Label_Time(lv_event_t * e);
extern lv_obj_t * ui_DashBoard_Label_Time;
extern lv_obj_t * ui_DashBoard_Bar_lph;
extern lv_obj_t * ui_DashBoard_Label_LPHnum;
extern lv_obj_t * ui_DashBoard_Label_ODOonFuel;
extern lv_obj_t * ui_DashBoard_Label_SpeedDigit;
extern lv_obj_t * ui_DashBoard_Image_FreeWind;
extern lv_obj_t * ui_DashBoard_Image_ConditionHot;
extern lv_obj_t * ui_DashBoard_Image_ConditionCold;
extern lv_obj_t * ui_DashBoard_Image_RFirstVent;
extern lv_obj_t * ui_DashBoard_Image_RFirstVentAlert;
extern lv_obj_t * ui_DashBoard_Image_RSecondVent;
extern lv_obj_t * ui_DashBoard_Image_RSecondVentAlert;
extern lv_obj_t * ui_DashBoard_Image_RSecondVentAlert1;
extern void ui_event_DashBoard_Container_CenterContainer(lv_event_t * e);
extern lv_obj_t * ui_DashBoard_Container_CenterContainer;
extern void ui_event_DashBoard_Container_TripContainer(lv_event_t * e);
extern lv_obj_t * ui_DashBoard_Container_TripContainer;
extern void ui_event_DashBoard_Container_FuelContainer(lv_event_t * e);
extern lv_obj_t * ui_DashBoard_Container_FuelContainer;
extern lv_obj_t * ui_DashBoard_Label_CondShim;
extern lv_obj_t * ui_DashBoard_Label_VFirstShim;
extern lv_obj_t * ui_DashBoard_Label_VSecondShim;
extern lv_obj_t * ui_DashBoard_Label_EditionString;
extern lv_obj_t * ui_DashBoard_Image_ImageCyan;
extern lv_obj_t * ui_DashBoard_Image_ImageGreen;
extern lv_obj_t * ui_DashBoard_Image_ImageYellow;
extern lv_obj_t * ui_DashBoard_Image_ImageRed;
extern void ui_event_DashBoard_Container_ContainerRez(lv_event_t * e);
extern lv_obj_t * ui_DashBoard_Container_ContainerRez;
extern lv_obj_t * ui_DashBoard_Image_WiFi;
extern lv_obj_t * ui_DashBoard_Image_GPS;
extern lv_obj_t * ui_DashBoard_Image_ServerOn;
extern lv_obj_t * ui_DashBoard_Container_ContainerClimate;
extern void ui_event_DashBoard_Label_LabelCC(lv_event_t * e);
extern lv_obj_t * ui_DashBoard_Label_LabelCC;
extern lv_obj_t * ui_DashBoard_Label_Label13;
extern lv_obj_t * ui_DashBoard_Label_Label14;
extern lv_obj_t * ui_DashBoard_Label_Label15;
extern void ui_event_DashBoard_Switch_TempSwitch(lv_event_t * e);
extern lv_obj_t * ui_DashBoard_Switch_TempSwitch;
extern void ui_event_DashBoard_Switch_AlignSwitch(lv_event_t * e);
extern lv_obj_t * ui_DashBoard_Switch_AlignSwitch;
extern void ui_event_DashBoard_Switch_FlpwSwitch(lv_event_t * e);
extern lv_obj_t * ui_DashBoard_Switch_FlpwSwitch;
extern void ui_event_DashBoard_Slider_TempSlider(lv_event_t * e);
extern lv_obj_t * ui_DashBoard_Slider_TempSlider;
extern lv_obj_t * ui_DashBoard_Label_Temperatura;
extern void ui_event_DashBoard_Slider_AlignSlider(lv_event_t * e);
extern lv_obj_t * ui_DashBoard_Slider_AlignSlider;
extern void ui_event_DashBoard_Slider_FlowSlider(lv_event_t * e);
extern lv_obj_t * ui_DashBoard_Slider_FlowSlider;
extern lv_obj_t * ui_DashBoard_Label_FlowShim;
extern void ui_event_DashBoard_Container_AKBContainer(lv_event_t * e);
extern lv_obj_t * ui_DashBoard_Container_AKBContainer;
extern void ui_event_DashBoard_Container_DebugContainer(lv_event_t * e);
extern lv_obj_t * ui_DashBoard_Container_DebugContainer;
// CUSTOM VARIABLES
extern lv_obj_t * uic_DashBoard_Label_q;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

