// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Fiona_Project

#ifndef UI_SCREEN_DEBUGSCREEN_H
#define UI_SCREEN_DEBUGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_DebugScreen
extern void ui_Screen_DebugScreen_screen_init(void);
extern void ui_Screen_DebugScreen_screen_destroy(void);
extern lv_obj_t * ui_Screen_DebugScreen;
extern void ui_event_DebugScreen_Label_Label(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen_Label_Label;
extern void ui_event_DebugScreen_Textarea_TextAreaScreen(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen_Textarea_TextAreaScreen;
extern void ui_event_DebugScreen_Image_SDBack(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen_Image_SDBack;
extern void ui_event_DebugScreen_Image_SDGrey(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen_Image_SDGrey;
extern void ui_event_DebugScreen_Image_SDRed(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen_Image_SDRed;
extern void ui_event_DebugScreen_Image_ArduinoBack(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen_Image_ArduinoBack;
extern void ui_event_DebugScreen_Image_ArduinoGrey(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen_Image_ArduinoGrey;
extern void ui_event_DebugScreen_Image_ArduinoRed(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen_Image_ArduinoRed;
extern void ui_event_DebugScreen_Image_ESP32Back(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen_Image_ESP32Back;
extern void ui_event_DebugScreen_Image_ESP32Grey(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen_Image_ESP32Grey;
extern void ui_event_DebugScreen_Image_ESP32Red(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen_Image_ESP32Red;
extern void ui_event_DebugScreen_Image_SpeachBack(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen_Image_SpeachBack;
extern void ui_event_DebugScreen_Image_SpeachGrey(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen_Image_SpeachGrey;
extern void ui_event_DebugScreen_Image_SpeachRed(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen_Image_SpeachRed;
extern void ui_event_DebugScreen_Image_StatBack(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen_Image_StatBack;
extern void ui_event_DebugScreen_Image_StatGrey(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen_Image_StatGrey;
extern void ui_event_DebugScreen_Image_StatRed(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen_Image_StatRed;
extern void ui_event_DebugScreen_Image_PresetBack(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen_Image_PresetBack;
extern void ui_event_DebugScreen_Image_PresetGrey(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen_Image_PresetGrey;
extern void ui_event_DebugScreen_Image_PresetRed(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen_Image_PresetRed;
extern lv_obj_t * ui_DebugScreen_Label_Label16;
extern lv_obj_t * ui_DebugScreen_Label_Label17;
extern lv_obj_t * ui_DebugScreen_Label_Label18;
extern lv_obj_t * ui_DebugScreen_Label_Label19;
extern lv_obj_t * ui_DebugScreen_Label_Label20;
extern lv_obj_t * ui_DebugScreen_Label_Label21;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

