// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Fiona_Project

#include "../ui.h"

lv_obj_t * ui_Screen_ScreenReFuel = NULL;
lv_obj_t * ui_ScreenReFuel_Label_Label3 = NULL;
lv_obj_t * ui_ScreenReFuel_Textarea_TACurrentFuel = NULL;
lv_obj_t * ui_ScreenReFuel_Label_Zapravleno = NULL;
lv_obj_t * ui_ScreenReFuel_Textarea_TAPrise = NULL;
lv_obj_t * ui_ScreenReFuel_Label_LitrPrise = NULL;
lv_obj_t * ui_ScreenReFuel_Textarea_TAFuelToAdd = NULL;
lv_obj_t * ui_ScreenReFuel_Label_Label5 = NULL;
lv_obj_t * ui_ScreenReFuel_Textarea_TAODO = NULL;
lv_obj_t * ui_ScreenReFuel_Label_Calibrate = NULL;
lv_obj_t * ui_ScreenReFuel_Switch_SwitchFullTank = NULL;
lv_obj_t * ui_ScreenReFuel_Label_RefSaveLBtn = NULL;
// event funtions
void ui_event_ScreenReFuel_Label_Label3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ToHomeClick(e);
    }
}

void ui_event_ScreenReFuel_Textarea_TACurrentFuel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        OnTankFocus(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        TankDeFocus(e);
    }
}

void ui_event_ScreenReFuel_Textarea_TAPrise(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnPriseFocus(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        OnPriseDeFocus(e);
    }
}

void ui_event_ScreenReFuel_Textarea_TAFuelToAdd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        OnAddedFocus(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        OnAddedDeFocus(e);
    }
}

void ui_event_ScreenReFuel_Textarea_TAODO(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        OnOdoFocus(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        OnOdoDeFocus(e);
    }
}

void ui_event_ScreenReFuel_Switch_SwitchFullTank(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnCalibrateClicked(e);
    }
}

void ui_event_ScreenReFuel_Label_RefSaveLBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnSaveClk(e);
    }
}

// build funtions

void ui_Screen_ScreenReFuel_screen_init(void)
{
    ui_Screen_ScreenReFuel = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_ScreenReFuel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Screen_ScreenReFuel, &ui_img_global_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenReFuel_Label_Label3 = lv_label_create(ui_Screen_ScreenReFuel);
    lv_obj_set_width(ui_ScreenReFuel_Label_Label3, 400);
    lv_obj_set_height(ui_ScreenReFuel_Label_Label3, 30);
    lv_obj_set_x(ui_ScreenReFuel_Label_Label3, 0);
    lv_obj_set_y(ui_ScreenReFuel_Label_Label3, 10);
    lv_obj_set_align(ui_ScreenReFuel_Label_Label3, LV_ALIGN_TOP_MID);
    lv_obj_set_ext_click_area(ui_ScreenReFuel_Label_Label3, 20);
    lv_label_set_long_mode(ui_ScreenReFuel_Label_Label3, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_ScreenReFuel_Label_Label3, "Домой...");
    lv_obj_add_flag(ui_ScreenReFuel_Label_Label3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ScreenReFuel_Label_Label3,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_ScreenReFuel_Label_Label3, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenReFuel_Label_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ScreenReFuel_Label_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ScreenReFuel_Label_Label3, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenReFuel_Label_Label3, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenReFuel_Textarea_TACurrentFuel = lv_textarea_create(ui_Screen_ScreenReFuel);
    lv_obj_set_width(ui_ScreenReFuel_Textarea_TACurrentFuel, 135);
    lv_obj_set_height(ui_ScreenReFuel_Textarea_TACurrentFuel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreenReFuel_Textarea_TACurrentFuel, -403);
    lv_obj_set_y(ui_ScreenReFuel_Textarea_TACurrentFuel, -215);
    lv_obj_set_align(ui_ScreenReFuel_Textarea_TACurrentFuel, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_ScreenReFuel_Textarea_TACurrentFuel, "1234567890,.");
    lv_textarea_set_max_length(ui_ScreenReFuel_Textarea_TACurrentFuel, 4);
    lv_textarea_set_placeholder_text(ui_ScreenReFuel_Textarea_TACurrentFuel, "20,0");
    lv_textarea_set_one_line(ui_ScreenReFuel_Textarea_TACurrentFuel, true);
    lv_obj_set_style_text_color(ui_ScreenReFuel_Textarea_TACurrentFuel, lv_color_hex(0x00FF1C),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenReFuel_Textarea_TACurrentFuel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ScreenReFuel_Textarea_TACurrentFuel, LV_TEXT_ALIGN_LEFT,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenReFuel_Textarea_TACurrentFuel, &ui_font_LedSymbol, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenReFuel_Textarea_TACurrentFuel, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenReFuel_Textarea_TACurrentFuel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenReFuel_Label_Zapravleno = lv_label_create(ui_Screen_ScreenReFuel);
    lv_obj_set_width(ui_ScreenReFuel_Label_Zapravleno, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenReFuel_Label_Zapravleno, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreenReFuel_Label_Zapravleno, -216);
    lv_obj_set_y(ui_ScreenReFuel_Label_Zapravleno, -175);
    lv_obj_set_align(ui_ScreenReFuel_Label_Zapravleno, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenReFuel_Label_Zapravleno, "Заправлено:");
    lv_obj_set_style_text_color(ui_ScreenReFuel_Label_Zapravleno, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenReFuel_Label_Zapravleno, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenReFuel_Label_Zapravleno, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenReFuel_Textarea_TAPrise = lv_textarea_create(ui_Screen_ScreenReFuel);
    lv_obj_set_width(ui_ScreenReFuel_Textarea_TAPrise, 163);
    lv_obj_set_height(ui_ScreenReFuel_Textarea_TAPrise, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreenReFuel_Textarea_TAPrise, 375);
    lv_obj_set_y(ui_ScreenReFuel_Textarea_TAPrise, -174);
    lv_obj_set_align(ui_ScreenReFuel_Textarea_TAPrise, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_ScreenReFuel_Textarea_TAPrise, "1234567890,.");
    lv_textarea_set_max_length(ui_ScreenReFuel_Textarea_TAPrise, 5);
    lv_textarea_set_placeholder_text(ui_ScreenReFuel_Textarea_TAPrise, "63,87");
    lv_textarea_set_one_line(ui_ScreenReFuel_Textarea_TAPrise, true);
    lv_obj_set_style_text_color(ui_ScreenReFuel_Textarea_TAPrise, lv_color_hex(0x00FF1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenReFuel_Textarea_TAPrise, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ScreenReFuel_Textarea_TAPrise, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenReFuel_Textarea_TAPrise, &ui_font_LedSymbol, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenReFuel_Textarea_TAPrise, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenReFuel_Textarea_TAPrise, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenReFuel_Label_LitrPrise = lv_label_create(ui_Screen_ScreenReFuel);
    lv_obj_set_width(ui_ScreenReFuel_Label_LitrPrise, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenReFuel_Label_LitrPrise, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreenReFuel_Label_LitrPrise, 145);
    lv_obj_set_y(ui_ScreenReFuel_Label_LitrPrise, -174);
    lv_obj_set_align(ui_ScreenReFuel_Label_LitrPrise, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenReFuel_Label_LitrPrise, "Цена за литр:");
    lv_obj_set_style_text_color(ui_ScreenReFuel_Label_LitrPrise, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenReFuel_Label_LitrPrise, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenReFuel_Label_LitrPrise, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenReFuel_Textarea_TAFuelToAdd = lv_textarea_create(ui_Screen_ScreenReFuel);
    lv_obj_set_width(ui_ScreenReFuel_Textarea_TAFuelToAdd, 139);
    lv_obj_set_height(ui_ScreenReFuel_Textarea_TAFuelToAdd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreenReFuel_Textarea_TAFuelToAdd, -50);
    lv_obj_set_y(ui_ScreenReFuel_Textarea_TAFuelToAdd, -171);
    lv_obj_set_align(ui_ScreenReFuel_Textarea_TAFuelToAdd, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_ScreenReFuel_Textarea_TAFuelToAdd, "1234567890,.");
    lv_textarea_set_max_length(ui_ScreenReFuel_Textarea_TAFuelToAdd, 4);
    lv_textarea_set_placeholder_text(ui_ScreenReFuel_Textarea_TAFuelToAdd, "20,0");
    lv_textarea_set_one_line(ui_ScreenReFuel_Textarea_TAFuelToAdd, true);
    lv_obj_set_style_text_color(ui_ScreenReFuel_Textarea_TAFuelToAdd, lv_color_hex(0x00FF1C),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenReFuel_Textarea_TAFuelToAdd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ScreenReFuel_Textarea_TAFuelToAdd, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenReFuel_Textarea_TAFuelToAdd, &ui_font_LedSymbol, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenReFuel_Textarea_TAFuelToAdd, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenReFuel_Textarea_TAFuelToAdd, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenReFuel_Label_Label5 = lv_label_create(ui_Screen_ScreenReFuel);
    lv_obj_set_width(ui_ScreenReFuel_Label_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenReFuel_Label_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreenReFuel_Label_Label5, -160);
    lv_obj_set_y(ui_ScreenReFuel_Label_Label5, -90);
    lv_obj_set_align(ui_ScreenReFuel_Label_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenReFuel_Label_Label5, "Показания одометра:");
    lv_obj_set_style_text_color(ui_ScreenReFuel_Label_Label5, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenReFuel_Label_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenReFuel_Label_Label5, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenReFuel_Textarea_TAODO = lv_textarea_create(ui_Screen_ScreenReFuel);
    lv_obj_set_width(ui_ScreenReFuel_Textarea_TAODO, 217);
    lv_obj_set_height(ui_ScreenReFuel_Textarea_TAODO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreenReFuel_Textarea_TAODO, 130);
    lv_obj_set_y(ui_ScreenReFuel_Textarea_TAODO, -91);
    lv_obj_set_align(ui_ScreenReFuel_Textarea_TAODO, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_ScreenReFuel_Textarea_TAODO, "1234567890,.");
    lv_textarea_set_max_length(ui_ScreenReFuel_Textarea_TAODO, 7);
    lv_textarea_set_placeholder_text(ui_ScreenReFuel_Textarea_TAODO, "190000");
    lv_textarea_set_one_line(ui_ScreenReFuel_Textarea_TAODO, true);
    lv_obj_set_style_text_color(ui_ScreenReFuel_Textarea_TAODO, lv_color_hex(0x00FF1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenReFuel_Textarea_TAODO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ScreenReFuel_Textarea_TAODO, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenReFuel_Textarea_TAODO, &ui_font_LedSymbol, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenReFuel_Textarea_TAODO, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenReFuel_Textarea_TAODO, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenReFuel_Label_Calibrate = lv_label_create(ui_Screen_ScreenReFuel);
    lv_obj_set_width(ui_ScreenReFuel_Label_Calibrate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenReFuel_Label_Calibrate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreenReFuel_Label_Calibrate, 330);
    lv_obj_set_y(ui_ScreenReFuel_Label_Calibrate, -90);
    lv_obj_set_align(ui_ScreenReFuel_Label_Calibrate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenReFuel_Label_Calibrate, "Калибровка");
    lv_obj_set_style_text_color(ui_ScreenReFuel_Label_Calibrate, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenReFuel_Label_Calibrate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenReFuel_Label_Calibrate, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenReFuel_Switch_SwitchFullTank = lv_switch_create(ui_Screen_ScreenReFuel);
    lv_obj_set_width(ui_ScreenReFuel_Switch_SwitchFullTank, 60);
    lv_obj_set_height(ui_ScreenReFuel_Switch_SwitchFullTank, 30);
    lv_obj_set_x(ui_ScreenReFuel_Switch_SwitchFullTank, 449);
    lv_obj_set_y(ui_ScreenReFuel_Switch_SwitchFullTank, -90);
    lv_obj_set_align(ui_ScreenReFuel_Switch_SwitchFullTank, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ScreenReFuel_Switch_SwitchFullTank, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenReFuel_Switch_SwitchFullTank, 64, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ScreenReFuel_Switch_SwitchFullTank, lv_color_hex(0x00FF00),
                              LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenReFuel_Switch_SwitchFullTank, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ScreenReFuel_Label_RefSaveLBtn = lv_label_create(ui_Screen_ScreenReFuel);
    lv_obj_set_width(ui_ScreenReFuel_Label_RefSaveLBtn, 200);
    lv_obj_set_height(ui_ScreenReFuel_Label_RefSaveLBtn, 35);
    lv_obj_set_x(ui_ScreenReFuel_Label_RefSaveLBtn, 70);
    lv_obj_set_y(ui_ScreenReFuel_Label_RefSaveLBtn, 0);
    lv_obj_set_align(ui_ScreenReFuel_Label_RefSaveLBtn, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_ScreenReFuel_Label_RefSaveLBtn, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_ScreenReFuel_Label_RefSaveLBtn, "Заправлено");
    lv_obj_add_flag(ui_ScreenReFuel_Label_RefSaveLBtn, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_ScreenReFuel_Label_RefSaveLBtn, lv_color_hex(0x18187B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenReFuel_Label_RefSaveLBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ScreenReFuel_Label_RefSaveLBtn, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ScreenReFuel_Label_RefSaveLBtn, LV_TEXT_DECOR_UNDERLINE,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenReFuel_Label_RefSaveLBtn, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ScreenReFuel_Label_RefSaveLBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenReFuel_Label_RefSaveLBtn, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenReFuel_Label_RefSaveLBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenReFuel_Label_Label3, ui_event_ScreenReFuel_Label_Label3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenReFuel_Textarea_TACurrentFuel, ui_event_ScreenReFuel_Textarea_TACurrentFuel, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_ScreenReFuel_Textarea_TAPrise, ui_event_ScreenReFuel_Textarea_TAPrise, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenReFuel_Textarea_TAFuelToAdd, ui_event_ScreenReFuel_Textarea_TAFuelToAdd, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_ScreenReFuel_Textarea_TAODO, ui_event_ScreenReFuel_Textarea_TAODO, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenReFuel_Switch_SwitchFullTank, ui_event_ScreenReFuel_Switch_SwitchFullTank, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_ScreenReFuel_Label_RefSaveLBtn, ui_event_ScreenReFuel_Label_RefSaveLBtn, LV_EVENT_ALL, NULL);

}

void ui_Screen_ScreenReFuel_screen_destroy(void)
{
    if(ui_Screen_ScreenReFuel) lv_obj_del(ui_Screen_ScreenReFuel);

    // NULL screen variables
    ui_Screen_ScreenReFuel = NULL;
    ui_ScreenReFuel_Label_Label3 = NULL;
    ui_ScreenReFuel_Textarea_TACurrentFuel = NULL;
    ui_ScreenReFuel_Label_Zapravleno = NULL;
    ui_ScreenReFuel_Textarea_TAPrise = NULL;
    ui_ScreenReFuel_Label_LitrPrise = NULL;
    ui_ScreenReFuel_Textarea_TAFuelToAdd = NULL;
    ui_ScreenReFuel_Label_Label5 = NULL;
    ui_ScreenReFuel_Textarea_TAODO = NULL;
    ui_ScreenReFuel_Label_Calibrate = NULL;
    ui_ScreenReFuel_Switch_SwitchFullTank = NULL;
    ui_ScreenReFuel_Label_RefSaveLBtn = NULL;

}
