// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Fiona_Project

#include "../ui.h"

lv_obj_t * ui_Screen_DebugScreen = NULL;
lv_obj_t * ui_DebugScreen_Label_Label = NULL;
lv_obj_t * ui_DebugScreen_Textarea_TextAreaScreen = NULL;
lv_obj_t * ui_DebugScreen_Image_SDBack = NULL;
lv_obj_t * ui_DebugScreen_Image_SDGrey = NULL;
lv_obj_t * ui_DebugScreen_Image_SDRed = NULL;
lv_obj_t * ui_DebugScreen_Image_ArduinoBack = NULL;
lv_obj_t * ui_DebugScreen_Image_ArduinoGrey = NULL;
lv_obj_t * ui_DebugScreen_Image_ArduinoRed = NULL;
lv_obj_t * ui_DebugScreen_Image_ESP32Back = NULL;
lv_obj_t * ui_DebugScreen_Image_ESP32Grey = NULL;
lv_obj_t * ui_DebugScreen_Image_ESP32Red = NULL;
lv_obj_t * ui_DebugScreen_Image_SpeachBack = NULL;
lv_obj_t * ui_DebugScreen_Image_SpeachGrey = NULL;
lv_obj_t * ui_DebugScreen_Image_SpeachRed = NULL;
lv_obj_t * ui_DebugScreen_Image_StatBack = NULL;
lv_obj_t * ui_DebugScreen_Image_StatGrey = NULL;
lv_obj_t * ui_DebugScreen_Image_StatRed = NULL;
lv_obj_t * ui_DebugScreen_Image_PresetBack = NULL;
lv_obj_t * ui_DebugScreen_Image_PresetGrey = NULL;
lv_obj_t * ui_DebugScreen_Image_PresetRed = NULL;
lv_obj_t * ui_DebugScreen_Label_Label16 = NULL;
lv_obj_t * ui_DebugScreen_Label_Label17 = NULL;
lv_obj_t * ui_DebugScreen_Label_Label18 = NULL;
lv_obj_t * ui_DebugScreen_Label_Label19 = NULL;
lv_obj_t * ui_DebugScreen_Label_Label20 = NULL;
lv_obj_t * ui_DebugScreen_Label_Label21 = NULL;
// event funtions
void ui_event_DebugScreen_Label_Label(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ToHomeClick(e);
    }
}

void ui_event_DebugScreen_Textarea_TextAreaScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnDebugScreen(e);
    }
}

void ui_event_DebugScreen_Image_SDBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnSdClick(e);
    }
}

void ui_event_DebugScreen_Image_SDGrey(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnSdClick(e);
    }
}

void ui_event_DebugScreen_Image_SDRed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnSdClick(e);
    }
}

void ui_event_DebugScreen_Image_ArduinoBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnArduinoClk(e);
    }
}

void ui_event_DebugScreen_Image_ArduinoGrey(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnArduinoClk(e);
    }
}

void ui_event_DebugScreen_Image_ArduinoRed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnArduinoClk(e);
    }
}

void ui_event_DebugScreen_Image_ESP32Back(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnESPClk(e);
    }
}

void ui_event_DebugScreen_Image_ESP32Grey(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnESPClk(e);
    }
}

void ui_event_DebugScreen_Image_ESP32Red(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnESPClk(e);
    }
}

void ui_event_DebugScreen_Image_SpeachBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnSpeachClk(e);
    }
}

void ui_event_DebugScreen_Image_SpeachGrey(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnSpeachClk(e);
    }
}

void ui_event_DebugScreen_Image_SpeachRed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnSpeachClk(e);
    }
}

void ui_event_DebugScreen_Image_StatBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnStatClk(e);
    }
}

void ui_event_DebugScreen_Image_StatGrey(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnStatClk(e);
    }
}

void ui_event_DebugScreen_Image_StatRed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnStatClk(e);
    }
}

void ui_event_DebugScreen_Image_PresetBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnPresetsClk(e);
    }
}

void ui_event_DebugScreen_Image_PresetGrey(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnPresetsClk(e);
    }
}

void ui_event_DebugScreen_Image_PresetRed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnPresetsClk(e);
    }
}

// build funtions

void ui_Screen_DebugScreen_screen_init(void)
{
    ui_Screen_DebugScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_DebugScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Screen_DebugScreen, &ui_img_global_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DebugScreen_Label_Label = lv_label_create(ui_Screen_DebugScreen);
    lv_obj_set_width(ui_DebugScreen_Label_Label, 400);
    lv_obj_set_height(ui_DebugScreen_Label_Label, 30);
    lv_obj_set_x(ui_DebugScreen_Label_Label, 0);
    lv_obj_set_y(ui_DebugScreen_Label_Label, 10);
    lv_obj_set_align(ui_DebugScreen_Label_Label, LV_ALIGN_TOP_MID);
    lv_obj_set_ext_click_area(ui_DebugScreen_Label_Label, 20);
    lv_label_set_long_mode(ui_DebugScreen_Label_Label, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_DebugScreen_Label_Label, "Домой...");
    lv_obj_add_flag(ui_DebugScreen_Label_Label, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DebugScreen_Label_Label,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DebugScreen_Label_Label, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DebugScreen_Label_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DebugScreen_Label_Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_DebugScreen_Label_Label, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DebugScreen_Label_Label, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DebugScreen_Textarea_TextAreaScreen = lv_textarea_create(ui_Screen_DebugScreen);
    lv_obj_set_width(ui_DebugScreen_Textarea_TextAreaScreen, 632);
    lv_obj_set_height(ui_DebugScreen_Textarea_TextAreaScreen, 483);
    lv_obj_set_x(ui_DebugScreen_Textarea_TextAreaScreen, 33);
    lv_obj_set_y(ui_DebugScreen_Textarea_TextAreaScreen, 81);
    lv_textarea_set_text(ui_DebugScreen_Textarea_TextAreaScreen, "Данные системы.\n");
    lv_textarea_set_placeholder_text(ui_DebugScreen_Textarea_TextAreaScreen, "Placeholder...");
    lv_obj_remove_flag(ui_DebugScreen_Textarea_TextAreaScreen,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DebugScreen_Textarea_TextAreaScreen, lv_color_hex(0x01C840),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DebugScreen_Textarea_TextAreaScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DebugScreen_Textarea_TextAreaScreen, &ui_font_BaseFont16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DebugScreen_Textarea_TextAreaScreen, lv_color_hex(0x000810),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DebugScreen_Textarea_TextAreaScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DebugScreen_Image_SDBack = lv_image_create(ui_Screen_DebugScreen);
    lv_image_set_src(ui_DebugScreen_Image_SDBack, &ui_img_black_png);
    lv_obj_set_width(ui_DebugScreen_Image_SDBack, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_DebugScreen_Image_SDBack, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_DebugScreen_Image_SDBack, 880);
    lv_obj_set_y(ui_DebugScreen_Image_SDBack, -180);
    lv_obj_set_align(ui_DebugScreen_Image_SDBack, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DebugScreen_Image_SDBack, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DebugScreen_Image_SDBack,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DebugScreen_Image_SDGrey = lv_image_create(ui_Screen_DebugScreen);
    lv_image_set_src(ui_DebugScreen_Image_SDGrey, &ui_img_grey_png);
    lv_obj_set_width(ui_DebugScreen_Image_SDGrey, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_DebugScreen_Image_SDGrey, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_DebugScreen_Image_SDGrey, 880);
    lv_obj_set_y(ui_DebugScreen_Image_SDGrey, -180);
    lv_obj_set_align(ui_DebugScreen_Image_SDGrey, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DebugScreen_Image_SDGrey, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DebugScreen_Image_SDGrey,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DebugScreen_Image_SDRed = lv_image_create(ui_Screen_DebugScreen);
    lv_image_set_src(ui_DebugScreen_Image_SDRed, &ui_img_red_png);
    lv_obj_set_width(ui_DebugScreen_Image_SDRed, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_DebugScreen_Image_SDRed, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_DebugScreen_Image_SDRed, 880);
    lv_obj_set_y(ui_DebugScreen_Image_SDRed, -180);
    lv_obj_set_align(ui_DebugScreen_Image_SDRed, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DebugScreen_Image_SDRed, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DebugScreen_Image_SDRed,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DebugScreen_Image_ArduinoBack = lv_image_create(ui_Screen_DebugScreen);
    lv_image_set_src(ui_DebugScreen_Image_ArduinoBack, &ui_img_black_png);
    lv_obj_set_width(ui_DebugScreen_Image_ArduinoBack, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_DebugScreen_Image_ArduinoBack, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_DebugScreen_Image_ArduinoBack, 880);
    lv_obj_set_y(ui_DebugScreen_Image_ArduinoBack, -97);
    lv_obj_set_align(ui_DebugScreen_Image_ArduinoBack, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DebugScreen_Image_ArduinoBack, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DebugScreen_Image_ArduinoBack,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DebugScreen_Image_ArduinoGrey = lv_image_create(ui_Screen_DebugScreen);
    lv_image_set_src(ui_DebugScreen_Image_ArduinoGrey, &ui_img_grey_png);
    lv_obj_set_width(ui_DebugScreen_Image_ArduinoGrey, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_DebugScreen_Image_ArduinoGrey, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_DebugScreen_Image_ArduinoGrey, 880);
    lv_obj_set_y(ui_DebugScreen_Image_ArduinoGrey, -97);
    lv_obj_set_align(ui_DebugScreen_Image_ArduinoGrey, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DebugScreen_Image_ArduinoGrey, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DebugScreen_Image_ArduinoGrey,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DebugScreen_Image_ArduinoRed = lv_image_create(ui_Screen_DebugScreen);
    lv_image_set_src(ui_DebugScreen_Image_ArduinoRed, &ui_img_red_png);
    lv_obj_set_width(ui_DebugScreen_Image_ArduinoRed, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_DebugScreen_Image_ArduinoRed, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_DebugScreen_Image_ArduinoRed, 880);
    lv_obj_set_y(ui_DebugScreen_Image_ArduinoRed, -97);
    lv_obj_set_align(ui_DebugScreen_Image_ArduinoRed, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DebugScreen_Image_ArduinoRed, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DebugScreen_Image_ArduinoRed,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DebugScreen_Image_ESP32Back = lv_image_create(ui_Screen_DebugScreen);
    lv_image_set_src(ui_DebugScreen_Image_ESP32Back, &ui_img_black_png);
    lv_obj_set_width(ui_DebugScreen_Image_ESP32Back, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_DebugScreen_Image_ESP32Back, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_DebugScreen_Image_ESP32Back, 880);
    lv_obj_set_y(ui_DebugScreen_Image_ESP32Back, -15);
    lv_obj_set_align(ui_DebugScreen_Image_ESP32Back, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DebugScreen_Image_ESP32Back, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DebugScreen_Image_ESP32Back,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DebugScreen_Image_ESP32Grey = lv_image_create(ui_Screen_DebugScreen);
    lv_image_set_src(ui_DebugScreen_Image_ESP32Grey, &ui_img_grey_png);
    lv_obj_set_width(ui_DebugScreen_Image_ESP32Grey, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_DebugScreen_Image_ESP32Grey, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_DebugScreen_Image_ESP32Grey, 880);
    lv_obj_set_y(ui_DebugScreen_Image_ESP32Grey, -15);
    lv_obj_set_align(ui_DebugScreen_Image_ESP32Grey, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DebugScreen_Image_ESP32Grey, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DebugScreen_Image_ESP32Grey,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DebugScreen_Image_ESP32Red = lv_image_create(ui_Screen_DebugScreen);
    lv_image_set_src(ui_DebugScreen_Image_ESP32Red, &ui_img_red_png);
    lv_obj_set_width(ui_DebugScreen_Image_ESP32Red, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_DebugScreen_Image_ESP32Red, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_DebugScreen_Image_ESP32Red, 880);
    lv_obj_set_y(ui_DebugScreen_Image_ESP32Red, -15);
    lv_obj_set_align(ui_DebugScreen_Image_ESP32Red, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DebugScreen_Image_ESP32Red, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DebugScreen_Image_ESP32Red,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DebugScreen_Image_SpeachBack = lv_image_create(ui_Screen_DebugScreen);
    lv_image_set_src(ui_DebugScreen_Image_SpeachBack, &ui_img_black_png);
    lv_obj_set_width(ui_DebugScreen_Image_SpeachBack, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_DebugScreen_Image_SpeachBack, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_DebugScreen_Image_SpeachBack, 880);
    lv_obj_set_y(ui_DebugScreen_Image_SpeachBack, 66);
    lv_obj_set_align(ui_DebugScreen_Image_SpeachBack, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DebugScreen_Image_SpeachBack, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DebugScreen_Image_SpeachBack,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DebugScreen_Image_SpeachGrey = lv_image_create(ui_Screen_DebugScreen);
    lv_image_set_src(ui_DebugScreen_Image_SpeachGrey, &ui_img_grey_png);
    lv_obj_set_width(ui_DebugScreen_Image_SpeachGrey, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_DebugScreen_Image_SpeachGrey, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_DebugScreen_Image_SpeachGrey, 880);
    lv_obj_set_y(ui_DebugScreen_Image_SpeachGrey, 66);
    lv_obj_set_align(ui_DebugScreen_Image_SpeachGrey, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DebugScreen_Image_SpeachGrey, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DebugScreen_Image_SpeachGrey,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DebugScreen_Image_SpeachRed = lv_image_create(ui_Screen_DebugScreen);
    lv_image_set_src(ui_DebugScreen_Image_SpeachRed, &ui_img_red_png);
    lv_obj_set_width(ui_DebugScreen_Image_SpeachRed, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_DebugScreen_Image_SpeachRed, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_DebugScreen_Image_SpeachRed, 880);
    lv_obj_set_y(ui_DebugScreen_Image_SpeachRed, 66);
    lv_obj_set_align(ui_DebugScreen_Image_SpeachRed, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DebugScreen_Image_SpeachRed, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DebugScreen_Image_SpeachRed,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DebugScreen_Image_StatBack = lv_image_create(ui_Screen_DebugScreen);
    lv_image_set_src(ui_DebugScreen_Image_StatBack, &ui_img_black_png);
    lv_obj_set_width(ui_DebugScreen_Image_StatBack, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_DebugScreen_Image_StatBack, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_DebugScreen_Image_StatBack, 880);
    lv_obj_set_y(ui_DebugScreen_Image_StatBack, 148);
    lv_obj_set_align(ui_DebugScreen_Image_StatBack, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DebugScreen_Image_StatBack, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DebugScreen_Image_StatBack,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DebugScreen_Image_StatGrey = lv_image_create(ui_Screen_DebugScreen);
    lv_image_set_src(ui_DebugScreen_Image_StatGrey, &ui_img_grey_png);
    lv_obj_set_width(ui_DebugScreen_Image_StatGrey, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_DebugScreen_Image_StatGrey, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_DebugScreen_Image_StatGrey, 880);
    lv_obj_set_y(ui_DebugScreen_Image_StatGrey, 148);
    lv_obj_set_align(ui_DebugScreen_Image_StatGrey, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DebugScreen_Image_StatGrey, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DebugScreen_Image_StatGrey,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DebugScreen_Image_StatRed = lv_image_create(ui_Screen_DebugScreen);
    lv_image_set_src(ui_DebugScreen_Image_StatRed, &ui_img_red_png);
    lv_obj_set_width(ui_DebugScreen_Image_StatRed, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_DebugScreen_Image_StatRed, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_DebugScreen_Image_StatRed, 880);
    lv_obj_set_y(ui_DebugScreen_Image_StatRed, 148);
    lv_obj_set_align(ui_DebugScreen_Image_StatRed, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DebugScreen_Image_StatRed, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DebugScreen_Image_StatRed,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DebugScreen_Image_PresetBack = lv_image_create(ui_Screen_DebugScreen);
    lv_image_set_src(ui_DebugScreen_Image_PresetBack, &ui_img_black_png);
    lv_obj_set_width(ui_DebugScreen_Image_PresetBack, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_DebugScreen_Image_PresetBack, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_DebugScreen_Image_PresetBack, 880);
    lv_obj_set_y(ui_DebugScreen_Image_PresetBack, 230);
    lv_obj_set_align(ui_DebugScreen_Image_PresetBack, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DebugScreen_Image_PresetBack, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DebugScreen_Image_PresetBack,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DebugScreen_Image_PresetGrey = lv_image_create(ui_Screen_DebugScreen);
    lv_image_set_src(ui_DebugScreen_Image_PresetGrey, &ui_img_grey_png);
    lv_obj_set_width(ui_DebugScreen_Image_PresetGrey, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_DebugScreen_Image_PresetGrey, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_DebugScreen_Image_PresetGrey, 880);
    lv_obj_set_y(ui_DebugScreen_Image_PresetGrey, 230);
    lv_obj_set_align(ui_DebugScreen_Image_PresetGrey, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DebugScreen_Image_PresetGrey, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DebugScreen_Image_PresetGrey,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DebugScreen_Image_PresetRed = lv_image_create(ui_Screen_DebugScreen);
    lv_image_set_src(ui_DebugScreen_Image_PresetRed, &ui_img_red_png);
    lv_obj_set_width(ui_DebugScreen_Image_PresetRed, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_DebugScreen_Image_PresetRed, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_DebugScreen_Image_PresetRed, 880);
    lv_obj_set_y(ui_DebugScreen_Image_PresetRed, 230);
    lv_obj_set_align(ui_DebugScreen_Image_PresetRed, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DebugScreen_Image_PresetRed, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DebugScreen_Image_PresetRed,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_DebugScreen_Label_Label16 = lv_label_create(ui_Screen_DebugScreen);
    lv_obj_set_width(ui_DebugScreen_Label_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DebugScreen_Label_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DebugScreen_Label_Label16, 690);
    lv_obj_set_y(ui_DebugScreen_Label_Label16, -183);
    lv_obj_set_align(ui_DebugScreen_Label_Label16, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DebugScreen_Label_Label16, "Карта памяти");
    lv_obj_remove_flag(ui_DebugScreen_Label_Label16,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DebugScreen_Label_Label16, lv_color_hex(0x00CA41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DebugScreen_Label_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DebugScreen_Label_Label16, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DebugScreen_Label_Label17 = lv_label_create(ui_Screen_DebugScreen);
    lv_obj_set_width(ui_DebugScreen_Label_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DebugScreen_Label_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DebugScreen_Label_Label17, 690);
    lv_obj_set_y(ui_DebugScreen_Label_Label17, -97);
    lv_obj_set_align(ui_DebugScreen_Label_Label17, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DebugScreen_Label_Label17, "Ардуино");
    lv_obj_remove_flag(ui_DebugScreen_Label_Label17,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DebugScreen_Label_Label17, lv_color_hex(0x00CA41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DebugScreen_Label_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DebugScreen_Label_Label17, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DebugScreen_Label_Label18 = lv_label_create(ui_Screen_DebugScreen);
    lv_obj_set_width(ui_DebugScreen_Label_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DebugScreen_Label_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DebugScreen_Label_Label18, 690);
    lv_obj_set_y(ui_DebugScreen_Label_Label18, -15);
    lv_obj_set_align(ui_DebugScreen_Label_Label18, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DebugScreen_Label_Label18, "ESP32");
    lv_obj_remove_flag(ui_DebugScreen_Label_Label18,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DebugScreen_Label_Label18, lv_color_hex(0x00CA41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DebugScreen_Label_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DebugScreen_Label_Label18, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DebugScreen_Label_Label19 = lv_label_create(ui_Screen_DebugScreen);
    lv_obj_set_width(ui_DebugScreen_Label_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DebugScreen_Label_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DebugScreen_Label_Label19, 690);
    lv_obj_set_y(ui_DebugScreen_Label_Label19, 67);
    lv_obj_set_align(ui_DebugScreen_Label_Label19, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DebugScreen_Label_Label19, "Реплики");
    lv_obj_remove_flag(ui_DebugScreen_Label_Label19,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DebugScreen_Label_Label19, lv_color_hex(0x00CA41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DebugScreen_Label_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DebugScreen_Label_Label19, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DebugScreen_Label_Label20 = lv_label_create(ui_Screen_DebugScreen);
    lv_obj_set_width(ui_DebugScreen_Label_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DebugScreen_Label_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DebugScreen_Label_Label20, 690);
    lv_obj_set_y(ui_DebugScreen_Label_Label20, 149);
    lv_obj_set_align(ui_DebugScreen_Label_Label20, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DebugScreen_Label_Label20, "Статистика");
    lv_obj_remove_flag(ui_DebugScreen_Label_Label20,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DebugScreen_Label_Label20, lv_color_hex(0x00CA41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DebugScreen_Label_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DebugScreen_Label_Label20, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DebugScreen_Label_Label21 = lv_label_create(ui_Screen_DebugScreen);
    lv_obj_set_width(ui_DebugScreen_Label_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DebugScreen_Label_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DebugScreen_Label_Label21, 690);
    lv_obj_set_y(ui_DebugScreen_Label_Label21, 233);
    lv_obj_set_align(ui_DebugScreen_Label_Label21, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DebugScreen_Label_Label21, "Пресеты");
    lv_obj_remove_flag(ui_DebugScreen_Label_Label21,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DebugScreen_Label_Label21, lv_color_hex(0x00CA41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DebugScreen_Label_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DebugScreen_Label_Label21, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_DebugScreen_Label_Label, ui_event_DebugScreen_Label_Label, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugScreen_Textarea_TextAreaScreen, ui_event_DebugScreen_Textarea_TextAreaScreen, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_DebugScreen_Image_SDBack, ui_event_DebugScreen_Image_SDBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugScreen_Image_SDGrey, ui_event_DebugScreen_Image_SDGrey, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugScreen_Image_SDRed, ui_event_DebugScreen_Image_SDRed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugScreen_Image_ArduinoBack, ui_event_DebugScreen_Image_ArduinoBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugScreen_Image_ArduinoGrey, ui_event_DebugScreen_Image_ArduinoGrey, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugScreen_Image_ArduinoRed, ui_event_DebugScreen_Image_ArduinoRed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugScreen_Image_ESP32Back, ui_event_DebugScreen_Image_ESP32Back, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugScreen_Image_ESP32Grey, ui_event_DebugScreen_Image_ESP32Grey, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugScreen_Image_ESP32Red, ui_event_DebugScreen_Image_ESP32Red, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugScreen_Image_SpeachBack, ui_event_DebugScreen_Image_SpeachBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugScreen_Image_SpeachGrey, ui_event_DebugScreen_Image_SpeachGrey, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugScreen_Image_SpeachRed, ui_event_DebugScreen_Image_SpeachRed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugScreen_Image_StatBack, ui_event_DebugScreen_Image_StatBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugScreen_Image_StatGrey, ui_event_DebugScreen_Image_StatGrey, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugScreen_Image_StatRed, ui_event_DebugScreen_Image_StatRed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugScreen_Image_PresetBack, ui_event_DebugScreen_Image_PresetBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugScreen_Image_PresetGrey, ui_event_DebugScreen_Image_PresetGrey, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugScreen_Image_PresetRed, ui_event_DebugScreen_Image_PresetRed, LV_EVENT_ALL, NULL);

}

void ui_Screen_DebugScreen_screen_destroy(void)
{
    if(ui_Screen_DebugScreen) lv_obj_del(ui_Screen_DebugScreen);

    // NULL screen variables
    ui_Screen_DebugScreen = NULL;
    ui_DebugScreen_Label_Label = NULL;
    ui_DebugScreen_Textarea_TextAreaScreen = NULL;
    ui_DebugScreen_Image_SDBack = NULL;
    ui_DebugScreen_Image_SDGrey = NULL;
    ui_DebugScreen_Image_SDRed = NULL;
    ui_DebugScreen_Image_ArduinoBack = NULL;
    ui_DebugScreen_Image_ArduinoGrey = NULL;
    ui_DebugScreen_Image_ArduinoRed = NULL;
    ui_DebugScreen_Image_ESP32Back = NULL;
    ui_DebugScreen_Image_ESP32Grey = NULL;
    ui_DebugScreen_Image_ESP32Red = NULL;
    ui_DebugScreen_Image_SpeachBack = NULL;
    ui_DebugScreen_Image_SpeachGrey = NULL;
    ui_DebugScreen_Image_SpeachRed = NULL;
    ui_DebugScreen_Image_StatBack = NULL;
    ui_DebugScreen_Image_StatGrey = NULL;
    ui_DebugScreen_Image_StatRed = NULL;
    ui_DebugScreen_Image_PresetBack = NULL;
    ui_DebugScreen_Image_PresetGrey = NULL;
    ui_DebugScreen_Image_PresetRed = NULL;
    ui_DebugScreen_Label_Label16 = NULL;
    ui_DebugScreen_Label_Label17 = NULL;
    ui_DebugScreen_Label_Label18 = NULL;
    ui_DebugScreen_Label_Label19 = NULL;
    ui_DebugScreen_Label_Label20 = NULL;
    ui_DebugScreen_Label_Label21 = NULL;

}
