// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Fiona_Project

#include "../ui.h"

lv_obj_t * ui_Screen_Setting = NULL;
lv_obj_t * ui_Setting_Label_Label4 = NULL;
lv_obj_t * ui_Setting_Label_TimeLbl = NULL;
lv_obj_t * ui_Setting_Textarea_TimeTextArea = NULL;
lv_obj_t * ui_Setting_Label_SaveBtn = NULL;
lv_obj_t * ui_Setting_Label_TimeApply = NULL;
lv_obj_t * ui_Setting_Label_TimeAsk = NULL;
lv_obj_t * ui_Setting_Label_LightLbl2 = NULL;
lv_obj_t * ui_Setting_Label_LightMarkLbl2 = NULL;
lv_obj_t * ui_Setting_Label_DarkMarkLbl2 = NULL;
lv_obj_t * ui_Setting_Slider_SliderLight = NULL;
lv_obj_t * ui_Setting_Slider_SliderDark = NULL;
lv_obj_t * ui_Setting_Slider_SliderBridges = NULL;
lv_obj_t * ui_Setting_Label_CalibrateMCU = NULL;
lv_obj_t * ui_Setting_Label_FanPlus = NULL;
lv_obj_t * ui_Setting_Label_FanMinus = NULL;
lv_obj_t * ui_Setting_Label_FanApply = NULL;
lv_obj_t * ui_Setting_Label_FanDefault = NULL;
lv_obj_t * ui_Setting_Label_FanCalibLbl = NULL;
lv_obj_t * ui_Setting_Dropdown_DropdownFanDot = NULL;
lv_obj_t * ui_Setting_Label_KalibLabel = NULL;
lv_obj_t * ui_Setting_Dropdown_UartDevice = NULL;
lv_obj_t * ui_Setting_Dropdown_SpeedUart = NULL;
lv_obj_t * ui_Setting_Dropdown_RXList = NULL;
lv_obj_t * ui_Setting_Dropdown_TXList = NULL;
lv_obj_t * ui_Setting_Label_RXLabel = NULL;
lv_obj_t * ui_Setting_Label_TXLabel = NULL;
lv_obj_t * ui_Setting_Textarea_TextAreaUartLog = NULL;
// event funtions
void ui_event_Setting_Label_Label4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ToHomeClick(e);
    }
}

void ui_event_Setting_Textarea_TimeTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        TimeOnFocus(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        TimeOnDeFocus(e);
    }
}

void ui_event_Setting_Label_SaveBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnSaveClick(e);
    }
}

void ui_event_Setting_Label_TimeApply(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnTimeApply(e);
    }
}

void ui_event_Setting_Label_TimeAsk(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnTimeAsk(e);
    }
}

void ui_event_Setting_Slider_SliderLight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnLightSliderThresholdChanged(e);
    }
}

void ui_event_Setting_Slider_SliderDark(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnSliderThresholdChanged(e);
    }
}

void ui_event_Setting_Slider_SliderBridges(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnLightSliderChanged(e);
    }
}

void ui_event_Setting_Label_CalibrateMCU(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CalibrateMCUBtnClick(e);
        _ui_screen_change(&ui_Screen_DashBoard, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen_DashBoard_screen_init);
    }
}

void ui_event_Setting_Label_FanPlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        FanPlusClk(e);
    }
}

void ui_event_Setting_Label_FanMinus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        FanMinusClk(e);
    }
}

void ui_event_Setting_Label_FanApply(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        FanSaveApply(e);
    }
}

void ui_event_Setting_Label_FanDefault(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        FanDefaultClick(e);
    }
}

void ui_event_Setting_Dropdown_DropdownFanDot(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        FanChangeDot(e);
    }
}

void ui_event_Setting_Dropdown_UartDevice(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        DeviceChange(e);
    }
}

void ui_event_Setting_Dropdown_SpeedUart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SpeedChange(e);
    }
}

void ui_event_Setting_Dropdown_RXList(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        RXChangeDot(e);
    }
}

void ui_event_Setting_Dropdown_TXList(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        TXChangeDot(e);
    }
}

void ui_event_Setting_Textarea_TextAreaUartLog(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnTestScreenUart(e);
    }
}

// build funtions

void ui_Screen_Setting_screen_init(void)
{
    ui_Screen_Setting = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Setting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Screen_Setting, &ui_img_global_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Label_Label4 = lv_label_create(ui_Screen_Setting);
    lv_obj_set_width(ui_Setting_Label_Label4, 400);
    lv_obj_set_height(ui_Setting_Label_Label4, 30);
    lv_obj_set_x(ui_Setting_Label_Label4, 0);
    lv_obj_set_y(ui_Setting_Label_Label4, 10);
    lv_obj_set_align(ui_Setting_Label_Label4, LV_ALIGN_TOP_MID);
    lv_obj_set_ext_click_area(ui_Setting_Label_Label4, 20);
    lv_label_set_long_mode(ui_Setting_Label_Label4, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Setting_Label_Label4, "Домой...");
    lv_obj_add_flag(ui_Setting_Label_Label4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Setting_Label_Label4,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Setting_Label_Label4, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Label_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Setting_Label_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Setting_Label_Label4, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Label_Label4, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Label_TimeLbl = lv_label_create(ui_Screen_Setting);
    lv_obj_set_width(ui_Setting_Label_TimeLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Setting_Label_TimeLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Label_TimeLbl, 34);
    lv_obj_set_y(ui_Setting_Label_TimeLbl, 77);
    lv_label_set_text(ui_Setting_Label_TimeLbl, "Текущее время:");
    lv_obj_set_style_text_color(ui_Setting_Label_TimeLbl, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Label_TimeLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Label_TimeLbl, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Textarea_TimeTextArea = lv_textarea_create(ui_Screen_Setting);
    lv_obj_set_width(ui_Setting_Textarea_TimeTextArea, 153);
    lv_obj_set_height(ui_Setting_Textarea_TimeTextArea, 52);
    lv_obj_set_x(ui_Setting_Textarea_TimeTextArea, 258);
    lv_obj_set_y(ui_Setting_Textarea_TimeTextArea, 68);
    lv_textarea_set_max_length(ui_Setting_Textarea_TimeTextArea, 8);
    lv_textarea_set_placeholder_text(ui_Setting_Textarea_TimeTextArea, "00.00.00");
    lv_obj_set_style_text_align(ui_Setting_Textarea_TimeTextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Textarea_TimeTextArea, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Label_SaveBtn = lv_label_create(ui_Screen_Setting);
    lv_obj_set_width(ui_Setting_Label_SaveBtn, 207);
    lv_obj_set_height(ui_Setting_Label_SaveBtn, 35);
    lv_obj_set_x(ui_Setting_Label_SaveBtn, 370);
    lv_obj_set_y(ui_Setting_Label_SaveBtn, -36);
    lv_obj_set_align(ui_Setting_Label_SaveBtn, LV_ALIGN_BOTTOM_MID);
    lv_label_set_long_mode(ui_Setting_Label_SaveBtn, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Setting_Label_SaveBtn, "Сохранить");
    lv_obj_add_flag(ui_Setting_Label_SaveBtn, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Setting_Label_SaveBtn, lv_color_hex(0x18187B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Label_SaveBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Setting_Label_SaveBtn, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Setting_Label_SaveBtn, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Label_SaveBtn, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Setting_Label_SaveBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Setting_Label_SaveBtn, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_Label_SaveBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Label_TimeApply = lv_label_create(ui_Screen_Setting);
    lv_obj_set_width(ui_Setting_Label_TimeApply, 235);
    lv_obj_set_height(ui_Setting_Label_TimeApply, 35);
    lv_obj_set_x(ui_Setting_Label_TimeApply, 443);
    lv_obj_set_y(ui_Setting_Label_TimeApply, 79);
    lv_label_set_long_mode(ui_Setting_Label_TimeApply, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Setting_Label_TimeApply, "Применить");
    lv_obj_add_flag(ui_Setting_Label_TimeApply, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Setting_Label_TimeApply, lv_color_hex(0x18187B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Label_TimeApply, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Setting_Label_TimeApply, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Setting_Label_TimeApply, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Label_TimeApply, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Setting_Label_TimeApply, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Setting_Label_TimeApply, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_Label_TimeApply, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Label_TimeAsk = lv_label_create(ui_Screen_Setting);
    lv_obj_set_width(ui_Setting_Label_TimeAsk, 235);
    lv_obj_set_height(ui_Setting_Label_TimeAsk, 35);
    lv_obj_set_x(ui_Setting_Label_TimeAsk, 710);
    lv_obj_set_y(ui_Setting_Label_TimeAsk, 75);
    lv_label_set_long_mode(ui_Setting_Label_TimeAsk, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Setting_Label_TimeAsk, "Запросить");
    lv_obj_add_flag(ui_Setting_Label_TimeAsk, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Setting_Label_TimeAsk, lv_color_hex(0x18187B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Label_TimeAsk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Setting_Label_TimeAsk, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Setting_Label_TimeAsk, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Label_TimeAsk, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Setting_Label_TimeAsk, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Setting_Label_TimeAsk, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_Label_TimeAsk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Label_LightLbl2 = lv_label_create(ui_Screen_Setting);
    lv_obj_set_width(ui_Setting_Label_LightLbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Setting_Label_LightLbl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Label_LightLbl2, 36);
    lv_obj_set_y(ui_Setting_Label_LightLbl2, 167);
    lv_label_set_text(ui_Setting_Label_LightLbl2, "Яркость: 222");
    lv_obj_set_style_text_color(ui_Setting_Label_LightLbl2, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Label_LightLbl2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Label_LightLbl2, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Label_LightMarkLbl2 = lv_label_create(ui_Screen_Setting);
    lv_obj_set_width(ui_Setting_Label_LightMarkLbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Setting_Label_LightMarkLbl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Label_LightMarkLbl2, 40);
    lv_obj_set_y(ui_Setting_Label_LightMarkLbl2, 213);
    lv_label_set_text(ui_Setting_Label_LightMarkLbl2, "Светло: 245");
    lv_obj_set_style_text_color(ui_Setting_Label_LightMarkLbl2, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Label_LightMarkLbl2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Label_LightMarkLbl2, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Label_DarkMarkLbl2 = lv_label_create(ui_Screen_Setting);
    lv_obj_set_width(ui_Setting_Label_DarkMarkLbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Setting_Label_DarkMarkLbl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Label_DarkMarkLbl2, 522);
    lv_obj_set_y(ui_Setting_Label_DarkMarkLbl2, 216);
    lv_label_set_text(ui_Setting_Label_DarkMarkLbl2, "Темно: 025");
    lv_obj_set_style_text_color(ui_Setting_Label_DarkMarkLbl2, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Label_DarkMarkLbl2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Label_DarkMarkLbl2, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Slider_SliderLight = lv_slider_create(ui_Screen_Setting);
    lv_slider_set_range(ui_Setting_Slider_SliderLight, 0, 4095);
    lv_slider_set_value(ui_Setting_Slider_SliderLight, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Setting_Slider_SliderLight) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_Setting_Slider_SliderLight, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Setting_Slider_SliderLight, 242);
    lv_obj_set_height(ui_Setting_Slider_SliderLight, 25);
    lv_obj_set_x(ui_Setting_Slider_SliderLight, -143);
    lv_obj_set_y(ui_Setting_Slider_SliderLight, -69);
    lv_obj_set_align(ui_Setting_Slider_SliderLight, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Setting_Slider_SliderLight,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Setting_Slider_SliderLight,
                                                                                  lv_obj_get_style_pad_right(ui_Setting_Slider_SliderLight, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Setting_Slider_SliderDark = lv_slider_create(ui_Screen_Setting);
    lv_slider_set_range(ui_Setting_Slider_SliderDark, 0, 4095);
    lv_slider_set_value(ui_Setting_Slider_SliderDark, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Setting_Slider_SliderDark) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_Setting_Slider_SliderDark, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Setting_Slider_SliderDark, 260);
    lv_obj_set_height(ui_Setting_Slider_SliderDark, 25);
    lv_obj_set_x(ui_Setting_Slider_SliderDark, 317);
    lv_obj_set_y(ui_Setting_Slider_SliderDark, -68);
    lv_obj_set_align(ui_Setting_Slider_SliderDark, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Setting_Slider_SliderDark,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Setting_Slider_SliderDark,
                                                                                  lv_obj_get_style_pad_right(ui_Setting_Slider_SliderDark, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Setting_Slider_SliderBridges = lv_slider_create(ui_Screen_Setting);
    lv_slider_set_value(ui_Setting_Slider_SliderBridges, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Setting_Slider_SliderBridges) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_Setting_Slider_SliderBridges, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Setting_Slider_SliderBridges, 366);
    lv_obj_set_height(ui_Setting_Slider_SliderBridges, 25);
    lv_obj_set_x(ui_Setting_Slider_SliderBridges, -79);
    lv_obj_set_y(ui_Setting_Slider_SliderBridges, -115);
    lv_obj_set_align(ui_Setting_Slider_SliderBridges, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Setting_Slider_SliderBridges,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Setting_Slider_SliderBridges,
                                                                                  lv_obj_get_style_pad_right(ui_Setting_Slider_SliderBridges, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Setting_Label_CalibrateMCU = lv_label_create(ui_Screen_Setting);
    lv_obj_set_width(ui_Setting_Label_CalibrateMCU, 713);
    lv_obj_set_height(ui_Setting_Label_CalibrateMCU, 35);
    lv_obj_set_x(ui_Setting_Label_CalibrateMCU, -116);
    lv_obj_set_y(ui_Setting_Label_CalibrateMCU, -34);
    lv_obj_set_align(ui_Setting_Label_CalibrateMCU, LV_ALIGN_BOTTOM_MID);
    lv_label_set_long_mode(ui_Setting_Label_CalibrateMCU, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Setting_Label_CalibrateMCU, "Калибровать аксклерометр");
    lv_obj_add_flag(ui_Setting_Label_CalibrateMCU, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Setting_Label_CalibrateMCU, lv_color_hex(0x18187B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Label_CalibrateMCU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Setting_Label_CalibrateMCU, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Setting_Label_CalibrateMCU, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Label_CalibrateMCU, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Setting_Label_CalibrateMCU, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Setting_Label_CalibrateMCU, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_Label_CalibrateMCU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Label_FanPlus = lv_label_create(ui_Screen_Setting);
    lv_obj_set_width(ui_Setting_Label_FanPlus, LV_SIZE_CONTENT);   /// 235
    lv_obj_set_height(ui_Setting_Label_FanPlus, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_Setting_Label_FanPlus, 412);
    lv_obj_set_y(ui_Setting_Label_FanPlus, 263);
    lv_label_set_long_mode(ui_Setting_Label_FanPlus, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Setting_Label_FanPlus, ">>>");
    lv_obj_add_flag(ui_Setting_Label_FanPlus, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Setting_Label_FanPlus, lv_color_hex(0x18187B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Label_FanPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Setting_Label_FanPlus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Setting_Label_FanPlus, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Label_FanPlus, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Setting_Label_FanPlus, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Setting_Label_FanPlus, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_Label_FanPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Label_FanMinus = lv_label_create(ui_Screen_Setting);
    lv_obj_set_width(ui_Setting_Label_FanMinus, LV_SIZE_CONTENT);   /// 235
    lv_obj_set_height(ui_Setting_Label_FanMinus, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_Setting_Label_FanMinus, 287);
    lv_obj_set_y(ui_Setting_Label_FanMinus, 263);
    lv_label_set_long_mode(ui_Setting_Label_FanMinus, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Setting_Label_FanMinus, "<<<");
    lv_obj_add_flag(ui_Setting_Label_FanMinus, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Setting_Label_FanMinus, lv_color_hex(0x18187B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Label_FanMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Setting_Label_FanMinus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Setting_Label_FanMinus, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Label_FanMinus, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Setting_Label_FanMinus, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Setting_Label_FanMinus, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_Label_FanMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Label_FanApply = lv_label_create(ui_Screen_Setting);
    lv_obj_set_width(ui_Setting_Label_FanApply, LV_SIZE_CONTENT);   /// 235
    lv_obj_set_height(ui_Setting_Label_FanApply, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_Setting_Label_FanApply, 37);
    lv_obj_set_y(ui_Setting_Label_FanApply, 313);
    lv_label_set_long_mode(ui_Setting_Label_FanApply, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Setting_Label_FanApply, " Применить ");
    lv_obj_add_flag(ui_Setting_Label_FanApply, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Setting_Label_FanApply, lv_color_hex(0x18187B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Label_FanApply, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Setting_Label_FanApply, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Setting_Label_FanApply, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Label_FanApply, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Setting_Label_FanApply, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Setting_Label_FanApply, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_Label_FanApply, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Label_FanDefault = lv_label_create(ui_Screen_Setting);
    lv_obj_set_width(ui_Setting_Label_FanDefault, LV_SIZE_CONTENT);   /// 235
    lv_obj_set_height(ui_Setting_Label_FanDefault, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_Setting_Label_FanDefault, 285);
    lv_obj_set_y(ui_Setting_Label_FanDefault, 312);
    lv_label_set_long_mode(ui_Setting_Label_FanDefault, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Setting_Label_FanDefault, " Умолчения ");
    lv_obj_add_flag(ui_Setting_Label_FanDefault, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Setting_Label_FanDefault,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Setting_Label_FanDefault, lv_color_hex(0x18187B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Label_FanDefault, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Setting_Label_FanDefault, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Setting_Label_FanDefault, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Label_FanDefault, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Setting_Label_FanDefault, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Setting_Label_FanDefault, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_Label_FanDefault, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Label_FanCalibLbl = lv_label_create(ui_Screen_Setting);
    lv_obj_set_width(ui_Setting_Label_FanCalibLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Setting_Label_FanCalibLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Label_FanCalibLbl, 344);
    lv_obj_set_y(ui_Setting_Label_FanCalibLbl, 264);
    lv_label_set_text(ui_Setting_Label_FanCalibLbl, "128");
    lv_obj_set_style_text_color(ui_Setting_Label_FanCalibLbl, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Label_FanCalibLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Label_FanCalibLbl, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Dropdown_DropdownFanDot = lv_dropdown_create(ui_Screen_Setting);
    lv_dropdown_set_options(ui_Setting_Dropdown_DropdownFanDot,
                            "Радиатор - Точка старта\nРадиатор - Точка остановки\nРадиатор - Точка ВЧ\nРадиатор - Точка аэродинамики\nПечка - Точка старта\nПечка - Точка остановки\nПечка - Точка ВЧ\nПечка - Точка аэродинамики");
    lv_obj_set_width(ui_Setting_Dropdown_DropdownFanDot, 238);
    lv_obj_set_height(ui_Setting_Dropdown_DropdownFanDot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Dropdown_DropdownFanDot, 34);
    lv_obj_set_y(ui_Setting_Dropdown_DropdownFanDot, 257);
    lv_obj_add_flag(ui_Setting_Dropdown_DropdownFanDot, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Setting_Dropdown_DropdownFanDot, &ui_font_BaseFont20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Setting_Dropdown_DropdownFanDot, &lv_font_montserrat_14,
                               LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Setting_Dropdown_DropdownFanDot), &ui_font_BaseFont20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Setting_Dropdown_DropdownFanDot), &ui_font_BaseFont20,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Setting_Label_KalibLabel = lv_label_create(ui_Screen_Setting);
    lv_obj_set_width(ui_Setting_Label_KalibLabel, 940);
    lv_obj_set_height(ui_Setting_Label_KalibLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Label_KalibLabel, 40);
    lv_obj_set_y(ui_Setting_Label_KalibLabel, 485);
    lv_label_set_text(ui_Setting_Label_KalibLabel, "Этапы калибровки");
    lv_obj_set_style_text_color(ui_Setting_Label_KalibLabel, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Label_KalibLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Label_KalibLabel, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Dropdown_UartDevice = lv_dropdown_create(ui_Screen_Setting);
    lv_dropdown_set_options(ui_Setting_Dropdown_UartDevice, "Arduino\nESP32\nGPS");
    lv_obj_set_width(ui_Setting_Dropdown_UartDevice, 163);
    lv_obj_set_height(ui_Setting_Dropdown_UartDevice, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Dropdown_UartDevice, 34);
    lv_obj_set_y(ui_Setting_Dropdown_UartDevice, 366);
    lv_obj_add_flag(ui_Setting_Dropdown_UartDevice, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Setting_Dropdown_UartDevice, &ui_font_BaseFont20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Setting_Dropdown_UartDevice, &lv_font_montserrat_14,
                               LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Setting_Dropdown_UartDevice), &ui_font_BaseFont20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Setting_Dropdown_UartDevice), &ui_font_BaseFont20,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Setting_Dropdown_SpeedUart = lv_dropdown_create(ui_Screen_Setting);
    lv_dropdown_set_options(ui_Setting_Dropdown_SpeedUart, "9600\n115200\n921600");
    lv_obj_set_width(ui_Setting_Dropdown_SpeedUart, 161);
    lv_obj_set_height(ui_Setting_Dropdown_SpeedUart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Dropdown_SpeedUart, 36);
    lv_obj_set_y(ui_Setting_Dropdown_SpeedUart, 428);
    lv_obj_add_flag(ui_Setting_Dropdown_SpeedUart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Setting_Dropdown_SpeedUart, &ui_font_BaseFont20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Setting_Dropdown_SpeedUart, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Setting_Dropdown_SpeedUart), &ui_font_BaseFont20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Setting_Dropdown_SpeedUart), &ui_font_BaseFont20,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Setting_Dropdown_RXList = lv_dropdown_create(ui_Screen_Setting);
    lv_dropdown_set_options(ui_Setting_Dropdown_RXList, "1\n2\n3\n4\n5\n26\n27\n32\n33\n37\n38\n45\n46\n47");
    lv_obj_set_width(ui_Setting_Dropdown_RXList, 115);
    lv_obj_set_height(ui_Setting_Dropdown_RXList, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Dropdown_RXList, 340);
    lv_obj_set_y(ui_Setting_Dropdown_RXList, 366);
    lv_obj_add_flag(ui_Setting_Dropdown_RXList, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Setting_Dropdown_RXList, &ui_font_BaseFont20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Setting_Dropdown_RXList, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Setting_Dropdown_RXList), &ui_font_BaseFont20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Setting_Dropdown_RXList), &ui_font_BaseFont20,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Setting_Dropdown_TXList = lv_dropdown_create(ui_Screen_Setting);
    lv_dropdown_set_options(ui_Setting_Dropdown_TXList, "1\n2\n3\n4\n5\n26\n27\n32\n33\n37\n38\n45\n46\n47");
    lv_obj_set_width(ui_Setting_Dropdown_TXList, 115);
    lv_obj_set_height(ui_Setting_Dropdown_TXList, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Dropdown_TXList, 340);
    lv_obj_set_y(ui_Setting_Dropdown_TXList, 428);
    lv_obj_add_flag(ui_Setting_Dropdown_TXList, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Setting_Dropdown_TXList, &ui_font_BaseFont20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Setting_Dropdown_TXList, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Setting_Dropdown_TXList), &ui_font_BaseFont20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Setting_Dropdown_TXList), &ui_font_BaseFont20,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Setting_Label_RXLabel = lv_label_create(ui_Screen_Setting);
    lv_obj_set_width(ui_Setting_Label_RXLabel, LV_SIZE_CONTENT);   /// 940
    lv_obj_set_height(ui_Setting_Label_RXLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Label_RXLabel, 280);
    lv_obj_set_y(ui_Setting_Label_RXLabel, 372);
    lv_label_set_text(ui_Setting_Label_RXLabel, "RX");
    lv_obj_set_style_text_color(ui_Setting_Label_RXLabel, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Label_RXLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Label_RXLabel, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Label_TXLabel = lv_label_create(ui_Screen_Setting);
    lv_obj_set_width(ui_Setting_Label_TXLabel, LV_SIZE_CONTENT);   /// 940
    lv_obj_set_height(ui_Setting_Label_TXLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Label_TXLabel, 280);
    lv_obj_set_y(ui_Setting_Label_TXLabel, 439);
    lv_label_set_text(ui_Setting_Label_TXLabel, "TX");
    lv_obj_set_style_text_color(ui_Setting_Label_TXLabel, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Label_TXLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Label_TXLabel, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Textarea_TextAreaUartLog = lv_textarea_create(ui_Screen_Setting);
    lv_obj_set_width(ui_Setting_Textarea_TextAreaUartLog, 513);
    lv_obj_set_height(ui_Setting_Textarea_TextAreaUartLog, 225);
    lv_obj_set_x(ui_Setting_Textarea_TextAreaUartLog, 472);
    lv_obj_set_y(ui_Setting_Textarea_TextAreaUartLog, 257);
    lv_textarea_set_text(ui_Setting_Textarea_TextAreaUartLog, "Данные системы.\n");
    lv_textarea_set_placeholder_text(ui_Setting_Textarea_TextAreaUartLog, "Placeholder...");
    lv_obj_remove_flag(ui_Setting_Textarea_TextAreaUartLog,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Setting_Textarea_TextAreaUartLog, lv_color_hex(0x01C840),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Textarea_TextAreaUartLog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Textarea_TextAreaUartLog, &ui_font_BaseFont16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Setting_Textarea_TextAreaUartLog, lv_color_hex(0x000810), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_Textarea_TextAreaUartLog, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Setting_Label_Label4, ui_event_Setting_Label_Label4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Textarea_TimeTextArea, ui_event_Setting_Textarea_TimeTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Label_SaveBtn, ui_event_Setting_Label_SaveBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Label_TimeApply, ui_event_Setting_Label_TimeApply, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Label_TimeAsk, ui_event_Setting_Label_TimeAsk, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Slider_SliderLight, ui_event_Setting_Slider_SliderLight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Slider_SliderDark, ui_event_Setting_Slider_SliderDark, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Slider_SliderBridges, ui_event_Setting_Slider_SliderBridges, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Label_CalibrateMCU, ui_event_Setting_Label_CalibrateMCU, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Label_FanPlus, ui_event_Setting_Label_FanPlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Label_FanMinus, ui_event_Setting_Label_FanMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Label_FanApply, ui_event_Setting_Label_FanApply, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Label_FanDefault, ui_event_Setting_Label_FanDefault, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Dropdown_DropdownFanDot, ui_event_Setting_Dropdown_DropdownFanDot, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Dropdown_UartDevice, ui_event_Setting_Dropdown_UartDevice, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Dropdown_SpeedUart, ui_event_Setting_Dropdown_SpeedUart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Dropdown_RXList, ui_event_Setting_Dropdown_RXList, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Dropdown_TXList, ui_event_Setting_Dropdown_TXList, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Textarea_TextAreaUartLog, ui_event_Setting_Textarea_TextAreaUartLog, LV_EVENT_ALL, NULL);

}

void ui_Screen_Setting_screen_destroy(void)
{
    if(ui_Screen_Setting) lv_obj_del(ui_Screen_Setting);

    // NULL screen variables
    ui_Screen_Setting = NULL;
    ui_Setting_Label_Label4 = NULL;
    ui_Setting_Label_TimeLbl = NULL;
    ui_Setting_Textarea_TimeTextArea = NULL;
    ui_Setting_Label_SaveBtn = NULL;
    ui_Setting_Label_TimeApply = NULL;
    ui_Setting_Label_TimeAsk = NULL;
    ui_Setting_Label_LightLbl2 = NULL;
    ui_Setting_Label_LightMarkLbl2 = NULL;
    ui_Setting_Label_DarkMarkLbl2 = NULL;
    ui_Setting_Slider_SliderLight = NULL;
    ui_Setting_Slider_SliderDark = NULL;
    ui_Setting_Slider_SliderBridges = NULL;
    ui_Setting_Label_CalibrateMCU = NULL;
    ui_Setting_Label_FanPlus = NULL;
    ui_Setting_Label_FanMinus = NULL;
    ui_Setting_Label_FanApply = NULL;
    ui_Setting_Label_FanDefault = NULL;
    ui_Setting_Label_FanCalibLbl = NULL;
    ui_Setting_Dropdown_DropdownFanDot = NULL;
    ui_Setting_Label_KalibLabel = NULL;
    ui_Setting_Dropdown_UartDevice = NULL;
    ui_Setting_Dropdown_SpeedUart = NULL;
    ui_Setting_Dropdown_RXList = NULL;
    ui_Setting_Dropdown_TXList = NULL;
    ui_Setting_Label_RXLabel = NULL;
    ui_Setting_Label_TXLabel = NULL;
    ui_Setting_Textarea_TextAreaUartLog = NULL;

}
