// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Fiona_Project

#ifndef UI_SCREEN_DASHBOARD_H
#define UI_SCREEN_DASHBOARD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_DashBoard
extern void ui_Screen_DashBoard_screen_init(void);
extern void ui_Screen_DashBoard_screen_destroy(void);
extern void ui_event_Screen_DashBoard(lv_event_t * e);
extern lv_obj_t * ui_Screen_DashBoard;
extern lv_obj_t * ui_DashBoard_Image_Backgrownd;
extern lv_obj_t * ui_DashBoard_Label_FionaSpeachLabelDash;
extern lv_obj_t * ui_DashBoard_Label_TahoLBL;
extern lv_obj_t * ui_DashBoard_Arc_Taho;
extern lv_obj_t * ui_DashBoard_Image_BlueRing;
extern lv_obj_t * ui_DashBoard_Bar_BatBar;
extern lv_obj_t * ui_DashBoard_Image_BatShape;
extern lv_obj_t * ui_DashBoard_Image_Batallert;
extern lv_obj_t * ui_DashBoard_Image_BatHL;
extern lv_obj_t * ui_DashBoard_Bar_FuelBar;
extern lv_obj_t * ui_DashBoard_Image_FuelShape;
extern lv_obj_t * ui_DashBoard_Image_FuelNorm;
extern lv_obj_t * ui_DashBoard_Image_FuelAllert;
extern lv_obj_t * ui_DashBoard_Bar_TempBar;
extern lv_obj_t * ui_DashBoard_Image_CoolShape;
extern lv_obj_t * ui_DashBoard_Image_CoolNorm;
extern lv_obj_t * ui_DashBoard_Image_CoolHigh;
extern lv_obj_t * ui_DashBoard_Arc_Drossel;
extern lv_obj_t * ui_DashBoard_Arc_Uskorenie;
extern lv_obj_t * ui_DashBoard_Label_GazBL;
extern lv_obj_t * ui_DashBoard_Label_AxelBL;
extern lv_obj_t * ui_DashBoard_Label_AKB;
extern lv_obj_t * ui_DashBoard_Label_FUEL;
extern lv_obj_t * ui_DashBoard_Label_ODO;
extern lv_obj_t * ui_DashBoard_Label_TempNum;
extern lv_obj_t * ui_DashBoard_Image_TripImg;
extern lv_obj_t * ui_DashBoard_Label_TripNum;
extern lv_obj_t * ui_DashBoard_Label_TripTime;
extern lv_obj_t * ui_DashBoard_Label_TripTimePause;
extern lv_obj_t * ui_DashBoard_Label_TripLitr;
extern void ui_event_DashBoard_Label_Time(lv_event_t * e);
extern lv_obj_t * ui_DashBoard_Label_Time;
extern lv_obj_t * ui_DashBoard_Bar_lph;
extern lv_obj_t * ui_DashBoard_Label_LPHnum;
extern lv_obj_t * ui_DashBoard_Label_ODOonFuel;
extern lv_obj_t * ui_DashBoard_Label_SpeedDigit;
extern lv_obj_t * ui_DashBoard_Image_FreeWind;
extern lv_obj_t * ui_DashBoard_Image_ConditionHot;
extern lv_obj_t * ui_DashBoard_Image_ConditionCold;
extern lv_obj_t * ui_DashBoard_Image_RFirstVent;
extern lv_obj_t * ui_DashBoard_Image_RFirstVentAlert;
extern lv_obj_t * ui_DashBoard_Image_RSecondVent;
extern lv_obj_t * ui_DashBoard_Image_RSecondVentAlert;
extern lv_obj_t * ui_DashBoard_Image_RSecondVentAlert1;
extern void ui_event_DashBoard_Container_CenterContainer(lv_event_t * e);
extern lv_obj_t * ui_DashBoard_Container_CenterContainer;
extern void ui_event_DashBoard_Container_TripContainer(lv_event_t * e);
extern lv_obj_t * ui_DashBoard_Container_TripContainer;
extern void ui_event_DashBoard_Container_FuelContainer(lv_event_t * e);
extern lv_obj_t * ui_DashBoard_Container_FuelContainer;
extern lv_obj_t * ui_DashBoard_Label_EditionString;
// CUSTOM VARIABLES
extern lv_obj_t * uic_DashBoard_Label_q;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

