// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Fiona_Project

#ifndef UI_SCREEN_SCREENREFUEL_H
#define UI_SCREEN_SCREENREFUEL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_ScreenReFuel
extern void ui_Screen_ScreenReFuel_screen_init(void);
extern void ui_Screen_ScreenReFuel_screen_destroy(void);
extern lv_obj_t * ui_Screen_ScreenReFuel;
extern void ui_event_ScreenReFuel_Label_Label3(lv_event_t * e);
extern lv_obj_t * ui_ScreenReFuel_Label_Label3;
extern void ui_event_ScreenReFuel_Textarea_TACurrentFuel(lv_event_t * e);
extern lv_obj_t * ui_ScreenReFuel_Textarea_TACurrentFuel;
extern lv_obj_t * ui_ScreenReFuel_Label_Zapravleno;
extern void ui_event_ScreenReFuel_Textarea_TAPrise(lv_event_t * e);
extern lv_obj_t * ui_ScreenReFuel_Textarea_TAPrise;
extern lv_obj_t * ui_ScreenReFuel_Label_LitrPrise;
extern void ui_event_ScreenReFuel_Textarea_TAFuelToAdd(lv_event_t * e);
extern lv_obj_t * ui_ScreenReFuel_Textarea_TAFuelToAdd;
extern lv_obj_t * ui_ScreenReFuel_Label_Label5;
extern void ui_event_ScreenReFuel_Textarea_TAODO(lv_event_t * e);
extern lv_obj_t * ui_ScreenReFuel_Textarea_TAODO;
extern lv_obj_t * ui_ScreenReFuel_Label_Calibrate;
extern void ui_event_ScreenReFuel_Switch_SwitchFullTank(lv_event_t * e);
extern lv_obj_t * ui_ScreenReFuel_Switch_SwitchFullTank;
extern void ui_event_ScreenReFuel_Label_RefSaveLBtn(lv_event_t * e);
extern lv_obj_t * ui_ScreenReFuel_Label_RefSaveLBtn;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

