// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Fiona_Project

#ifndef UI_SCREEN_SYSTEM_H
#define UI_SCREEN_SYSTEM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_System
extern void ui_Screen_System_screen_init(void);
extern void ui_Screen_System_screen_destroy(void);
extern lv_obj_t * ui_Screen_System;
extern lv_obj_t * ui_System_Tabview_SystemTabView;
extern void ui_event_System_Tabpage_Refuel(lv_event_t * e);
extern lv_obj_t * ui_System_Tabpage_Refuel;
extern lv_obj_t * ui_System_Bar_FuelTank;
extern lv_obj_t * ui_System_Label_Zapravleno;
extern void ui_event_System_Textarea_TAPrise(lv_event_t * e);
extern lv_obj_t * ui_System_Textarea_TAPrise;
extern lv_obj_t * ui_System_Label_LitrPrise;
extern lv_obj_t * ui_System_Label_Label4;
extern void ui_event_System_Textarea_TAODO(lv_event_t * e);
extern lv_obj_t * ui_System_Textarea_TAODO;
extern lv_obj_t * ui_System_Label_Calibrate;
extern void ui_event_System_Switch_SwitchFullTank(lv_event_t * e);
extern lv_obj_t * ui_System_Switch_SwitchFullTank;
extern void ui_event_System_Textarea_TACurrentFuel(lv_event_t * e);
extern lv_obj_t * ui_System_Textarea_TACurrentFuel;
extern void ui_event_System_Label_SaveLBtn(lv_event_t * e);
extern lv_obj_t * ui_System_Label_SaveLBtn;
extern void ui_event_System_Textarea_TAFuelToAdd(lv_event_t * e);
extern lv_obj_t * ui_System_Textarea_TAFuelToAdd;
extern void ui_event_System_Tabpage_Setting(lv_event_t * e);
extern lv_obj_t * ui_System_Tabpage_Setting;
extern void ui_event_System_Textarea_TimeTextArea(lv_event_t * e);
extern lv_obj_t * ui_System_Textarea_TimeTextArea;
extern void ui_event_System_Label_SaveLBtn2(lv_event_t * e);
extern lv_obj_t * ui_System_Label_SaveLBtn2;
extern lv_obj_t * ui_System_Label_TimeLbl;
extern void ui_event_System_Label_TimeLBtn(lv_event_t * e);
extern lv_obj_t * ui_System_Label_TimeLBtn;
extern void ui_event_System_Label_TimeLBtnR(lv_event_t * e);
extern lv_obj_t * ui_System_Label_TimeLBtnR;
extern lv_obj_t * ui_System_Label_LightLbl;
extern lv_obj_t * ui_System_Label_LightMarkLbl;
extern lv_obj_t * ui_System_Label_DarkMarkLbl;
extern void ui_event_System_Slider_SliderLight(lv_event_t * e);
extern lv_obj_t * ui_System_Slider_SliderLight;
extern void ui_event_System_Slider_SliderDark(lv_event_t * e);
extern lv_obj_t * ui_System_Slider_SliderDark;
extern lv_obj_t * ui_System_Label_CurrentLight;
extern void ui_event_System_Slider_SliderBridges(lv_event_t * e);
extern lv_obj_t * ui_System_Slider_SliderBridges;
extern void ui_event_System_Label_CalibrateMCU(lv_event_t * e);
extern lv_obj_t * ui_System_Label_CalibrateMCU;
extern void ui_event_System_Label_FanPlus(lv_event_t * e);
extern lv_obj_t * ui_System_Label_FanPlus;
extern void ui_event_System_Label_FanMinus(lv_event_t * e);
extern lv_obj_t * ui_System_Label_FanMinus;
extern void ui_event_System_Label_FanApply(lv_event_t * e);
extern lv_obj_t * ui_System_Label_FanApply;
extern void ui_event_System_Label_FanSaved(lv_event_t * e);
extern lv_obj_t * ui_System_Label_FanSaved;
extern lv_obj_t * ui_System_Label_FanCalibLbl;
extern void ui_event_System_Dropdown_DropdownFanDot(lv_event_t * e);
extern lv_obj_t * ui_System_Dropdown_DropdownFanDot;
extern void ui_event_System_Tabpage_DebugArduino(lv_event_t * e);
extern lv_obj_t * ui_System_Tabpage_DebugArduino;
extern void ui_event_System_Textarea_TextAreaArduino(lv_event_t * e);
extern lv_obj_t * ui_System_Textarea_TextAreaArduino;
extern void ui_event_System_Tabpage_DebugESP32(lv_event_t * e);
extern lv_obj_t * ui_System_Tabpage_DebugESP32;
extern void ui_event_System_Textarea_TextAreaESP(lv_event_t * e);
extern lv_obj_t * ui_System_Textarea_TextAreaESP;
extern void ui_event_System_Tabpage_DebugScreen(lv_event_t * e);
extern lv_obj_t * ui_System_Tabpage_DebugScreen;
extern void ui_event_System_Textarea_TextAreaScreen(lv_event_t * e);
extern lv_obj_t * ui_System_Textarea_TextAreaScreen;
extern lv_obj_t * ui_System_Image_SDBack;
extern lv_obj_t * ui_System_Image_SDGrey;
extern lv_obj_t * ui_System_Image_SDRed;
extern lv_obj_t * ui_System_Image_ArduinoBack;
extern lv_obj_t * ui_System_Image_ArduinoGrey;
extern lv_obj_t * ui_System_Image_ArduinoRed;
extern lv_obj_t * ui_System_Image_ESP32Back;
extern lv_obj_t * ui_System_Image_ESP32Grey;
extern lv_obj_t * ui_System_Image_ESP32Red;
extern lv_obj_t * ui_System_Image_SpeachBack;
extern lv_obj_t * ui_System_Image_SpeachGrey;
extern lv_obj_t * ui_System_Image_SpeachRed;
extern lv_obj_t * ui_System_Image_StatBack;
extern lv_obj_t * ui_System_Image_StatGrey;
extern lv_obj_t * ui_System_Image_StatRed;
extern lv_obj_t * ui_System_Image_PresetBack;
extern lv_obj_t * ui_System_Image_PresetGrey;
extern lv_obj_t * ui_System_Image_PresetRed;
extern lv_obj_t * ui_System_Label_Label6;
extern lv_obj_t * ui_System_Label_Label7;
extern lv_obj_t * ui_System_Label_Label8;
extern lv_obj_t * ui_System_Label_Label9;
extern lv_obj_t * ui_System_Label_Label10;
extern lv_obj_t * ui_System_Label_Label11;
extern void ui_event_System_Label_Label1(lv_event_t * e);
extern lv_obj_t * ui_System_Label_Label1;
extern lv_obj_t * ui_System_Keyboard_KeyboardForTab;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

