// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Fiona_Project

#ifndef UI_SCREEN_SPLASHSCREEN_H
#define UI_SCREEN_SPLASHSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_SplashScreen
extern void ui_Screen_SplashScreen_screen_init(void);
extern void ui_Screen_SplashScreen_screen_destroy(void);
extern lv_obj_t * ui_Screen_SplashScreen;
extern lv_obj_t * ui_SplashScreen_Image_Logo;
extern void ui_event_SplashScreen_Label_Clock(lv_event_t * e);
extern lv_obj_t * ui_SplashScreen_Label_Clock;
extern lv_obj_t * ui_SplashScreen_Label_FionaSpeachLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

