// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Fiona_Project

#include "../ui.h"

lv_obj_t * ui_Screen_ClimateControl = NULL;
lv_obj_t * ui_ClimateControl_Label_LabelCC = NULL;
lv_obj_t * ui_ClimateControl_Label_Label5 = NULL;
lv_obj_t * ui_ClimateControl_Slider_TempSlider = NULL;
lv_obj_t * ui_ClimateControl_Label_Label2 = NULL;
lv_obj_t * ui_ClimateControl_Slider_AlignSlider = NULL;
lv_obj_t * ui_ClimateControl_Label_Label3 = NULL;
lv_obj_t * ui_ClimateControl_Slider_FlowSlider = NULL;
lv_obj_t * ui_ClimateControl_Switch_TempSwitch = NULL;
lv_obj_t * ui_ClimateControl_Switch_AlignSwitch = NULL;
lv_obj_t * ui_ClimateControl_Switch_FlpwSwitch = NULL;
// event funtions
void ui_event_ClimateControl_Label_LabelCC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ToHomeClick(e);
        _ui_screen_change(&ui_Screen_DashBoard, LV_SCR_LOAD_ANIM_OVER_LEFT, 100, 100, &ui_Screen_DashBoard_screen_init);
    }
}

void ui_event_ClimateControl_Slider_TempSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        TempChanged(e);
    }
}

void ui_event_ClimateControl_Slider_AlignSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        AlignChanged(e);
    }
}

void ui_event_ClimateControl_Slider_FlowSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        FlowChanged(e);
    }
}

void ui_event_ClimateControl_Switch_TempSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        TempAutoChange(e);
    }
}

void ui_event_ClimateControl_Switch_AlignSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        AlignAutoChange(e);
    }
}

void ui_event_ClimateControl_Switch_FlpwSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        FlowAutoChange(e);
    }
}

// build funtions

void ui_Screen_ClimateControl_screen_init(void)
{
    ui_Screen_ClimateControl = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_ClimateControl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Screen_ClimateControl, &ui_img_global_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClimateControl_Label_LabelCC = lv_label_create(ui_Screen_ClimateControl);
    lv_obj_set_width(ui_ClimateControl_Label_LabelCC, 400);
    lv_obj_set_height(ui_ClimateControl_Label_LabelCC, 30);
    lv_obj_set_x(ui_ClimateControl_Label_LabelCC, 0);
    lv_obj_set_y(ui_ClimateControl_Label_LabelCC, 10);
    lv_obj_set_align(ui_ClimateControl_Label_LabelCC, LV_ALIGN_TOP_MID);
    lv_obj_set_ext_click_area(ui_ClimateControl_Label_LabelCC, 20);
    lv_label_set_long_mode(ui_ClimateControl_Label_LabelCC, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_ClimateControl_Label_LabelCC, "Климат...");
    lv_obj_add_flag(ui_ClimateControl_Label_LabelCC, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ClimateControl_Label_LabelCC,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_ClimateControl_Label_LabelCC, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ClimateControl_Label_LabelCC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ClimateControl_Label_LabelCC, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ClimateControl_Label_LabelCC, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ClimateControl_Label_LabelCC, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClimateControl_Label_Label5 = lv_label_create(ui_Screen_ClimateControl);
    lv_obj_set_width(ui_ClimateControl_Label_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClimateControl_Label_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClimateControl_Label_Label5, 35);
    lv_obj_set_y(ui_ClimateControl_Label_Label5, 70);
    lv_obj_set_align(ui_ClimateControl_Label_Label5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_ClimateControl_Label_Label5, "Температура");
    lv_obj_remove_flag(ui_ClimateControl_Label_Label5,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_ClimateControl_Label_Label5, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ClimateControl_Label_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ClimateControl_Label_Label5, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClimateControl_Slider_TempSlider = lv_slider_create(ui_Screen_ClimateControl);
    lv_slider_set_range(ui_ClimateControl_Slider_TempSlider, 0, 255);
    lv_slider_set_value(ui_ClimateControl_Slider_TempSlider, 128, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ClimateControl_Slider_TempSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_ClimateControl_Slider_TempSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ClimateControl_Slider_TempSlider, 900);
    lv_obj_set_height(ui_ClimateControl_Slider_TempSlider, 60);
    lv_obj_set_x(ui_ClimateControl_Slider_TempSlider, 35);
    lv_obj_set_y(ui_ClimateControl_Slider_TempSlider, -150);
    lv_obj_set_align(ui_ClimateControl_Slider_TempSlider, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_ClimateControl_Slider_TempSlider, lv_color_hex(0x0000FF),
                              LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClimateControl_Slider_TempSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ClimateControl_Slider_TempSlider,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ClimateControl_Slider_TempSlider,
                                                                                  lv_obj_get_style_pad_right(ui_ClimateControl_Slider_TempSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ClimateControl_Label_Label2 = lv_label_create(ui_Screen_ClimateControl);
    lv_obj_set_width(ui_ClimateControl_Label_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClimateControl_Label_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClimateControl_Label_Label2, 36);
    lv_obj_set_y(ui_ClimateControl_Label_Label2, 268);
    lv_obj_set_align(ui_ClimateControl_Label_Label2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_ClimateControl_Label_Label2,
                      "Салон---------------------------Ноги---------------------------Стекло");
    lv_obj_remove_flag(ui_ClimateControl_Label_Label2,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_ClimateControl_Label_Label2, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ClimateControl_Label_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ClimateControl_Label_Label2, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClimateControl_Slider_AlignSlider = lv_slider_create(ui_Screen_ClimateControl);
    lv_slider_set_range(ui_ClimateControl_Slider_AlignSlider, 0, 255);
    lv_slider_set_value(ui_ClimateControl_Slider_AlignSlider, 128, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ClimateControl_Slider_AlignSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_ClimateControl_Slider_AlignSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ClimateControl_Slider_AlignSlider, 900);
    lv_obj_set_height(ui_ClimateControl_Slider_AlignSlider, 60);
    lv_obj_set_x(ui_ClimateControl_Slider_AlignSlider, 35);
    lv_obj_set_y(ui_ClimateControl_Slider_AlignSlider, 50);
    lv_obj_set_align(ui_ClimateControl_Slider_AlignSlider, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_ClimateControl_Slider_AlignSlider, lv_color_hex(0x0000FF),
                              LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClimateControl_Slider_AlignSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ClimateControl_Slider_AlignSlider,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ClimateControl_Slider_AlignSlider,
                                                                                  lv_obj_get_style_pad_right(ui_ClimateControl_Slider_AlignSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ClimateControl_Label_Label3 = lv_label_create(ui_Screen_ClimateControl);
    lv_obj_set_width(ui_ClimateControl_Label_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClimateControl_Label_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClimateControl_Label_Label3, 35);
    lv_obj_set_y(ui_ClimateControl_Label_Label3, 446);
    lv_obj_set_align(ui_ClimateControl_Label_Label3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_ClimateControl_Label_Label3, "Сила");
    lv_obj_remove_flag(ui_ClimateControl_Label_Label3,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_ClimateControl_Label_Label3, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ClimateControl_Label_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ClimateControl_Label_Label3, &ui_font_BaseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClimateControl_Slider_FlowSlider = lv_slider_create(ui_Screen_ClimateControl);
    lv_slider_set_range(ui_ClimateControl_Slider_FlowSlider, 0, 255);
    lv_slider_set_value(ui_ClimateControl_Slider_FlowSlider, 128, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ClimateControl_Slider_FlowSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_ClimateControl_Slider_FlowSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ClimateControl_Slider_FlowSlider, 900);
    lv_obj_set_height(ui_ClimateControl_Slider_FlowSlider, 60);
    lv_obj_set_x(ui_ClimateControl_Slider_FlowSlider, 35);
    lv_obj_set_y(ui_ClimateControl_Slider_FlowSlider, 230);
    lv_obj_set_align(ui_ClimateControl_Slider_FlowSlider, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_ClimateControl_Slider_FlowSlider, lv_color_hex(0x0000FF),
                              LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClimateControl_Slider_FlowSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ClimateControl_Slider_FlowSlider,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ClimateControl_Slider_FlowSlider,
                                                                                  lv_obj_get_style_pad_right(ui_ClimateControl_Slider_FlowSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ClimateControl_Switch_TempSwitch = lv_switch_create(ui_Screen_ClimateControl);
    lv_obj_set_width(ui_ClimateControl_Switch_TempSwitch, 66);
    lv_obj_set_height(ui_ClimateControl_Switch_TempSwitch, 25);
    lv_obj_set_x(ui_ClimateControl_Switch_TempSwitch, -451);
    lv_obj_set_y(ui_ClimateControl_Switch_TempSwitch, -150);
    lv_obj_set_align(ui_ClimateControl_Switch_TempSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ClimateControl_Switch_TempSwitch, lv_color_hex(0x000810), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClimateControl_Switch_TempSwitch, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ClimateControl_Switch_TempSwitch, lv_color_hex(0x00FF17), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClimateControl_Switch_TempSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ClimateControl_Switch_AlignSwitch = lv_switch_create(ui_Screen_ClimateControl);
    lv_obj_set_width(ui_ClimateControl_Switch_AlignSwitch, 66);
    lv_obj_set_height(ui_ClimateControl_Switch_AlignSwitch, 25);
    lv_obj_set_x(ui_ClimateControl_Switch_AlignSwitch, -452);
    lv_obj_set_y(ui_ClimateControl_Switch_AlignSwitch, 50);
    lv_obj_set_align(ui_ClimateControl_Switch_AlignSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ClimateControl_Switch_AlignSwitch, lv_color_hex(0x000810),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClimateControl_Switch_AlignSwitch, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ClimateControl_Switch_AlignSwitch, lv_color_hex(0x00FF17),
                              LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClimateControl_Switch_AlignSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ClimateControl_Switch_FlpwSwitch = lv_switch_create(ui_Screen_ClimateControl);
    lv_obj_set_width(ui_ClimateControl_Switch_FlpwSwitch, 66);
    lv_obj_set_height(ui_ClimateControl_Switch_FlpwSwitch, 25);
    lv_obj_set_x(ui_ClimateControl_Switch_FlpwSwitch, -448);
    lv_obj_set_y(ui_ClimateControl_Switch_FlpwSwitch, 229);
    lv_obj_set_align(ui_ClimateControl_Switch_FlpwSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ClimateControl_Switch_FlpwSwitch, lv_color_hex(0x000810), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClimateControl_Switch_FlpwSwitch, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ClimateControl_Switch_FlpwSwitch, lv_color_hex(0x00FF17), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClimateControl_Switch_FlpwSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ClimateControl_Label_LabelCC, ui_event_ClimateControl_Label_LabelCC, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ClimateControl_Slider_TempSlider, ui_event_ClimateControl_Slider_TempSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ClimateControl_Slider_AlignSlider, ui_event_ClimateControl_Slider_AlignSlider, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_ClimateControl_Slider_FlowSlider, ui_event_ClimateControl_Slider_FlowSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ClimateControl_Switch_TempSwitch, ui_event_ClimateControl_Switch_TempSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ClimateControl_Switch_AlignSwitch, ui_event_ClimateControl_Switch_AlignSwitch, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_ClimateControl_Switch_FlpwSwitch, ui_event_ClimateControl_Switch_FlpwSwitch, LV_EVENT_ALL, NULL);

}

void ui_Screen_ClimateControl_screen_destroy(void)
{
    if(ui_Screen_ClimateControl) lv_obj_del(ui_Screen_ClimateControl);

    // NULL screen variables
    ui_Screen_ClimateControl = NULL;
    ui_ClimateControl_Label_LabelCC = NULL;
    ui_ClimateControl_Label_Label5 = NULL;
    ui_ClimateControl_Slider_TempSlider = NULL;
    ui_ClimateControl_Label_Label2 = NULL;
    ui_ClimateControl_Slider_AlignSlider = NULL;
    ui_ClimateControl_Label_Label3 = NULL;
    ui_ClimateControl_Slider_FlowSlider = NULL;
    ui_ClimateControl_Switch_TempSwitch = NULL;
    ui_ClimateControl_Switch_AlignSwitch = NULL;
    ui_ClimateControl_Switch_FlpwSwitch = NULL;

}
