[env:esp32dev]
framework = arduino
monitor_speed = 115200
platform = espressif32
board = esp32dev
upload_speed = 921600
;build_flags = -DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
board_build.filesystem = littlefs
build_src_filter = +<*> -<ClimateController.cpp> -<FanController.cpp>
board_build.partitions = partitions.csv
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.5
    https://github.com/rfetick/MPU6050_light.git