// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Fiona_Project

#ifndef _FIONA_PROJECT_UI_H
#define _FIONA_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen_DashBoard.h"
#include "screens/ui_Screen_System.h"
#include "screens/ui_Screen_ClimateControl.h"
#include "screens/ui_Screen_SplashScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui_Startevents____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bg_red_png);    // assets/bg_red.png
LV_IMG_DECLARE(ui_img_small_blue_png);    // assets/small_blue.png
LV_IMG_DECLARE(ui_img_speed_png);    // assets/speed.png
LV_IMG_DECLARE(ui_img_akb_png);    // assets/AKB.png
LV_IMG_DECLARE(ui_img_battery_png);    // assets/battery.png
LV_IMG_DECLARE(ui_img_h_l_png);    // assets/h_l.png
LV_IMG_DECLARE(ui_img_fuel_png);    // assets/FUEL.png
LV_IMG_DECLARE(ui_img_ofe_png);    // assets/ofe.png
LV_IMG_DECLARE(ui_img_oil_level_png);    // assets/oil_level.png
LV_IMG_DECLARE(ui_img_twater_png);    // assets/TWater.png
LV_IMG_DECLARE(ui_img_water_temp2_png);    // assets/water_temp2.png
LV_IMG_DECLARE(ui_img_water_temp_png);    // assets/water_temp.png
LV_IMG_DECLARE(ui_img_esp_png);    // assets/esp.png
LV_IMG_DECLARE(ui_img_1173513873);    // assets/cool-cold.png
LV_IMG_DECLARE(ui_img_1279366634);    // assets/cool-hot.png
LV_IMG_DECLARE(ui_img_1173515923);    // assets/cool-cond.png
LV_IMG_DECLARE(ui_img_cooller2_png);    // assets/cooller2.png
LV_IMG_DECLARE(ui_img_cooller1a_png);    // assets/cooller1a.png
LV_IMG_DECLARE(ui_img_cooller1_png);    // assets/cooller1.png
LV_IMG_DECLARE(ui_img_cooller2a_png);    // assets/cooller2a.png
LV_IMG_DECLARE(ui_img_cooller3_png);    // assets/cooller3.png
LV_IMG_DECLARE(ui_img_cyan_cat_png);    // assets/cyan_cat.png
LV_IMG_DECLARE(ui_img_green_cat_png);    // assets/green_cat.png
LV_IMG_DECLARE(ui_img_yellow_cat_png);    // assets/yellow_cat.png
LV_IMG_DECLARE(ui_img_red_cat_png);    // assets/red_cat.png
LV_IMG_DECLARE(ui_img_global_bg_png);    // assets/global_bg.png
LV_IMG_DECLARE(ui_img_black_png);    // assets/black.png
LV_IMG_DECLARE(ui_img_grey_png);    // assets/grey.png
LV_IMG_DECLARE(ui_img_red_png);    // assets/red.png
LV_IMG_DECLARE(ui_img_fordlogo_png);    // assets/FordLogo.png


// FONTS
LV_FONT_DECLARE(ui_font_BaseFont);
LV_FONT_DECLARE(ui_font_BaseFont20);
LV_FONT_DECLARE(ui_font_Digital);
LV_FONT_DECLARE(ui_font_LedSymbol);
LV_FONT_DECLARE(ui_font_BaseFont16);
LV_FONT_DECLARE(ui_font_SSaverFont);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
