// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Fiona_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void DashOnFocused(lv_event_t * e);
void OnDefocused(lv_event_t * e);
void DashboardOnLoad(lv_event_t * e);
void GetInternetTime(lv_event_t * e);
void OnTripClick(lv_event_t * e);
void ToRefuelClk(lv_event_t * e);
void RezChange(lv_event_t * e);
void ToHomeClick(lv_event_t * e);
void TempAutoChange(lv_event_t * e);
void AlignAutoChange(lv_event_t * e);
void FlowAutoChange(lv_event_t * e);
void TempChanged(lv_event_t * e);
void AlignChanged(lv_event_t * e);
void FlowChanged(lv_event_t * e);
void ToSettingClk(lv_event_t * e);
void ToDebugClk(lv_event_t * e);
void OnScreenSaverClk(lv_event_t * e);
void OnTankFocus(lv_event_t * e);
void TankDeFocus(lv_event_t * e);
void OnPriseFocus(lv_event_t * e);
void OnPriseDeFocus(lv_event_t * e);
void OnAddedFocus(lv_event_t * e);
void OnAddedDeFocus(lv_event_t * e);
void OnOdoFocus(lv_event_t * e);
void OnOdoDeFocus(lv_event_t * e);
void OnCalibrateClicked(lv_event_t * e);
void OnSaveClk(lv_event_t * e);
void TimeOnFocus(lv_event_t * e);
void TimeOnDeFocus(lv_event_t * e);
void OnSaveClick(lv_event_t * e);
void OnTimeApply(lv_event_t * e);
void OnTimeAsk(lv_event_t * e);
void OnLightSliderThresholdChanged(lv_event_t * e);
void OnSliderThresholdChanged(lv_event_t * e);
void OnLightSliderChanged(lv_event_t * e);
void CalibrateMCUBtnClick(lv_event_t * e);
void FanPlusClk(lv_event_t * e);
void FanMinusClk(lv_event_t * e);
void FanSaveApply(lv_event_t * e);
void FanDefaultClick(lv_event_t * e);
void FanChangeDot(lv_event_t * e);
void DeviceChange(lv_event_t * e);
void SpeedChange(lv_event_t * e);
void RXChangeDot(lv_event_t * e);
void TXChangeDot(lv_event_t * e);
void OnTestScreenUart(lv_event_t * e);
void OnDebugScreen(lv_event_t * e);
void OnSdClick(lv_event_t * e);
void OnArduinoClk(lv_event_t * e);
void OnESPClk(lv_event_t * e);
void OnSpeachClk(lv_event_t * e);
void OnStatClk(lv_event_t * e);
void OnPresetsClk(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
