// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Fiona_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void DashOnFocused(lv_event_t * e);
void OnDefocused(lv_event_t * e);
void DashboardOnLoad(lv_event_t * e);
void GetInternetTime(lv_event_t * e);
void OnTripClick(lv_event_t * e);
void RezChange(lv_event_t * e);
void OnRefuelFocused(lv_event_t * e);
void OnRefueDefFocused(lv_event_t * e);
void OnCalibrateClicked(lv_event_t * e);
void SaveChangeBtnClick(lv_event_t * e);
void SettingFocused(lv_event_t * e);
void SettingDeFocused(lv_event_t * e);
void SaveSettingChangeBtnClick(lv_event_t * e);
void SetTimeClicked(lv_event_t * e);
void SetTimeRClicked(lv_event_t * e);
void OnLightSliderThresholdChanged(lv_event_t * e);
void OnSliderThresholdChanged(lv_event_t * e);
void OnLightSliderChanged(lv_event_t * e);
void CalibrateMCUBtnClick(lv_event_t * e);
void FanPlusClk(lv_event_t * e);
void FanMinusClk(lv_event_t * e);
void FanSaveApply(lv_event_t * e);
void FanChangeDot(lv_event_t * e);
void OnDebugArduino(lv_event_t * e);
void OnDebugESP32(lv_event_t * e);
void OnDebugScreen(lv_event_t * e);
void ToHomeClick(lv_event_t * e);
void TempChanged(lv_event_t * e);
void AlignChanged(lv_event_t * e);
void FlowChanged(lv_event_t * e);
void TempAutoChange(lv_event_t * e);
void AlignAutoChange(lv_event_t * e);
void FlowAutoChange(lv_event_t * e);
void OnScreenSaverClk(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
