// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Fiona_Project

#include "ui.h"
#include "fiona_core.h"
#include "system_actions.h"
#include "ui_debug_helpers.h"
#include "CarData.h"
#include "uart_protocol.h"
#include "sd_utils.h"
#include "fiona_brain.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <time.h>

// Внешние переменные и функции из ядра (для заправки)
extern lv_subject_t subject_speed;
extern lv_subject_t subject_rpm;
extern lv_subject_t subject_bat;
extern lv_subject_t subject_fuel;
extern lv_subject_t subject_temp;
extern lv_subject_t subject_odo;
extern lv_subject_t subject_range;
extern lv_subject_t subject_lph;
extern lv_subject_t subject_trip_time;
extern lv_subject_t subject_trip_pause;
extern lv_subject_t subject_trip_fuel;
extern lv_subject_t subject_trip_dist;
extern lv_subject_t subject_clock_color;
extern lv_subject_t subject_dash_message;
extern lv_timer_t * poll_timer;
extern lv_timer_t * clock_timer;
extern bool screensaver_active;

// ---------- Переменные для ручного выбора стиля ----------
static uint8_t selected_style = 0;      // 0=авто, 1=спорт(циан), 2=семья(зелёный), 3=агрессивный(жёлтый)
static lv_timer_t * style_confirm_timer = NULL;

// Прототип функции фиксации стиля
static void style_confirm_timer_cb(lv_timer_t * t);

/* ---------------------------------------------------------------------------
 * Обработчики событий дашборда и системных действий
 * --------------------------------------------------------------------------- */
void DashOnFocused(lv_event_t * e) {}
void OnDefocused(lv_event_t * e) {}

void DashboardOnLoad(lv_event_t * e) {
    fiona_core_dashboard_on_load();
}

void GetInternetTime(lv_event_t * e) {
    fiona_core_request_internet_time();
    uart_send_to_gateway(MSG_REQ_TIME, NULL, 0);
}

void OnTripClick(lv_event_t * e) {
    uart_send_to_gateway(MSG_TRIP_TOGGLE, NULL, 0);
}

// ------------------- Заправка -------------------

void OnRefuelFocused(lv_event_t * e) {
    CarData *data = CarData_Get();
    if (!data) return;

    char buf[32];
    snprintf(buf, sizeof(buf), "%.1f", data->fuelValue);
    lv_textarea_set_text(ui_System_Textarea_TACurrentFuel, buf);

    uint32_t miles = (uint32_t)(data->odoKm * 0.621371f);
    snprintf(buf, sizeof(buf), "%u", miles);
    lv_textarea_set_text(ui_System_Textarea_TAODO, buf);

    snprintf(buf, sizeof(buf), "%.2f", data->fuelPrice);
    lv_textarea_set_text(ui_System_Textarea_TAPrise, buf);

    lv_textarea_set_text(ui_System_Textarea_TAFuelToAdd, "");
    lv_textarea_set_text(ui_System_Textarea_TAPrise, "");
    lv_obj_add_flag(ui_System_Label_SaveLBtn, LV_OBJ_FLAG_HIDDEN);
    lv_obj_remove_state(ui_System_Switch_SwitchFullTank, LV_STATE_CHECKED);
}

void OnRefueDefFocused(lv_event_t * e) {}
void OnCalibrateClicked(lv_event_t * e) {}

void SaveChangeBtnClick(lv_event_t * e) {
    CarData *data = CarData_Get();
    if (!data) return;

    const char *fuel_add_text = lv_textarea_get_text(ui_System_Textarea_TAFuelToAdd);
    const char *fuel_curr_text = lv_textarea_get_text(ui_System_Textarea_TACurrentFuel);
    const char *odo_text = lv_textarea_get_text(ui_System_Textarea_TAODO);
    const char *price_text = lv_textarea_get_text(ui_System_Textarea_TAPrise);
    bool switch_full_tank = lv_obj_has_state(ui_System_Switch_SwitchFullTank, LV_STATE_CHECKED);

    bool odo_filled = (odo_text[0] != '\0');
    bool fuel_add_filled = (fuel_add_text[0] != '\0');
    bool fuel_curr_filled = (fuel_curr_text[0] != '\0');
    bool price_filled = (price_text[0] != '\0');

    bool saved = false;

    if (fuel_curr_filled && odo_filled) {
        float fuel_current = atof(fuel_curr_text);
        uint32_t miles = atoi(odo_text);
        uint32_t odo_km = (uint32_t)(miles * 1.60934f);

        CarData_Lock(100);
        data->fuelValue = fuel_current;
        data->odoKm = odo_km;
        CarData_Unlock();

        uart_send_set_fuel_level(fuel_current);
        uart_send_set_odo(odo_km);

        if (price_filled) {
            float price = atof(price_text);
            CarData_Lock(100);
            data->fuelPrice = price;
            CarData_Unlock();
        }
        saved = true;
    }

    if (fuel_add_filled && price_filled) {
        float fuel_add = atof(fuel_add_text);
        float price = atof(price_text);

        uart_send_refuel_data(fuel_add, price);

        CarData_Lock(100);
        data->fuelPrice = price;
        CarData_Unlock();

        RefuelRecord rec;
        rec.timestamp = time(NULL);
        rec.liters = fuel_add;
        rec.price = price;
        if (odo_filled) {
            uint32_t miles = atoi(odo_text);
            rec.odo_km = (uint32_t)(miles * 1.60934f);
        } else {
            rec.odo_km = data->odoKm;
        }
        rec.cost = fuel_add * price;
        rec.calibration = switch_full_tank;

        sd_write_refuel_record(&rec);

        CarData_Lock(100);
        memcpy(&data->lastRefuel, &rec, sizeof(RefuelRecord));
        if (switch_full_tank && odo_filled) {
            uint32_t miles = atoi(odo_text);
            data->odoKm = (uint32_t)(miles * 1.60934f);
            uart_send_set_odo(data->odoKm);
            uart_send_full_tank_flag(1);
        }
        CarData_Unlock();
        saved = true;
    }

    if (saved) {
        lv_obj_add_flag(ui_System_Label_SaveLBtn, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_System_Label_Zapravleno, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_System_Textarea_TAFuelToAdd, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_System_Label_LitrPrise, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_System_Textarea_TAPrise, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_System_Label_Calibrate, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_System_Switch_SwitchFullTank, LV_OBJ_FLAG_HIDDEN);

        lv_textarea_set_text(ui_System_Textarea_TACurrentFuel, "");
        lv_textarea_set_text(ui_System_Textarea_TAODO, "");
        lv_textarea_set_text(ui_System_Textarea_TAFuelToAdd, "");
        lv_textarea_set_text(ui_System_Textarea_TAPrise, "");

        _ui_screen_change(&ui_Screen_DashBoard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_DashBoard_screen_init);
    }
}

// ------------------- Настройки времени -------------------
void SetTimeClicked(lv_event_t * e) {
    system_actions_set_time_from_textarea();
}

void SetTimeRClicked(lv_event_t * e) {
    system_actions_request_time();
}

/* ---------------------------------------------------------------------------
 * Вкладка «Настройки»: обработчики слайдеров и сохранения
 * --------------------------------------------------------------------------- */

void SettingFocused(lv_event_t * e) {
    CarData *data = CarData_Get();
    if (!data) return;

    CarData_Lock(10);
    uint8_t brightness = data->backlight_brightness;
    uint8_t threshold_bright = data->light_threshold_bright;
    uint8_t threshold_dark = data->light_threshold_dark;
    CarData_Unlock();

    lv_slider_set_value(ui_System_Slider_SliderBridges, brightness, LV_ANIM_OFF);
    lv_slider_set_value(ui_System_Slider_SliderLight, threshold_bright, LV_ANIM_OFF);
    lv_slider_set_value(ui_System_Slider_SliderDark, threshold_dark, LV_ANIM_OFF);
}

void SettingDeFocused(lv_event_t * e) {}

void OnLightSliderChanged(lv_event_t * e) {
    CarData *data = CarData_Get();
    if (!data) return;

    int val = lv_slider_get_value(ui_System_Slider_SliderBridges);
    if (val < 0) val = 0;
    if (val > 100) val = 100;

    CarData_Lock(10);
    data->backlight_brightness = (uint8_t)val;
    CarData_Unlock();

    lv_label_set_text_fmt(ui_System_Label_LightLbl, "Яркость: %d", val);
}

void OnLightSliderThresholdChanged(lv_event_t * e) {
    CarData *data = CarData_Get();
    if (!data) return;

    int val = lv_slider_get_value(ui_System_Slider_SliderLight);
    if (val < 0) val = 0;
    if (val > 4095) val = 4095;

    CarData_Lock(10);
    data->light_threshold_bright = (uint8_t)val;
    CarData_Unlock();

    lv_label_set_text_fmt(ui_System_Label_LightMarkLbl, "Светло: %d", val);
}

void OnSliderThresholdChanged(lv_event_t * e) {
    CarData *data = CarData_Get();
    if (!data) return;

    int val = lv_slider_get_value(ui_System_Slider_SliderDark);
    if (val < 0) val = 0;
    if (val > 4095) val = 4095;

    CarData_Lock(10);
    data->light_threshold_dark = (uint8_t)val;
    CarData_Unlock();

    lv_label_set_text_fmt(ui_System_Label_DarkMarkLbl, "Темно: %d", val);
}

void SaveSettingChangeBtnClick(lv_event_t * e)
{
    fiona_core_save_car_data_to_nvs();
    lv_label_set_text(ui_System_Label_LightLbl, "Сохранено!");
}

/* ---------------------------------------------------------------------------
 * Остальные обработчики (климат-контроль и дебаг-вкладки)
 * --------------------------------------------------------------------------- */
void ToHomeClick(lv_event_t * e) {}
void TempChanged(lv_event_t * e) {}
void AlignChanged(lv_event_t * e) {}
void FlowChanged(lv_event_t * e) {}
void TempAutoChange(lv_event_t * e) {}
void AlignAutoChange(lv_event_t * e) {}
void FlowAutoChange(lv_event_t * e) {}

void OnDebugArduino(lv_event_t * e) {
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED) {
        ui_debug_update_arduino_tab();
    }
}

void OnDebugESP32(lv_event_t * e) {
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED) {
        ui_debug_update_esp32_tab();
    }
}

void OnDebugScreen(lv_event_t * e) {
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED) {
        ui_debug_update_screen_tab();
    }
}

// ------------------- Скринсейвер: пробуждение по клику -------------------
void OnScreenSaverClk(lv_event_t * e)
{
    fiona_core_deactivate_screensaver();
}

// ------------------- Калибровка IMU -------------------
void CalibrateMCUBtnClick(lv_event_t * e)
{
    uart_send_to_gateway(MSG_CALIBRATE_ACCEL, NULL, 0);
    lv_label_set_text(ui_DashBoard_Label_FionaSpeachLabelDash, "Калибровка запущена");
    extern bool calibration_active;
    calibration_active = true;
}

// ------------------- Ручной выбор стиля (клик по контейнеру) -------------------
void RezChange(lv_event_t * e)
{
    // Циклический перебор: 0(авто) -> 1(спокойный) -> 2(агрессивный) -> 3(спорт) -> 0...
    selected_style = (selected_style + 1) % 4;

    // Скрываем всех котов
    lv_obj_add_flag(ui_DashBoard_Image_ImageCyan, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_DashBoard_Image_ImageGreen, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_DashBoard_Image_ImageYellow, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_DashBoard_Image_ImageRed, LV_OBJ_FLAG_HIDDEN);

    // Показываем выбранного кота (соответствие стилям из fiona_brain)
    if (selected_style == 1) {
        lv_obj_remove_flag(ui_DashBoard_Image_ImageGreen, LV_OBJ_FLAG_HIDDEN);   // спокойный
    } else if (selected_style == 2) {
        lv_obj_remove_flag(ui_DashBoard_Image_ImageYellow, LV_OBJ_FLAG_HIDDEN);  // агрессивный
    } else if (selected_style == 3) {
        lv_obj_remove_flag(ui_DashBoard_Image_ImageCyan, LV_OBJ_FLAG_HIDDEN);    // спорт
    }
    // selected_style == 0 – все коты скрыты

    // Показываем индикатор ручного режима (ImageSpeed)
    lv_obj_remove_flag(ui_DashBoard_Image_ImageSpeed, LV_OBJ_FLAG_HIDDEN);

    // Перезапускаем таймер подтверждения на 5 секунд
    if (style_confirm_timer) {
        lv_timer_del(style_confirm_timer);
    }
    style_confirm_timer = lv_timer_create(style_confirm_timer_cb, 5000, NULL);
}

// Таймер подтверждения: через 5 секунд после последнего клика фиксируем стиль
static void style_confirm_timer_cb(lv_timer_t * t)
{
    // Записываем выбранный стиль в ручной режим
    FionaState *state = fiona_brain_get_state();
    if (state) {
        state->manual_style = selected_style;
    }

    // Скрываем индикатор ручного режима
    lv_obj_add_flag(ui_DashBoard_Image_ImageSpeed, LV_OBJ_FLAG_HIDDEN);

    // Удаляем таймер
    lv_timer_del(t);
    style_confirm_timer = NULL;
}

// ------------------- Пустые обработчики ImageAnim -------------------
void ImageAnimOnLoad(lv_event_t * e)
{
    // Your code here
}

void ImageAnimOnUnLoad(lv_event_t * e)
{
    // Your code here
}
void FanPlusClk(lv_event_t * e)
{
	// Your code here
}

void FanMinusClk(lv_event_t * e)
{
	// Your code here
}

void FanSaveApply(lv_event_t * e)
{
	// Your code here
}

void FanChangeDot(lv_event_t * e)
{
	// Your code here
}
